Kit/convertkit-wordpress

README.md
wp-convertkit.php

`Warning: Invalid argument supplied for foreach() in wp-convertkit.php on line 398` was appearing in some pages.

Fix forms warning

---

README.md
admin/settings.php
lib/integration/wishlist_member.php

Fixes a bug causing syntax error when getting options

401 getting array data from function

---

README.md
admin/section/wishlist_member.php

Don't use method return in write context.

---

lib/convertkit-api.php

This will make it so if the API is slow or unreachable the site is not affected.

Avoid crashing on timeout

---

README.md
admin/section/base.php
admin/section/general.php
admin/section/wishlist_member.php
admin/settings.php
lib/convertkit-api.php
lib/integration/wishlist_member.php
lib/multi_value_field_table.php
lib/template-tags.php
readme.txt
views/backend/meta-boxes/meta-box.php
wp-convertkit.php

This version adds support for v3 of the ConvertKit API. #10

Version 1.4.0 of plugin

---

.gitignore
admin/section/general.php
lib/convertkit-api.php
readme.txt
wp-convertkit.php

Fix for version upgrade from v2 to v3 with different Form IDs.

Version 1.4.1

---

lib/convertkit-api.php
lib/integration/wishlist_member.php
readme.txt
wp-convertkit.php

Hey @davidlamarwheeler please take a look at this PR. Thanks!

Release 1.4.2

---

admin/section/general.php
admin/settings.php
lib/class-ck-widget-form.php
lib/convertkit-api.php
lib/integration/wishlist_member.php
lib/log.txt
wp-convertkit.php

- Add WP widget for form
- Updates form version to `v6`
- Add logger to help troubleshoot
- Add link to CK account if no forms available
- Add notice if can't connect to API

Version 1.4.3

---

admin/section/general.php
admin/section/wishlist_member.php
admin/settings.php
lib/convertkit-api.php
wp-convertkit.php

Adding CF7 integration

---

admin/class-convertkit-settings.php
admin/section/class-convertkit-settings-contactform7.php
admin/section/class-convertkit-settings-general.php
admin/section/class-convertkit-settings-wishlist.php
includes/class-ck-widget-form.php
includes/class-convertkit-api.php
includes/class-convertkit.php
readme.txt
wp-convertkit.php

* Add support for new form builder
* Remove unnecessary API calls
* Store form/landing page/tag data in WP Options
* Add update routine for refreshing local convertkit data

Version 1.6.0

---

includes/class-convertkit.php
readme.txt
views/backend/meta-boxes/meta-box.php
wp-convertkit.php

* Fix for landing pages not showing in the admin area drop down
* Fix for showing new landing pages on the front end of the site
* Added jquery to landing pages as new landing page builder does not include it

Version 1.6.1

---

bin/install-wp-tests.sh
circle.yml
package.json
phpcs.xml.dist
phpunit.xml.dist
tests/bootstrap.php
tests/test-sample.php

Closes #125
Adding circle.yml
Updating package.json

CircleCI 2.0 files.

---

admin/class-convertkit-settings.php
package-lock.json
package.json

Closes #115
Renamed the table row class for the ConvertKit Form section on category. Fixes incompatibility with Yoast plugin.

Fix category issue.

---

views/backend/meta-boxes/meta-box.php

Our metabox appears on the blog archive page. However, settings in the metabox have no effect, because our plugin does not filter the output of the archive page.
Closes #188

Add notice to metabox on blog archive page

---

views/backend/meta-boxes/meta-box.php

Reverts ConvertKit/ConvertKit-WordPress#189
Accidentally merged into master. Reverting.

Revert "Add notice to metabox on blog archive page"

---

admin/section/class-convertkit-settings-general.php

Add better explanation for debug checkbox in settings

---

admin/section/class-convertkit-settings-base.php
admin/section/class-convertkit-settings-general.php
admin/section/class-convertkit-settings-tools.php
includes/class-convertkit-api.php
includes/functions.php
package-lock.json
package.json
readme.txt
wp-convertkit.php

Release: 1.9.4

---

package.json
readme.txt
wp-convertkit.php

Reverts ConvertKit/convertkit-wordpress#250

Revert "Update changelog and stable tags for 1.9.5.1"

---

bin/package.sh

Reverts ConvertKit/convertkit-wordpress#249

Revert "Update package.sh with correct zip url"

---

admin/section/class-convertkit-settings-general.php
admin/section/class-convertkit-settings-tools.php
composer.lock
includes/class-convertkit-api.php
package.json
readme.txt
wp-convertkit.php

Reverts ConvertKit/convertkit-wordpress#248

Revert "Limit logs and prevent full API response logging"

---

admin/class-convertkit-settings.php
admin/class-convertkit-tinymce.php
admin/class-multi-value-field-table.php
admin/section/class-convertkit-settings-contactform7.php
admin/section/class-convertkit-settings-general.php
admin/section/class-convertkit-settings-tools.php
admin/section/class-convertkit-settings-wishlist.php
includes/class-ck-widget-form.php
includes/class-convertkit-api.php
includes/class-convertkit-custom-content.php
includes/class-convertkit.php
includes/integration/class-convertkit-contactform7-integration.php
includes/integration/class-convertkit-wishlist-integration.php
lib/browser.php
phpcs.xml.dist
views/backend/meta-boxes/meta-box.php
wp-convertkit.php

Reverts ConvertKit/convertkit-wordpress#242

Revert "PHPCS Cleanup"

---

.github/workflows/coding-standards.yml
.github/workflows/test.yml

Updates GitHub Actions for coding standards and tests to run when changes are pushed to the `main` branch since it has been renamed from `master` in GitHub.
Existing tests should run on this PR and when this PR is merged.

Run Coding Standards and Tests on `main` branch

---

resources/backend/css/setup-wizard.css

Removes fixed widths on grid items in the setup wizard, making the UI responsive.
Before:
After:

Make Setup Wizard Responsive

---

views/backend/setup-wizard/convertkit-setup/content-3.php

- Removes outdated video in place of documentation link for how to create a form in ConvertKit
- Adds a notice that Forms can be added manually using the block or shortcode
- Standardises wording on some screens

Update Plugin Setup Wizard Content

---

.github/workflows/tests.yml

Run Tests using WordPress 6.0.2

Run Tests using WordPress 6.0.2

---

.github/workflows/tests.yml

Run tests against WordPress 6.0.3, released October 17th.

Run tests against WordPress 6.0.3

---

.github/workflows/coding-standards.yml
.github/workflows/tests.yml

Run Tests and Coding Standards against WordPress 6.1, released November 1st.

Run Tests and Coding Standards against WordPress 6.1

---

.scripts/read-actions-filters.php
ACTIONS-FILTERS.md
includes/class-convertkit-post-type-product.php
includes/class-convertkit-settings.php

Improvements to how `apply_filters` and `do_action` hooks are parsed for our developer documentation (`ACTIONS-FILTERS.md`)

Fix Actions & Filters script

---

composer.json

Implements [this PR](https://github.com/ConvertKit/convertkit-wordpress-libraries/pull/13) to reduce the number of calls made to resource classes' `refresh()` method when an API error occurs - most likely by specifying an invalid API key in the Plugin's settings.
Before:
After:
First request:
Second and subsequent requests:

Reduce calls to `refresh()` on API error

---

.github/workflows/coding-standards.yml
.github/workflows/tests.yml
readme.txt
tests/_support/Helper/Acceptance/Plugin.php
tests/wpunit/ResourceTagsTest.php

Run tests against ‘latest’ (WordPress 6.2)

Run tests against ‘latest’ (WordPress 6.2)

---

admin/class-multi-value-field-table.php
tests/_support/Helper/Acceptance/Plugin.php
tests/wpunit/ResourcePostsTest.php

Merge #479 into main

---

resources/frontend/css/broadcasts.css

Adds responsive CSS for the broadcasts block, for both list and grid views.

Broadcasts: Add responsive CSS

---

readme.txt

As discussed with @brendancarney, with Member Content out of beta, this PR improves the readme file by adding the `membership` tag and keyword 6 times in the content, to better rank in the Plugin Directory when people search for e.g. membership sites.

Readme: Improve section on Membership Sites

---

.github/workflows/tests.yml

Use GitHub `write-file-action` v1.2

Use GitHub `write-file-action` v1.2

---

.github/workflows/coding-standards.yml
.github/workflows/deploy.yml
.github/workflows/tests.yml

Use GitHub Checkout Action v4, released today.

Use GitHub Checkout Action v4

---

includes/class-convertkit-output-restrict-content.php
resources/frontend/css/restrict-content.css
views/frontend/restrict-content/product-code.php

Improves the input field to enter the 6 digit verification code when accessing member only content, to better follow the [Figma designs](https://www.figma.com/file/vmJIjAxG14L767ZNhEgZaV/Phase-2-%26-3-vision).
Before:
After:
Video:
https://www.loom.com/share/18680071a495458aad3d9475424453b9?sid=88a6971b-4025-49ef-9c17-441389206811
Notes:
- Matching the Open Sans font isn't possible, given this font may not be loaded by all WordPress Themes. Loading this for every site using Restrict Content functionality adds an overhead that seems unnecessary.  This implementation uses the monospace font, to ensure the number size and spacing aligns with the background image across any WordPress Theme.
- This access code step and text will later be served in a modal through further PR's, to more closely …

Restrict Content: Access Code UI

---

includes/class-convertkit-output-restrict-content.php
tests/_support/Helper/Acceptance/WPGutenberg.php
tests/acceptance/restrict-content/RestrictContentProductPageCest.php
tests/acceptance/restrict-content/RestrictContentProductPostCest.php

Add correct version numbers to work done for #576

Fix Version Numbers

---

resources/frontend/css/restrict-content.css
views/frontend/restrict-content/product-modal.php

Improves the mobile UI for Member Content authentication.
Before:
After:
Existing tests pass. Checked output manually on desktop and mobile to ensure no regressions.

Member Content: Improve Mobile UI

---

readme.txt

Updates the readme file to reflect the number of subscribers supported on the free newsletter plan.

Update Free Account Description in `readme.txt`

---

composer.json

Updates the Plugin to use the [2.0.1 release](https://github.com/ConvertKit/convertkit-wordpress-libraries/releases/tag/2.0.1) of the WordPress Libraries

Use WordPress Libraries `2.0.1`

---

.github/workflows/coding-standards.yml
.github/workflows/tests.yml
tests/_support/Helper/Acceptance/WPGutenberg.php
tests/acceptance/broadcasts/import-export/BroadcastsExportPostCest.php
tests/acceptance/integrations/wlm/WishListMemberCest.php

Run tests against WordPress 6.6 RC3
.

Run tests against WordPress 6.6 RC3

---

tests/acceptance/integrations/other/ContactForm7FormCest.php

Refactors Contact Form 7 Tests

Refactor Contact Form 7 Tests

---

includes/class-convertkit-setup.php

Replaces unnecessary negatives based on [this comment](https://github.com/ConvertKit/convertkit-wordpress/pull/693#discussion_r1704110596).

Fix Negatives

---

tests/_support/Helper/Acceptance/DiviBuilder.php
tests/acceptance.suite.yml
tests/acceptance/integrations/other/DiviBroadcastsCest.php
tests/acceptance/integrations/other/DiviFormCest.php
tests/acceptance/integrations/other/DiviFormTriggerCest.php
tests/acceptance/integrations/other/DiviProductCest.php

Refactors tests to remove duplicated code.

Divi: Refactor Tests

---

DEPLOYMENT.md
DEVELOPMENT.md
README.md
SETUP.md
TESTING.md
resources/backend/css/settings.css

- Renames ConvertKit to Kit in .md files
- Tweaks to the UI to better match the new app.kit.com UI, including hover states on buttons, text colors, beta labels and border radius on panels
Before:
After:

Branding Fixes

---

includes/class-convertkit-output-restrict-content.php

Adds support for magic links in emails, which previously failed due to [CSRF/nonce validation requirements](https://developer.wordpress.org/apis/security/nonces/). Since magic links don’t include a nonce, the Plugin would reject them.
This update modifies the logic to validate the nonce when present, whilst allowing magic links to function without it. Additionally, it updates the WordPress action hook from `init` to `wp`, to correctly retrieve the current Post ID.

Restrict Content: Support magic links in email

---

.github/workflows/coding-standards.yml
.github/workflows/tests.yml

Runs the changes made to the Plugin and Tests in #803 against WordPress 6.7, to ensure no breaking changes are introduced.

Test Plugin + Test Changes in #803 against WordPress 6.7

---

readme.txt

Updates the readme file to increase the keyword density and description for the Plugin's membership features, based on the current rankings in the WordPress.org Plugin Directory:
email marketing: Increased keyword phrase from 11 to 13 mentions.
membership: increased keyword phrase from 20 to 25 mentions; moved higher up the readme file and added to the Plugin's title.

Readme: Update Features
