- wp-convertkit.php
The plugin was requesting the api `/forms` endpoint for every page regardless of whether it needed to display a form or not.
> Don't call api forms endpoint if there's no form to be shown

- includes/class-convertkit-custom-content.php
Closes #152 
`ConvertKit_Custom_Content::maybe_tag_subscriber()` is hooked to the `the_post`
action. This is great, because it lets us apply a tag if the visitor has a
`ck_subscriber_id` cookie and the content being viewed should apply a tag.
However, the `ConvertKit_Custom_Content::maybe_tag_subscriber()` method fires twice
per page load, because it's also called by
`ConvertKit_Custom_Content::maybe_tag_subscriber_ajax()`.
In cases where we're not on an individual page or post (e.g. the blog archive,
category archive, etc.), this is a problem, because
`ConvertKit_Custom_Content::maybe_tag_subscriber()` gets called with a null
`$post` argument.
Instead, we should only call `ConvertKit_Custom_Content::maybe_tag_subscriber()`
from `ConvertKit_Custom_Content::maybe_tag_subscriber()` if we're …
> Only call ConvertKit_Custom_Content::maybe_tag_subscriber() on actual pages/posts

- resources/frontend/wp-convertkit.js
Closes #156 
Previously, `ck_subscriber_id` was remvoed from the URL immediately on fetching
the query var. This worked fine in most cases, but if the AJAX call to the
plugin failed for any reason, then the cookie with `ck_subscriber_id` would never
be set, and the subscriber ID would be lost (until the subscriber clicked on
another email link with their subscriber ID included).
Now, we only remove the URL parameter if the AJAX call is successful and we
have set the cookie.
> Don't remove ck_subscriber_id from URL until we set a cookie

- resources/frontend/wp-convertkit.js
Closes #148 
Dynamic content was only partially working within the plugin prior to this change. If a subscriber clicked on a link with `?ck_subscriber_id={id}` in the URL (which CK generates in emails if a setting is checked on the account), then dynamic content worked. However, if a CK form was submitted on a site using the plugin, then a cookie was not added with the subscriber ID, so the plugin could not look up the subscriber to fetch tags and show dynamic content.
This change corrects the form elements being targeted to fetch the new subscriber's ID, so a cookie can be added after form submission.
- On a page on the test site, add a form. Make sure the form will apply a tag to the subscriber. You can use the default form already on the account; it will add the tag `test-tag`.
- On …
> Make the custom content feature work properly

- admin/section/class-convertkit-settings-wishlist.php
Closes #159 
This enforces that we actually use an array for saving WishList Member integration settings. It also moves to the WP builtin `sanitize_text_field()` over `stripslashes()`
> Force WishList Member integration settings to be saved as an array

- includes/class-convertkit.php
Closes #116 
Closes #120 
This PR handles the scenario where the WordPress meta `landing_page` is not set on a post. This would happen if a page was created in an old version of the plugin and has not been saved since.
When the page is loaded a "PHP Notice:  Undefined index" is added to the debug.log if WP_Debug is turned on.
> Fix for when landing page id is not set.

- admin/class-convertkit-settings.php
- admin/section/class-convertkit-settings-base.php
- admin/section/class-convertkit-settings-tools.php
- lib/browser.php
- resources/backend/wp-convertkit.css
- wp-convertkit.php
Adds a "Tools" tab to the ConvertKit settings page. The new tab includes a log viewer to show the CK log. This will help in troubleshooting issues with the plugin. Customer support can request the customer copy+paste this log into support requests or get admin credentials this log file instead.
This will remove the need to ask for SFTP credentials or going through the WP plugin editor (not active on all sites) to view the log file.
There is also a "clear the log" button to remove old or out of date entries from the log file.
> Adding tools tab.

- admin/section/class-convertkit-settings-general.php
- includes/class-convertkit.php
- resources/frontend/wp-convertkit.js
Closes #127 
Before this PR, our javascript makes an ajax request on _every page load_ 😱 
This PR adds a few things:
- An option to turn off loading of our javascript entirely. This is the Nuclear Option™ and will prevent tagging and custom content (using our shortcode, and in the future a Gutenberg block) from functioning.
- Only sends an ajax request to tag subscribers on page load _if_ we are on a page with tags AND we have a subscriber id (either via cookie or URL query param).
- Use this version of the plugin: https://github.com/ConvertKit/ConvertKit-WordPress/archive/issue/127.zip
- Set up a page or post with a tag assigned to it
- Set up a page or post without a tag assigned to it
- Visit both pages/posts without a `ck_subscriber_id` (e.g. in an incognito window) and verify that no …
> Improve performance of our javascript for fun and profit

- resources/frontend/wp-convertkit.js
Closes #168 
Previously, if a URL with a query string is visited, e.g. example.com?foo=bar, our plugin javascript would strip out the ?foo=bar, even though it should really only strip out the query string if it's ?ck_subscriber_id={ID}.
Now, we confirm that the URL we're operating on contains `?ck_subscriber_id` before changing it.
A further enhancement _could_ be to selectively strip out `ck_subscriber_id={id}` but leave any other query parameters alone. However, this probably isn't necessary as the only time `ck_subscriber_id` should be present is when it's added in ConvertKit-sent emails, which in most cases wouldn't contain other query parameters.
- Install this version of the plugin: https://github.com/ConvertKit/ConvertKit-WordPress/archive/issue/168.zip
- Visit a page with a query …
> Only strip out ck_subscriber_id from URL query parameters

- admin/class-convertkit-settings.php
Closes #115
The Yoast SEO plugin javascript targets .term-description-wrap here: https://github.com/Yoast/wordpress-seo/blob/b59bd349fbf7e3b0da834e87d0042e022e89f8f7/js/src/wp-seo-term-scraper.js#L72
The `<tr>` containing our form select menu on Category edit pages previously had that class name, causing breakage.
This change removes that class name.
> Remove class name that conflicted with Yoast SEO javascript

- includes/class-convertkit.php
- readme.txt
Closes #182 
Before this, any category that had been edited (even with no changes) and saved would result in any posts in that category never showing the global default form, even if the post and category were both set to show the global default form.
This is because categories (which have been edited and saved) which have the default form set have a `$form_id` of `'default'` set, but our code was only fetching the global default form if the category's `$form_id` was `0`.
This changes the code to check if the category's `$form_id` is either `0` _or_ `'default'` and if so fetch the global form.
> Fix issue where global default form would never show for some categories

- admin/class-convertkit-settings.php
- admin/section/class-convertkit-settings-general.php
- includes/class-convertkit-api.php
Closes #184 
If a site using the utf8 character set, instead of the newer utf8mb4 character set, AND the connected ConvertKit account has forms/tags/landing pages with emoji characters, then saving that in the site's database will fail.
More info: https://make.wordpress.org/core/2015/04/02/the-utf8mb4-upgrade/
This PR adds checks and messaging to guard against this. We can't prevent the problem (the plugin will still not work if emojis are present and the site uses utf8), but we can (usually) detect it and warn the user.
> Add checks for outdated character set use

- package.json
- plugin.php
- readme.txt
- wp-convertkit.php
Requires plugin.php, so people who have already upgraded and reactivated
don't get deactivated again
> Add back wp-convertkit.php to try and prevent plugin deactivations

- admin/section/class-convertkit-settings-tools.php
- includes/class-convertkit-api.php
- includes/functions.php
- package-lock.json
- The default user-agent send by functions in WordPress' HTTP API just includes the WordPress version and the site's main URL
- These changes flesh out that user-agent so that it now also includes the ConvertKit WordPress plugin's version, and the site's PHP version as well
> Send PHP Version and Plugin Version with API Rquests

- admin/section/class-convertkit-settings-base.php
- admin/section/class-convertkit-settings-general.php
Some users have reported undefined index notices like the following when navigating around their wp-admins:
```
PHP Notice:  Undefined index: api_key in [...]/plugins/convertkit-wordpress/admin/section/class-convertkit-settings-base.php on line 147
PHP Notice:  Undefined index: api_secret in [...]/plugins/convertkit-wordpress/admin/section/class-convertkit-settings-base.php on line 147
```
I wasn't recreating these all of the time, but finally started getting them in my local site. I've made some small tweaks to the code that fix this.
> Fix Undefined-Index Notices for API Key and Secret in Admin

- admin/section/class-convertkit-settings-general.php
- admin/section/class-convertkit-settings-tools.php
- composer.lock
- includes/class-convertkit-api.php
- package.json
- readme.txt
- wp-convertkit.php
This PR rewrites the full writing of the API response to the `logs.txt` file and instead just returns a success log.
This also prevents more than 1,000 lines from being loaded into the debug console.
> Limit logs and prevent full API response logging

- includes/blocks/class-convertkit-block-form.php
- readme.txt
- tests/acceptance/PageShortcodeFormCest.php
- wp-convertkit.php
Fixes a form rendering issue where a newly created ConvertKit Form is added to a WordPress Page using a shortcode, and the Form's ID does not yet exist in the Plugin's cached Forms data.
In this case, a single API call to the `forms` endpoint of the ConvertKit API is made to refresh the list of Forms, caching the result and ensuring that the new Form correctly renders.
For context, the list of available Forms are cached in the Plugin by design when navigating to Settings > ConvertKit, to ensure that the Plugin does not make repeated calls to the `forms` endpoint of the ConvertKit API when using Forms elsewhere in the Plugin (e.g. when specifying a Form in a Page's meta box, adding as a shortcode etc, which would otherwise result in slow page loading times for site visitors and users).
As …
> Fix: Render Form Shortcode when new ConvertKit Form ID specified

- readme.txt
- tests/acceptance/PageCest.php
- tests/acceptance/PostCest.php
A WordPress Plugin may specify the minimum PHP version that is required for a Plugin to be installed or updated by adding the `Requires PHP` header in the `readme.txt` file.
As of now:
- PHP 7.4 and higher are the only currently supported versions: https://www.php.net/supported-versions.php
- WordPress recommends PHP 7.4 and higher: https://wordpress.org/about/requirements/
Many hosts lag behind providing up-to-date PHP versions (notably WP Engine only introducing support for PHP 8.0 earlier this month), so enforcing a strict PHP 7.4+ policy would most likely restrict who can use this Plugin (WordPress do not provide per-Plugin PHP version statistics).  However, we also cannot continue to appear to support out-of-date PHP versions (such as < 5.4), as this results in support requests for …
> Bump minimum required PHP version

- includes/class-convertkit-api.php
- readme.txt
- tests/acceptance/PageFormCest.php
- tests/acceptance/PageLandingPageCest.php
- tests/acceptance/PageTagCest.php
- tests/acceptance/PostFormCest.php
- tests/acceptance/PostLandingPageCest.php
Legacy Forms would wrongly include `<html>`, `<head>` and `<body>` tags due to using PHP's `DOMDocument` functionality (this being used to convert relative to absolute URIs).
This did not affect output, noting browsers ignore these erroneous duplicated tags:
Output when applying this PR is now correct:
This was missed through testing because Codeception removes these duplicate tags when loading a page's source into a DOM parser prior to performing assertions within tests.
> Legacy Forms: Removed erroneous <html>, <head> and <body> tags

- .github/workflows/test.yml
- admin/section/class-convertkit-settings-base.php
- readme.txt
- wp-convertkit.php
Removes a trailing comma in a sprintf() call, which caused parse errors on Plugin activation when using PHP 7.2.x or earlier.
Updated testing to run against PHP 7.2 as well as existing 7.3, 7.4 and 8.0 to ensure similar errors are caught in the future.
> Fix: Remove trailing comma in sprintf() call

- includes/class-wp-convertkit.php
Correctly sets the path to the Plugin's `languages` folder to the Plugin's folder name, with `/languages` appended to the end, relative to the WordPress Plugin directory (e.g. `convertkit/languages`).
The previous use of `dirname( __FILE__ )` is incorrect, as this function is called from within a subfolder, and would result in the path being incorrectly set to `includes/languages`.
Docs: [load_plugin_textdomain](https://developer.wordpress.org/reference/functions/load_plugin_textdomain/)
> Fix Languages Folder Path

- resources/backend/js/gutenberg.js
Orders the Form block's dropdown options by form name (label), instead of ID (key), to match other Form dropdown selections used across the Plugin.
Before:
After:
> Gutenberg Blocks: Sort <select> field options alphabetically by label

- admin/class-convertkit-admin-settings.php
- admin/class-convertkit-admin-tinymce.php
- admin/class-convertkit-admin-upgrade.php
- admin/class-multi-value-field-table.php
- admin/section/class-convertkit-settings-base.php
- admin/section/class-convertkit-settings-general.php
- includes/blocks/class-convertkit-block-content.php
- includes/blocks/class-convertkit-block-form.php
- includes/blocks/class-convertkit-block.php
- includes/class-convertkit-ajax.php
- includes/class-convertkit-api.php
- includes/class-convertkit-output.php
- includes/class-convertkit-post.php
- includes/class-convertkit-resource-forms.php
- includes/class-convertkit-resource-landing-pages.php
- includes/class-convertkit-resource-tags.php
- includes/class-convertkit-resource.php
- includes/class-convertkit-review-request.php
- includes/class-convertkit-settings.php
- includes/class-convertkit-system-info.php
- includes/class-convertkit-term.php
- includes/class-convertkit-user.php
- includes/class-wp-convertkit.php
- includes/functions.php
- includes/integrations/contactform7/class-convertkit-contactform7-admin-settings.php
- includes/integrations/contactform7/class-convertkit-contactform7-settings.php
- includes/integrations/wishlist/class-convertkit-wishlist-admin-settings.php
- includes/integrations/wishlist/class-convertkit-wishlist-settings.php
- includes/integrations/wishlist/class-convertkit-wishlist.php
- includes/widgets/class-ck-widget-form.php
Code changes to pass PHPStan's static analysis, broadly covering:
- Incorrect parameter type passed to `wp_enqueue_style()`
- Incorrect DocBlock parameter types (e.g. `string` when it is an `int`)
- More accurate DocBlock return types (e.g. `WP_Error|array` instead of `mixed`)
- Removal of unused functions, such as `register_custom_post_type_fields()`
Existing tests confirm working functionality of Plugin.
> Code changes to meet PHPStan static analysis tests

- admin/section/class-convertkit-settings-general.php
- resources/backend/css/select2.css
- views/backend/post/meta-box.php
- views/backend/term/fields.php
Prevents Plugin's additional Select2 styling from being applied to non-Plugin Select2 instances, [as reported here](https://github.com/ConvertKit/convertkit-wordpress/issues/287), by:
- wrapping Select2 instances inside a container element with a Plugin-specific class name,
- applying additional Select2 styling to the Plugin-specific class name.
Before, noting Plugin Select2 styles wrongly applied to a third party Gutenberg Block that also uses Select2, resulting in a scroll bar:
After, noting Plugin Select2 styles no longer applied to third party Gutenberg Block:
UI and visual tests to confirm styling correctly applies.
Existing acceptance tests confirm Select2 instances still work as expected.
> Prevent Select2 styling from applying to non-Plugin elements

- includes/class-convertkit-term.php
- readme.txt
- tests/acceptance/PostFormCest.php
- views/backend/term/fields.php
The Default Form for Posts would fail to display when all of the following conditions are met:
1. WordPress Categories are created prior to 1.9.6.0
2. Those WordPress Categories are assigned to WordPress Posts, regardless of the Plugin version
3. The site(s) in question use PHP 8.0 or greater.
This is because Plugin versions prior to 1.9.6.0 would store the Form setting at Category level as either `default` or a Form ID; 1.9.6.0 and later store the Form setting at Category level as either `0` or a Form ID.
(I made this change at the time working on 1.9.6.0 because the `None` label had a value of `default`, compared with the `None` label having a value of `0` for this setting on Pages or Posts, which seemed incorrect/inconsistent.  Turns out, `None` at Category level really means "Don't …
> Fix Form Setting on Category

- .github/workflows/test.yml
- includes/class-wp-convertkit.php
- includes/integrations/elementor/class-convertkit-elementor-widget-form.php
- includes/integrations/elementor/class-convertkit-elementor-widget.php
- includes/integrations/elementor/class-convertkit-elementor.php
- resources/backend/css/elementor.css
- tests/_support/Helper/Acceptance.php
- tests/acceptance/PageElementorFormCest.php
- tests/acceptance/PostElementorFormCest.php
- wp-convertkit.php
Registers a ConvertKit Form Widget in [Elementor](https://en-gb.wordpress.org/plugins/elementor/), a popular page builder with ~ 5 million active installations of the free version.
Whilst Elementor provide a ConvertKit integration with their own Form widget:
1. It's only available to Elementor Pro users (those with a paid license for Elementor),
2. It doesn't allow the user to choose a ConvertKit Form to embed into their Page/Post.
This allows editors to insert ConvertKit Forms into Pages, Posts and Custom Post Types when editing with Elementor, similar to how we support [Gutenberg](https://github.com/ConvertKit/convertkit-wordpress/pull/273).
Video:
https://www.loom.com/share/7d2a8cbb132d406085fc4a234a944074
- PageElementorFormCest: Tests for adding, saving and viewing Pages with the …
> ConvertKit Form Widget for Elementor Page Builder

- tests/acceptance/PageBlockFormCest.php
- tests/acceptance/PageElementorFormCest.php
- tests/acceptance/PageFormCest.php
- tests/acceptance/PostElementorFormCest.php
- tests/acceptance/PostFormCest.php
- tests/acceptance/WooCommerceProductFormCest.php
The same Page, Post or Product title was used across multiple tests, primarily when testing whether a ConvertKit form is displayed based on the Page's settings or Gutenberg Block.
For example, the following three tests would produce a Page, Post and Product, each with the same title '':
- Page: https://github.com/ConvertKit/convertkit-wordpress/blob/master/tests/acceptance/PageFormCest.php#L58
- Post: https://github.com/ConvertKit/convertkit-wordpress/blob/master/tests/acceptance/PostFormCest.php#L58
- Product: https://github.com/ConvertKit/convertkit-wordpress/blob/master/tests/acceptance/WooCommerceProductFormCest.php#L52
WordPress would create the following permalinks:
- Page: `/convertkit-form-default-none`
- Post: `/convertkit-form-default-none-2`
- Product: …
> Tests: Create unique Page, Post and Product Titles

- includes/blocks/class-convertkit-block-broadcasts.php
- includes/class-convertkit-resource-forms.php
- includes/class-convertkit-resource-landing-pages.php
- includes/class-convertkit-resource-posts.php
- includes/class-convertkit-resource-tags.php
- includes/class-convertkit-resource.php
- tests/wpunit/ResourceFormsTest.php
- tests/wpunit/ResourceLandingPagesTest.php
- tests/wpunit/ResourcePostsTest.php
- tests/wpunit/ResourceTagsTest.php
When ConvertKit Forms, Tags, Landing Pages or Posts ('resources') are fetched from the API, they're presently cached indefinitely (with no expiration) in WordPress' options table for performance, and to prevent multiple calls to the API.
These cached resources are refreshed when navigating to `WordPress Admin > Settings > ConvertKit`.
For Forms, Landing Pages and Tags, it's unlikely that these resources are changed in ConvertKit often - so performing the above step to force a refresh isn't an issue.
However, for the list of broadcasts, it's likely that:
1. User adds the [broadcast block / shortcode](https://github.com/ConvertKit/convertkit-wordpress/pull/301) to a WordPress Page, configured to show e.g. the latest 3 broadcasts
2. User creates a new broadcast in ConvertKit the next day
3. …
> Add expiration to cached resources

- resources/backend/js/gutenberg.js
- tests/_support/Helper/Acceptance.php
- tests/acceptance/PageBlockBroadcastsCest.php
Whilst the `Number of posts` option on the Broadcasts block is a number field, it's possible to define a blank value by pressing the backspace key.
This would result in the block crashing, and failing to render, because the `limit` parameter is expected to be a numerical value, not a blank string.
This PR resolves by checking if any numerical parameter is a blank string, and if so setting its value to the field's minimum value. 
- `PageBlockBroadcastsCest:testBroadcastsBlockWithBlankLimitParameter`: Emulates the above behaviour, confirming that no block error appears.
> Broadcast Block: Setting `Number of posts` to blank would crash block 

- includes/class-convertkit-setup.php
- includes/class-wp-convertkit.php
- includes/functions.php
- wp-convertkit.php
Adds activation and deactivation functions to a single setup class, which are triggered when the Plugin is activated or deactivated in WordPress.
Also moves the existing update function into new setup class.
A future PR will then use these activation, update and deactivation hooks to schedule/unschedule a WordPress Cron event for automatically refreshing the broadcasts list from the API, as discussed in [this PR](https://github.com/ConvertKit/convertkit-wordpress/pull/302#pullrequestreview-951929261).
Existing test coverage is sufficient; future PR's that use these activation / deactivation functions should include unit tests to confirm expected routines ran successfully.
> Plugin Activation and Deactivation routines

- tests/_support/Helper/Acceptance/WPGutenberg.php
- tests/_support/Helper/Acceptance/WPMetabox.php
- tests/acceptance.suite.yml
- tests/acceptance/PageBlockBroadcastsCest.php
- tests/acceptance/PageBlockFormCest.php
- tests/acceptance/PageElementorFormCest.php
- tests/acceptance/PageFormCest.php
- tests/acceptance/PageLandingPageCest.php
- tests/acceptance/PageTagCest.php
- tests/acceptance/PostElementorFormCest.php
- tests/acceptance/PostFormCest.php
Refactors Page and Post tests for Forms, Landing Pages and Tags that interact with the Gutenberg editor to use the new helper functions created in [this PR](https://github.com/ConvertKit/convertkit-wordpress/pull/307) for repetitive tasks, such as creating Pages/Posts.
- Existing tests pass to confirm no breaking changes to testing framework.
> Tests: Refactor Page/Post Tests

- admin/section/class-convertkit-settings-tools.php
- tests/acceptance/PluginSettingsToolsCest.php
Standardizes the filenames when downloading the Plugin's Log and System info to `convertkit-log.txt` and `convertkit-system-info.txt`.
Previously, the Log would include the server's full path in the filename, which was messy.
PR also adds tests to confirm that downloading the log and system info work.
- `PluginSettingsToolsCest:testDownloadLog`: Tests that downloading the plugin's log file works
- `PluginSettingsToolsCest:testDownloadSystemInfo`: Tests that downloading the plugin's system info works
> Standardize Log and System info filenames

- includes/class-convertkit-gutenberg.php
- includes/widgets/class-ck-widget-form.php
- readme.txt
- resources/backend/js/gutenberg.js
- tests/_support/Helper/Acceptance/WPWidget.php
- tests/acceptance.suite.yml
- tests/acceptance/WidgetBroadcastsCest.php
- tests/acceptance/WidgetFormCest.php
- tests/acceptance/WidgetsFormCest.php
Currently, we have a[ Form Widget](https://github.com/ConvertKit/convertkit-wordpress/blob/master/includes/widgets/class-ck-widget-form.php) which is registered in WordPress' widget system using the `WP_Widget` class, allowing site owners to place ConvertKit Forms in their site's sidebars or footers, depending on their theme.
[Since WordPress 5.8](https://wordpress.org/news/2021/08/widgets-in-wordpress-5-8-and-beyond/), the widget interface has been replaced with the Gutenberg editor, allowing site owners to place blocks in their site's sidebars and footers, again depending on their theme.
This PR:
- Enables the ConvertKit Form Block and ConvertKit Broadcasts Block to be added and configured to WordPress 5.8+ widget areas, and not just Pages/Posts.
- Adds tests for the Form and Broadcast …
> Support Blocks as Widgets

- includes/class-convertkit-api.php
- includes/class-convertkit-resource.php
- tests/wpunit/APITest.php
- tests/wpunit/ResourceFormsTest.php
- tests/wpunit/ResourceLandingPagesTest.php
- tests/wpunit/ResourcePostsTest.php
- tests/wpunit/ResourceTagsTest.php
Updates the API class to fetch all broadcasts from the API, now that [pagination is supported](https://github.com/ConvertKit/convertkit/pull/20651) in the posts API.
Caches all broadcasts, and provides a `get_paginated_subset()` function for cached resources, such as broadcasts, so that pagination is handled by the plugin, without needing to make repetitive requests to the API.
A separate PR will then utilize this pagination functionality on the Broadcasts block and shortcode.
- `APITest`: Added tests for new API functions.
- `ResourcePostsTest`: Added tests for pagination.
> Add pagination support to Broadcasts API / Resource classes

- .github/workflows/test.yml
- tests/acceptance/WishListMemberCest.php
Reinstates the WishList Member integration test, now that WLM have supplied a working copy of their Plugin that is compatible with WordPress 6.0
- `WishListMemberCest` passes tests.
> Reinstate WishList Member Test

- tests/acceptance/PageFormCest.php
- tests/acceptance/PostFormCest.php
Uses Form IDs specified in the .env file when performing assertions, instead of reading from the settings, due to some false failures in other tests and a minor performance improvement.
- `PageFormCest` and `PostFormCest` updated to use .env file values when asserting Form IDs.
> Testing: Use Form IDs in .env file

- includes/integrations/elementor/class-convertkit-elementor-widget-broadcasts.php
- readme.txt
- resources/backend/css/elementor.css
- tests/acceptance/integrations/ElementorBroadcastsCest.php
Registers the Broadcasts block as an [Elementor](https://en-gb.wordpress.org/plugins/elementor/) widget, as we did for the [Forms block](https://github.com/ConvertKit/convertkit-wordpress/pull/294).
(This was [previously submitted as a PR](https://github.com/ConvertKit/convertkit-wordpress/pull/323), but merged prior to review by accident, [and then removed](https://github.com/ConvertKit/convertkit-wordpress/commit/dbfb38191dd5dd5486a1a750e9b6589c9a258b5c) from the main branch to revert this).
- `ElementorBroadcastsCest`: Tests for adding the Broadcasts widget to a WordPress Page edited with the Elementor Page Builder.
> Add Broadcasts as Elementor Widget

- admin/class-convertkit-admin-settings.php
- admin/class-convertkit-admin-tinymce.php
- includes/blocks/class-convertkit-block-broadcasts.php
- includes/blocks/class-convertkit-block-form.php
- includes/class-convertkit-gutenberg.php
- includes/functions.php
Removes a double forwardslash from the URL when some CSS and JS assets are enqueued/loaded by the Plugin, as reported [here](https://github.com/ConvertKit/tier3-issues/issues/2290).
Whilst a double forwardslash in the URL doesn't break anything, it's best to remove them.
> Remove double forwardslash when enqueuing scripts and styles

- includes/blocks/class-convertkit-block-content.php
- lib/class-convertkit-api.php
- readme.txt
- tests/wpunit/APITest.php
- tests/wpunit/ResourceFormsNoDataTest.php
- tests/wpunit/ResourceFormsTest.php
- tests/wpunit/ResourceLandingPagesNoDataTest.php
- tests/wpunit/ResourceLandingPagesTest.php
- tests/wpunit/ResourcePostsNoDataTest.php
- tests/wpunit/ResourcePostsTest.php
- tests/wpunit/ResourceTagsNoDataTest.php
- tests/wpunit/ResourceTagsTest.php
Returns an empty array instead of a `WP_Error` object when no resources (forms, landing pages, tags etc) exist in the ConvertKit account.
- `APITest`: Added tests to confirm correct return type when no resources exist
- `ResourceFormsNoDataTest`: Added tests to confirm resource class returns expected values when no resources exist
- `ResourceLandingPagesNoDataTest`: Added tests to confirm resource class returns expected values when no resources exist
- `ResourcePostsNoDataTest`: Added tests to confirm resource class returns expected values when no resources exist
- `ResourceTagsNoDataTest`: Added tests to confirm resource class returns expected values when no resources exist
> API: Return array instead of `WP_Error` when no resources exist

- admin/class-convertkit-admin-bulk-quick-edit.php
- admin/class-convertkit-admin-post.php
- admin/class-convertkit-admin-quick-edit.php
- composer.json
- includes/class-wp-convertkit.php
- resources/backend/css/quick-edit.css
- resources/backend/js/quick-edit.js
- tests/_support/Helper/Acceptance/WPQuickEdit.php
- tests/acceptance.suite.yml
- tests/acceptance/forms/PageFormCest.php
- tests/acceptance/forms/PostFormCest.php
- tests/acceptance/integrations/WooCommerceProductFormCest.php
- tests/acceptance/tags/PageTagCest.php
- views/backend/post/quick-edit.php
- wp-convertkit.php
Adds options to WordPress' [Quick Edit](https://wordpress.com/support/pages/edit-pages-screen/#quick-edit) functionality to change the ConvertKit Form or Tag associated with a Page, Post or WooCommerce Product
Video:
https://www.loom.com/share/edc790cc466a419b97716977ce9c4c98
- `PageFormCest:testQuickEditUsingDefaultForm`: Tests that using the Quick Edit functionality on an existing WordPress Page works when choosing the `Default` option.
- `PageFormCest:testQuickEditUsingDefinedForm`: Tests that using the Quick Edit functionality on an existing WordPress Page works when choosing a specific form.
- `PostFormCest:testQuickEditUsingDefaultForm`: Tests that using the Quick Edit functionality on an existing WordPress Post works when choosing the `Default` option.
- …
> Quick Edit

- lib/class-convertkit-resource.php
Prevents querying the API on every WordPress Administration screen request if a ConvertKit account does not have a particular resource (such as forms or tags).  The frontend site is unaffected, as no API queries are made.
If a ConvertKit account has no resources (forms or tags), the plugin's cache for these resources will be empty.
As a result, the plugin would query the API on every WordPress administration screen request, resulting in slow loading times (in this example, approximately ~ 3 seconds is added to the load time for an administration screen):
Whilst the account _should_ have at least one form (the plugin isn't really useful otherwise), it's wrong for the plugin to presume that at least one tag will be defined in the ConvertKit account. Emulating an account that has one form …
> Plugin Performance when no Resources exist

- admin/class-convertkit-admin-category.php
- admin/class-convertkit-admin-refresh-resources.php
- includes/class-wp-convertkit.php
- resources/backend/js/refresh-resources.js
- tests/_support/Helper/Acceptance/Select2.php
- tests/_support/Helper/Acceptance/WPBulkEdit.php
- tests/_support/Helper/Acceptance/WPQuickEdit.php
- tests/acceptance/forms/PageNoFormCest.php
- tests/acceptance/general/RefreshResourcesButtonCest.php
- tests/acceptance/general/RefreshResourcesCest.php
- views/backend/post/bulk-edit.php
- views/backend/post/meta-box.php
- views/backend/post/quick-edit.php
- views/backend/term/fields.php
- wp-convertkit.php
Adds buttons next to Form, Tag and Landing Page fields to refresh the cached forms/landing pages/tags from the API, across
- adding/editing Pages/Posts
- quick/bulk editing Pages/Post
- editing Categories
Video:
https://www.loom.com/share/5babb995c54349b69f74607e32c18369
This solves two issues:
1. Currently, only WordPress Administrators have access to forcing a refresh of resources by navigating to the `Settings > ConvertKit` screen.  WordPress Editors and Authors do not have access to this screen, which is standard WordPress behaviour - however, Editors and Authors in WordPress can create/edit Pages, Posts and Categories, and configure the per-Page/Post/Category settings for ConvertKit (such as defining a form or landing page to display).
2.  There can be confusion when a ConvertKit …
> Add Refresh Buttons for Forms, Landing Pages and Tags

- resources/backend/js/bulk-edit.js
- tests/acceptance/forms/PageFormCest.php
- tests/acceptance/forms/PostFormCest.php
- tests/acceptance/integrations/WooCommerceProductFormCest.php
Fixes an issue in 1.9.8.0 where Bulk Edit fields would incorrectly display in the footer of the Pages/Posts table view when no Pages/Posts exist, or a search would return no results:
- `PageFormCest:testBulkEditFieldsHiddenWhenNoPagesFound`: Test that the Bulk Edit fields do not display when a search on a WP_List_Table returns no results.
- `PostFormCest:testBulkEditFieldsHiddenWhenNoPostsFound`: Test that the Bulk Edit fields do not display when a search on a WP_List_Table returns no results.
- `WooCommerceProductFormCest:testBulkEditFieldsHiddenWhenNoProductsFound`: Test that the Bulk Edit fields do not display when a search on a WP_List_Table returns no results.
> Don't display Bulk Edit fields when no Pages/Posts

- views/backend/post/bulk-edit.php
- views/backend/post/quick-edit.php
Fixes incorrect `for` attributes on Bulk and Quick Edit `<label>` elements, to correctly match the form field ID.
> Fix `for` label attribute on Bulk and Quick Edit

- lib/class-convertkit-api.php
- tests/wpunit/APITest.php
Handles 500 and 502 HTTP errors by returning a WP_Error object, which is then output as a notice in the Plugin's settings screen:
Previously, a PHP warning would be displayed if a 500 or 502 error was hit, as the response data would be `null`:
429 errors are already handled; 401, 422 and other errors are not handled by this PR, as they return a verbose error message in the body, which the API class checks for and handles.
- `APITest:test429RateLimitHit`: Tests that a 429 rate limit reached HTTP response code from the API class is returned as a WP_Error with the expected error message.
- `APITest:test500RateLimitHit`: Tests that a 500 internal server error HTTP response code from the API class is returned as a WP_Error with the expected error message.
- `APITest:test502RateLimitHit`: Tests …
> API: Handle 500 and 502 HTTP errors

- .github/workflows/test.yml
- tests/acceptance/integrations/ContactForm7FormCest.php
Reinstates deactivating the Contact Form 7 Plugin after running integration tests.
Deactivation was [previously disabled](https://github.com/ConvertKit/convertkit-wordpress/pull/338#discussion_r922173296) as it resulted in errors.
> Tests: Deactivate Contact Form 7 Plugin after test completion

- .github/workflows/coding-standards.yml
- .github/workflows/test.yml
Runs Coding Standards and PHPUnit tests against PHP 8.1.
At this time, it's not possible to run our acceptance and unit tests against PHP 8.1, as WordPress isn't yet compatible with PHP 8.1, resulting in PHP warnings being output when WordPress uses standard functions, such as `setcookie()`:
> Run Coding Standards and PHPUnit tests against PHP 8.1

- resources/backend/js/refresh-resources.js
- tests/acceptance/general/RefreshResourcesButtonCest.php
Displays a dismissible WordPress style inline error message when the refresh button's request fails, rather than failing silently, [as suggested here](https://github.com/ConvertKit/convertkit-woocommerce/pull/109#pullrequestreview-1060182288):
As WordPress doesn't have a native toast-style notification API/function we can use, I've implemented it to follow how WordPress shows its notifications:
If you think toast-style notifications would be better here, let me know.
- `RefreshResourcesButtonCest:testRefreshResourcesErrorNotice`: Confirms that an error notification is displayed when clicking the refresh button, where the Plugin is configured with invalid API keys
> Display Notification on Refresh Resource error

- readme.txt
Changes the Plugin's tags in the Plugin directory:
- Added `email newsletter`
- Changed `marketing` to `email marketing`
Changes the title of the Plugin from `ConvertKit` to `ConvertKit - Email Marketing, Email Newsletter and Landing Pages`, to include key search phrases.
Increases the keyword density for tags in the Plugin directory, to improve search visibility:
Before:
- marketing: 4
- newsletter: 4
- email marketing: 4
- email newsletter: 1
After:
- marketing: 7
- newsletter: 8
- email marketing: 7
- email newsletter: 8
Run the contents of the `readme.txt` file through https://wpreadme.com/ to confirm markdown is parsed correctly.
> Readme: Change Tags, Increase Keyword Density

- admin/class-convertkit-admin-tinymce.php
- readme.txt
- resources/backend/js/modal.js
- resources/backend/js/quicktags.js
- resources/backend/js/tinymce.js
- tests/_support/Helper/Acceptance/WPClassicEditor.php
- tests/acceptance/integrations/WooCommerceProductFormCest.php
- views/backend/tinymce/modal.php
When multiple Visual / Classic Editor instances exist on an edit screen (i.e. when adding/editing WooCommerce Products), two problems exist:
1. Text editor: buttons to insert ConvertKit shortcodes would not consistently work, resulting in the modal / modal background remaining stuck on screen:
2. Visual editor: buttons would sometimes insert the shortcode into the non-active editor:
This PR resolves by including an `editor_type`, so the `modal.js` script knows the state of the editor (visual or text), and can therefore consistently work, inserting the shortcode into the correct editor and closing the applicable modal window.
- `WooCommerceProductFormCest:testAddNewProductUsingFormShortcodeInVisualEditor`: Test the [convertkit_form] shortcode is inserted into the correct Content or Excerpt …
> Shortcodes: Add support for multiple Visual/Text editors on edit screen

- resources/backend/js/refresh-resources.js
- tests/acceptance/general/RefreshResourcesButtonCest.php
Extends work done on the [error notification for refresh resources](https://github.com/ConvertKit/convertkit-wordpress/pull/344), to include coverage for displaying an error notification when refreshing resource call returns an error across:
- Adding/editing a Page, Post or Custom Post Type in the Gutenberg editor
- Adding/editing a Page, Post or Custom Post Type in the Classic Editor
- Editing a Category
- `RefreshResourcesButtonCest:testRefreshResourcesErrorNoticeOnPage`: Tests that a dismissible error notification is displayed when adding/editing a Page in Gutenberg, and the refresh resource button returns an error
- `RefreshResourcesButtonCest:testRefreshResourcesErrorNoticeOnPageClassicEditor`: Tests that a dismissible error notification is displayed when adding/editing a Page in the …
> Extend Refresh Resource error notifications for Gutenberg, Classic Editor and Edit Category

- admin/section/class-convertkit-settings-tools.php
Building on [this PR](https://github.com/ConvertKit/convertkit-wordpress/pull/348), checks if the user is running WordPress 5.2 or greater, which is required to make use of WordPress' WP_Debug_Data class for building out the System Info.
If the user is running WordPress 5.0 or 5.1, they'll instead see this message, both in the `Settings > ConvertKit > Tools` screen and if they click the `Download system info` button:
We could re-include the old method for building System Info to support WordPress 5.0 and 5.1, as our Plugin does list itself as supporting WordPress 5.0 or higher.  However, [WordPress' statistics](https://en-gb.wordpress.org/about/stats/) indicate only ~ 2.31% of sites are using 5.0 or 5.1, and I'd prefer not to include older libraries in our code, unless there's a strong …
> Determine if WP_Debug_Data class can be used for System Info

- admin/class-convertkit-admin-setup-wizard.php
- admin/setup-wizard/class-convertkit-admin-setup-wizard-plugin.php
- includes/class-wp-convertkit.php
- includes/functions.php
- includes/setup-wizard/class-convertkit-setup-wizard-plugin.php
- tests/_support/Helper/Acceptance/ThirdPartyPlugin.php
- tests/acceptance/general/PluginSetupWizardCest.php
- views/backend/setup-wizard/convertkit-setup/content-1.php
- views/backend/setup-wizard/convertkit-setup/content-2.php
- views/backend/setup-wizard/convertkit-setup/content-3.php
- views/backend/setup-wizard/convertkit-setup/content-4.php
- wp-convertkit.php
Provides a setup wizard to configure the Plugin for the first time when the Plugin is activated and no settings exist.
The wizard will only display when:
- the WordPress user has permissions to activate plugins,
- the Plugin isn't activated on a multisite installation (there are complications with taking over the WordPress Admin UI on multisite),
- no existing API key and secret exist in the Plugin (i.e. if the Plugin was previously activated and configured on the same site, the wizard won't display) 
Videos:
- Linking a ConvertKit account:
https://www.loom.com/share/97c5939ad49f465cb77ff5953ba27188
- Linking a ConvertKit account that has no forms:
https://www.loom.com/share/684ef276f013411e92af11c1e040baeb
- `PluginSetupWizardCest`: Tests that the setup wizard displays when expected, and …
> Setup Wizard for Plugin

- readme.txt
- resources/backend/css/quicktags.css
- resources/backend/js/quicktags.js
Fixes the size and position of the Quicktags modal, which is displayed when clicking a ConvertKit button in the Text editor.
Before:
After:
> Quicktags Modal Size and Position

- admin/class-convertkit-admin-tinymce.php
- composer.json
- includes/blocks/class-convertkit-block-broadcasts.php
- includes/blocks/class-convertkit-block.php
- readme.txt
- resources/backend/css/tinymce.css
- resources/backend/js/gutenberg.js
- resources/backend/js/quicktags.js
- resources/backend/js/tinymce.js
- resources/frontend/js/broadcasts.js
- tests/acceptance/broadcasts/PageShortcodeBroadcastsCest.php
- views/backend/tinymce/modal-field.php
When using the Broadcasts block in Gutenberg, native options are displayed to define the block's background, text and link colors:
This PR adds support for defining color options when using the Broadcasts shortcode (i.e. for users not using Gutenberg), utilizing WordPress' built in color picker:
- `PageShortcodeBroadcastsCest:testBroadcastsShortcodeInVisualEditorWithHexColorParameters`: Test that color parameters are honored when defined.
> Broadcasts: Shortcode: Support color options

- includes/integrations/elementor/class-convertkit-elementor-widget.php
- readme.txt
- tests/acceptance/integrations/ElementorBroadcastsCest.php
This PR adds support for defining color options when using the Broadcasts widget in Elementor, utilizing Elementor's built in color picker
Before:
After:
- `ElementorBroadcastsCest:testBroadcastsWidgetWithHexColorParameters`: Tests that link, background and text colors are honored when configured in the Elementor Broadcast widget.
> Broadcasts: Elementor: Support color options

- includes/functions.php
Passes the site ID as an integer instead of a string when calling `switch_to_blog()`, as detected in PHPStan for WordPress' [most recent update (1.1.3)](https://github.com/szepeviktor/phpstan-wordpress/releases/tag/v1.1.3), released today:
> Pass Site ID as integer to switch_to_blog()

- includes/class-wp-convertkit.php
Replaces the generic `phpcs:ignore` with a specific `phpcs:disable WordPress.Security.NonceVerification.Recommended`, when inspecting PHP's `$_REQUEST` array for specific keys, to determine if a WordPress Page Builder is used.
This follows https://github.com/ConvertKit/convertkit-wordpress/pull/333
> Add specific reason to ignore Coding Standards in `includes/class-wp-convertkit.php`

- admin/class-convertkit-admin-refresh-resources.php
- admin/section/class-convertkit-settings-general.php
- composer.json
- includes/class-convertkit-resource-products.php
- tests/wpunit/ResourceProductsNoDataTest.php
- tests/wpunit/ResourceProductsTest.php
- wp-convertkit.php
Utilises version [1.2.0 of the ConvertKit WordPress Libraries](https://github.com/ConvertKit/convertkit-wordpress-libraries/pull/2) to support fetching Products via the ConvertKit API and caching them in the Plugin.
Further PR's to follow for implementation of the Product button block and shortcode, which will build on this.
- `ResourceProductsTest`: Tests that the `ConvertKit_Resource_Products` class works with the API
- `ResourceProductsNoDataTest`: Tess that the `ConvertKit_Resource_Products` class works with the API when the ConvertKit account contains no Products.
> API and Caching for Products

- tests/_support/Helper/Acceptance/Plugin.php
- tests/_support/Helper/Acceptance/WPClassicEditor.php
**Broadcasts**
Broadcast tests that use the `testBroadcastsPagination()` helper now read the cached resource to determine the first two Broadcasts that should be displayed when testing previous / next pagination.
Previously, the Broadcast name was hard coded into the test, which doesn’t make sense when Broadcasts might be added to the ConvertKit account in the future.
Additional checks have been added to confirm the correct Broadcast URL and UTM parameters are output.
**WooCommerce**
Updates the `addVisualEditorShortcode()` and `addTextEditorShortcode()` test helpers to correctly navigate to, and open, the applicable UI element, prior to performing steps.  This is due to WooCommerce 7.0 changing the default behaviour of the `Product short description` meta box being closed, not open. 
- …
> Tests: Improve reliability of tests for Broadcasts and WooCommerce

- includes/integrations/elementor/class-convertkit-elementor-widget-product.php
- resources/backend/css/elementor.css
- tests/acceptance/general/PluginSetupWizardCest.php
- tests/acceptance/integrations/ElementorProductCest.php
Registers the Product button block as an Elementor widget:
https://www.loom.com/share/1ebd138e582c428fb61504d70ca8778b
- `ElementorProductCest`: Tests for adding the Product button in Elementor
> Add Product button as an Elementor widget

- composer.json
- includes/blocks/class-convertkit-block-content.php
- includes/class-convertkit-ajax.php
- includes/class-convertkit-output.php
- includes/class-convertkit-subscriber.php
- tests/acceptance/tags/PageShortcodeCustomContentCest.php
- wp-convertkit.php
Abstracts logic to check:
- if a URL request includes a `ck_subscriber_id` parameter (i.e. if clicking a link in a ConvertKit email where the ConvertKit account's `Add subscriber_id parameter in email links` setting is enabled), and/or 
- if a `ck_subscriber_id` cookie exists (having been set by a previous request above).
This subscriber ID is used for displaying [custom content](https://help.convertkit.com/en/articles/2502591-getting-started-the-wordpress-plugin#custom-content) (i.e. blocks of content that are only viewable to a subscriber that has a specific tag); but will later be used in the Restrict Content functionality, to provide an improved way to gate/restrict content by form, tag or product, with email link authentication.
> Abstract `ck_subscriber_id` detection / cookie storage

- composer.json
- includes/blocks/class-convertkit-block-product.php
- includes/class-convertkit-post-type-product.php
- readme.txt
- wp-convertkit.php
Minor changes for the 2.0.0 Plugin release:
- Updated readme file to reflect changes and Products functionality
- Updated readme file and Plugin version to `2.0.0`
- Use WordPress Libraries `1.2.1`, which is now published
- Remove CSS include for non-existent file `gutenberg-block-product.css`
> ConvertKit 2.0.0

- .github/workflows/tests.yml
- tests/acceptance/tags/PageShortcodeCustomContentCest.php
Run tests against [supported PHP versions](https://www.php.net/supported-versions.php) and resolves API rate limits triggering tests to fail, due to so many tests previously running in parallel.
Coding Standards tests continue to run against PHP 7.2 and 7.3, to confirm we are not introducing breaking changes i.e. functions only available in PHP 7.4+.
> Tests: PHP Versions

- includes/integrations/contactform7/class-convertkit-contactform7-admin-settings.php
- includes/integrations/wishlist/class-convertkit-wishlist-admin-settings.php
Renders the closing div elements when accessing `Settings > ConvertKit > Contact Form 7` or `Settings > ConvertKit > WishList Member` and no ConvertKit Forms exist, to ensure the Plugin help description and WordPress' footer render in the correct places. 
Before:
After:
> Integrations: Render closing HTML elements when no Forms

- .github/workflows/coding-standards.yml
- .github/workflows/deploy.yml
- .github/workflows/tests.yml
Updates GitHub actions dependencies to use [Node 16](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
) instead of Node 12:
- `actions/checkout`: v2 to v3
- `DamianReeves/write-file-action`: v1.0 to v1.1
- `actions/upload-artifact`: v2 to v3
> GitHub Actions: Bump `actions` dependencies to versions that use Node 16

- .github/workflows/coding-standards.yml
- includes/blocks/class-convertkit-block-broadcasts.php
- readme.txt
- resources/backend/js/gutenberg-block-broadcasts.js
- tests/acceptance/broadcasts/PageBlockBroadcastsCest.php
Displays a message in the Gutenberg editor when inserting the ConvertKit Broadcasts block, if the ConvertKit account has no Broadcasts.
No message is displayed on the frontend site output.
Before:
After:
- `PageBlockBroadcastsCest:testBroadcastsBlockWithNoBroadcasts`: Tests that the expected message is displayed in the Gutenberg editor when no Broadcasts exist in ConvertKit.
> Broadcasts Block: Display message in editor when no Broadcasts exist

- admin/class-convertkit-admin-bulk-edit.php
- admin/class-convertkit-admin-quick-edit.php
- includes/integrations/contactform7/class-convertkit-contactform7-admin-settings.php
- includes/integrations/wishlist/class-convertkit-wishlist-admin-settings.php
Fixes failing static analysis tests due to improvements in static analysis in PHPStan for WordPress 1.1.5.
> PHPStan for WordPress 1.1.5 compatbility

- .github/workflows/coding-standards.yml
- .github/workflows/tests.yml
Uses `latest` for `wp-versions`, so that tests and coding standards always run against the latest stable release of WordPress, to save having to change the version number every time there's a WordPress update.
> Run Tests against latest stable WordPress version

- .github/workflows/tests.yml
Runs tests against PHP 8.1, which is the current (and only) [actively supported version](https://www.php.net/supported-versions.php) provided by PHP.
`WP_DEBUG` is disabled when running tests against PHP 8.1, due to [this WordPress core](https://core.trac.wordpress.org/ticket/54504) issue that requires resolution to prevent `E_DEPRECATED` notices when performing HTTP requests.
Critical PHP errors and warnings will still result in test failure, however we'll need to reintroduce WP_DEBUG once WordPress resolve the above core issue.
> Run tests against PHP 8.1

- admin/class-convertkit-admin-refresh-resources.php
- tests/acceptance/general/RefreshResourcesButtonCest.php
- Enables the refresh resource button functionality on the `Add New Category` screen
- Adds tests for the refresh resource button for the `Add New Category` screen
- `RefreshResourcesButtonCest:testRefreshResourcesOnAddCategory`: Test the refresh resource button works when adding a new Category at Posts > Categories
- `RefreshResourcesButtonCest:testRefreshResourcesOnEditCategory`: Test the refresh resource button works when adding an existing Category at Posts > Categories
- `RefreshResourcesButtonCest:testRefreshResourcesErrorNoticeOnAddCategory`: Test the expected error message displays when the refresh resource button is used, and invalid API credentials are specified, when adding a new Category at Posts > Categories
- `RefreshResourcesButtonCest:testRefreshResourcesErrorNoticeOnEditCa …
> Update Refresh Resources Tests

- includes/blocks/class-convertkit-block.php
- tests/acceptance/broadcasts/PageBlockBroadcastsCest.php
- tests/acceptance/broadcasts/PageShortcodeBroadcastsCest.php
- tests/acceptance/broadcasts/WidgetBroadcastsCest.php
- tests/acceptance/products/PageBlockProductCest.php
- tests/acceptance/products/PageShortcodeProductCest.php
If a block/shortcode attribute is a string, and it's empty, use the default value.
This fixes:
Adding a block/shortcode with blank previous/next pagination labels would result in no pagination being displayed.
Before:
After:
Adding a block/shortcode with no button text would result in a blank button being displayed.
Before:
After:
The following tests have been added, to test that supplying blank labels / text results in the default pagination / button text displaying: 
PageBlockBroadcastsCest
- testBroadcastsBlockWithBlankPaginationLabelParameters
PageShortcodeBroadcastsCest
- testBroadcastsShortcodeInVisualEditorWithBlankPaginationLabelParameters
WidgetBroadcastsCest
- testBroadcastsBlockWithBlankPaginationLabelParameters
PageBlockProductCest
- testProductBlockWithBlankTextParameter …
> Broadcasts, Products: Use default value when string is empty

- .github/workflows/tests.yml
Fixes failing Contact Form 7 tests, which fail due to Contact Form 7 v5.7 introducing a PHP notice: https://wordpress.org/support/topic/contact-form-7-error-19/
This is temporary until Contact Form 7 issue an update to resolve their issue, at which point this PR can be reverted, to ensure the latest Contact Form 7 Plugin is used for tests.
> Tests: Use Contact Form 7 v5.6.4

- includes/blocks/class-convertkit-block-product.php
- tests/_support/Helper/Acceptance/Plugin.php
- tests/acceptance/general/PluginSettingsGeneralCest.php
Removes the double forwardslash when the `product.css` stylesheet is loaded, as reported [here](https://convertkit.atlassian.net/browse/BUG-113):
Also removes a double forwardslash when the product block preview image is output.
Both URLs do work with the double forwardslash, but it's best not to have it.
- `seeProductOutput()`: Check that the full `product.css` URL is correctly formed; this helper function is used for all Broadcast block and shortcode tests.
> Remove double forwardslash on product.css URL

- tests/_support/Helper/Acceptance/WPClassicEditor.php
- tests/acceptance/integrations/WooCommerceProductFormCest.php
Removes the click event on tests to display the product short description field, as [WooCommerce 7.2 no longer auto collapses it](https://github.com/woocommerce/woocommerce/pull/35213).
> Tests: Compatibility with WooCommerce 7.2

- includes/blocks/class-convertkit-block-broadcasts.php
- includes/class-convertkit-resource-forms.php
- includes/class-convertkit-resource-products.php
- readme.txt
- tests/acceptance/broadcasts/PageBlockBroadcastsCest.php
- tests/acceptance/broadcasts/PageShortcodeBroadcastsCest.php
- tests/acceptance/products/PageBlockProductCest.php
- tests/acceptance/products/PageShortcodeProductCest.php
- wp-convertkit.php
Escapes Shortcode and Block attributes on output, resolving [this reported issue](https://n7studios-workspace.slack.com/archives/C02KFR6N1GF/p1671075539275659).
- `testBroadcastsBlockParameterEscaping`: Tests that output is correctly escaped when using the Broadcasts block
- `testBroadcastsShortcodeParameterEscaping`: Tests that output is correctly escaped when using the Broadcasts shortcode
- `testProductBlockParameterEscaping`: Tests that output is correctly escaped when using the Product block
- `testProductShortcodeParameterEscaping`: Tests that output is correctly escaped when using the Product shortcode
> Escape Shortcode and Block Attributes

- includes/class-convertkit-output.php
Runs checks to get, validate and store the subscriber ID in a cookie on WordPress' `init` action, instead of the later `wp_enqueue_scripts` action.
This prevents [this reported PHP warning](https://convertkit.atlassian.net/browse/T3-106) when:
- a Page Builder (such as Elementor Pro) begins HTML <head> output earlier than expected, and
- a visitor accesses a WordPress Page/Post with the `ck_subscriber_id` request parameter (typically by clicking a link in a ConvertKit email)
> Move subscriber ID cookie logic

- .github/workflows/tests.yml
Run tests against latest Contact Form 7 version, now 5.7.1 resolves the previous issue.
> Run tests against Contact Form 7 latest version

- includes/class-convertkit-ajax.php
- tests/_support/Helper/Acceptance/ConvertKitAPI.php
- tests/_support/Helper/Acceptance/Email.php
- tests/acceptance/tags/PageTagCest.php
Fixes [this issue](https://convertkit.atlassian.net/browse/T3-112), where subscribers failed to be assigned a tag, when a Page is set to tag them.
This was caused by [this commit](https://github.com/ConvertKit/convertkit-wordpress/blame/ffb1eab47b519dfaad70f0b1d994dab12245485f/includes/class-convertkit-ajax.php#L170-L175), where the `$subscriber` array became overwritten with the `ConvertKit_Subscriber` class, meaning that access to the `email_address` later in the code would fail.
This wasn't caught as no test existed for this specific functionality, and the nature of the AJAX call meant no on screen error would be presented to the user.
- `PageTagCest:testDefinedTagAppliesToValidSubscriber`: Tests that accessing a Page configured to tag subscribers correctly tags the subscriber when a …
> Tag subscriber when Page's "Add a Tag" option defined

- includes/integrations/elementor/class-convertkit-elementor.php
Starting in Elementor 3.5.0, widgets should be registered using the [`register()` function](https://developers.elementor.com/docs/managers/registering-widgets/).
This has become a [hard deprecation in Elementor 3.9.0](https://developers.elementor.com/v3-5-planned-deprecations/), which results in a PHP Deprecated notice displaying if WP_DEBUG is enabled:
This PR resolves by using the applicable Elementor function to register our blocks as Elementor widgets, depending on the Elementor version.
> Elementor 3.9.0 Compatibility

- tests/_support/Helper/Acceptance/WPClassicEditor.php
- tests/acceptance/general/RefreshResourcesButtonCest.php
- views/backend/post/bulk-edit.php
- views/backend/post/meta-box.php
- views/backend/post/quick-edit.php
(See [here](https://n7studios-workspace.slack.com/archives/C02KFR6N1GF/p1672416207059939?thread_ts=1670631223.079979&cid=C02KFR6N1GF) for several videos demonstrating Restrict Content functionality; it may be useful to view these for context prior to reviewing PRs individually)
Adds a refresh resource button next to the Member's Content setting when Bulk or Quick editing Pages/Posts
- `RefreshResourcesButtonCest`: Test that the refresh resource button works for Member's Content settings.
> Restrict Content: Refresh Products Button

- composer.json
[Original PR](https://github.com/ConvertKit/convertkit-wordpress/pull/419) incorrectly set `wp-libs-1.3.0` to base off this `test-performance` branch instead of `main`.
> Merge `test-performance` into `main`

- includes/class-convertkit-post-type-product.php
- tests/_data/dump.sql
- tests/acceptance/general/RefreshResourcesButtonCest.php
- tests/acceptance/products/PageLinkProductCest.php
Fixes this error on Plugin deactivation, due to the Products Custom Post Type no longer being registered.
> Restrict Content: Fix error on Plugin Deactivation

- .scripts/class-read-actions-filters.php
- admin/section/class-convertkit-settings-base.php
- includes/blocks/class-convertkit-block-content.php
- includes/blocks/class-convertkit-block-form.php
- includes/class-convertkit-resource-landing-pages.php
- includes/functions.php
- includes/integrations/wishlist/class-convertkit-wishlist-admin-settings.php
Replaces the vague `mixed` parameter on docblocks with accurate definitions of accepted variable types, for improved PHPStan analysis.
> Replace mixed type in docblocks

- includes/class-convertkit-preview-output.php
- tests/acceptance/forms/EditFormLinkCest.php
Adds `utm_source` and `utm_content` parameters to the Edit form in ConvertKit link, to match UTM parameters added to other ConvertKit links.
- `EditFormLinkCest`: Modified tests to include detection of UTM parameters.
> Add UTM parameters to "Edit form in ConvertKit" link

- tests/acceptance/general/UpgradePathsCest.php
- tests/acceptance/integrations/ElementorBroadcastsCest.php
- tests/acceptance/integrations/ElementorFormCest.php
- tests/acceptance/integrations/ElementorProductCest.php
- tests/acceptance/landing-pages/PageLandingPageCest.php
- tests/acceptance/tags/PageTagCest.php
Fixes tests that specify no form should be defined in the Page's settings. This was incorrectly set to `-1`, which displays the default form; `0` is the correct value to display no form.
> Tests: Fix incorrect 'None' setting for Form

- includes/blocks/class-convertkit-block-form.php
- includes/blocks/class-convertkit-block-product.php
- resources/backend/js/gutenberg-block-product.js
- views/backend/tinymce/modal-field.php
Form block / shortcode:
- Removes an unused API Key and settings class
- Explains why a data attribute comprising of forms exists
- Check that Forms exist before attempting to `get()` Forms to populate the data attribute
Product block / shortcode:
- Removes unused data attributes and settings class
- Performs a simpler check when previewing a block to determine if a Product was specified in the Block's settings
Classic Editor:
- Removes unnecessary code to build unused data-attributes when the insert shortcode modal is displayed in the Classic Editor for Forms, Products and Broadcasts
- Always defines the data-shortcode attribute, correctly escaped, to determine the shortcode name to insert into the Classic Editor
> Fix Form and Product block / shortcode field definitions

- tests/wpunit/APITest.php
Adds a unit test to confirm that the Plugin's name and version number is in the user-agent string when making API requests.
- `APITest`: Unit test to confirm that the correct Plugin name and version number are included in the user-agent string when making API requests.
> Test User Agent for API requests

- includes/class-convertkit-preview-output.php
- tests/acceptance/forms/EditFormLinkCest.php
Fixes an issue where a PHP warning would be output if a logged in WordPress user previews a Page, Post or Custom Post being edited that contains a Legacy Form, due to these forms not having a `format` property.
Before:
After:
- EditFormLinkCest: Added test for legacy forms to confirm no errors and correct link to edit the legacy form on ConvertKit. Other tests include additional checks for PHP warnings/errors.
> Fix Preview with Legacy Form

- .github/workflows/coding-standards.yml
- .github/workflows/tests.yml
- includes/widgets/class-ck-widget-form.php
- resources/backend/js/gutenberg-block-broadcasts.js
- resources/backend/js/gutenberg-block-form.js
- resources/backend/js/gutenberg-block-product.js
- resources/backend/js/gutenberg.js
- tests/_support/Helper/Acceptance/WPGutenberg.php
- tests/_support/Helper/Acceptance/WPWidget.php
- tests/acceptance/forms/WidgetFormCest.php
Run tests against WordPress 6.2 Beta 1, fixing:
- Use `wp.serverSideRender` instead of deprecated `wp.components.ServerSideRender`, which is removed in WordPress 6.2
- Rename the ConvertKit Form widget to a Legacy Widget; users should use the Form block, but we need to retain the existing WordPress widget for backward compatibility for those already using it
> Run tests against WordPress 6.2 Beta 1

- resources/frontend/css/restrict-content.css
- Centers the call to action for themes that don't provide the styles to do this automatically.
- Removes text decoration on button links, that might be applied by some themes.
Before:
After:
> Restrict Content: Align CTA

- admin/section/class-convertkit-settings-general.php
- includes/blocks/class-convertkit-block-product.php
- includes/class-convertkit-output-restrict-content.php
- tests/_support/Helper/Acceptance/Plugin.php
- tests/acceptance/general/PluginSettingsGeneralCest.php
- tests/acceptance/restrict-content/RestrictContentSettingsCest.php
- Honors the `Disable CSS` setting at `Settings > ConvertKit`
- Updated the description for the `Disable CSS` setting to reflect which sections are affected
- Product CSS: Set ID to match format of other CSS e.g. Broadcasts
- `RestrictContentSettingsCest:testDisableCSSSetting`: Test that the `Disable CSS` setting is honored when enabled
> Restrict Content: Honor `Disable CSS` setting

- .github/workflows/tests.yml
Forces tests to run using Chromedriver v109, due to numerous [reported issues](https://groups.google.com/g/chromedriver-users) with v110.
Specifically:
- tests where downloading and inspecting a file's content
- tests to check an iframe exists
This will need to be reviewed periodically and a later version of Chromedriver used when they resolve.
> Tests: Use Chromedriver v109

- resources/backend/js/gutenberg.js
Refactor Gutenberg JS, similar to the work done for the [block formatters](https://github.com/ConvertKit/convertkit-wordpress/pull/459).
Removes unused constants and elements.
> Refactor Gutenberg JavaScript

- admin/class-convertkit-admin-settings-restrict-content.php
Adds a notice to the Member Content settings screen at `Settings > ConvertKit > Member Content (beta)`, advising that  any server side or plugin level caching system must be configured to disable caching when the `ck_subscriber_id` cookie is present.
Whilst we forcibly exclude caching by [appending a query parameter](https://github.com/ConvertKit/convertkit-wordpress/pull/464) as part of the authentication flow, two scenarios still exist where cached (incorrect) content can be served by the server or a third party caching plugin:
1. If a subscriber subsequently leaves the WordPress Page, and then accesses it days later (e.g. through a link on the web site, perhaps in the site navigation menu, which will not include a query parameter)
2. A different visitor accesses the same page; some …
> Restrict Content: Add caching warning notice

- admin/class-convertkit-admin-settings.php
- includes/blocks/class-convertkit-block-broadcasts.php
- includes/class-convertkit-preview-output.php
- includes/functions.php
- readme.txt
- tests/_support/Helper/Acceptance/Plugin.php
- tests/_support/Helper/Acceptance/WPGutenberg.php
- tests/acceptance/broadcasts/PageBlockBroadcastsCest.php
- tests/acceptance/broadcasts/PageShortcodeBroadcastsCest.php
- tests/acceptance/forms/EditFormLinkCest.php
- tests/acceptance/forms/PageNoFormCest.php
- tests/acceptance/general/PluginSettingsGeneralCest.php
- tests/acceptance/general/PluginSetupWizardCest.php
- tests/acceptance/integrations/ElementorBroadcastsCest.php
As discussed with @brendancarney, adds the WordPress locale (e.g. `en_US`) to the `utm_term` in links to ConvertKit, so we can determine the most common languages used and prioritize which languages to translate the Plugin to.
- Existing tests updated to check for `utm_term`.
> Add locale to `utm_term`

- tests/_support/Helper/Acceptance/WPBulkEdit.php
- tests/acceptance/forms/CategoryFormCest.php
- tests/acceptance/general/PageCest.php
- tests/acceptance/general/PluginSettingsGeneralCest.php
- tests/acceptance/general/PluginSettingsToolsCest.php
- tests/acceptance/general/PostCest.php
- tests/acceptance/integrations/ContactForm7FormCest.php
- tests/acceptance/restrict-content/RestrictContentFilterCest.php
- tests/acceptance/restrict-content/RestrictContentSetupCest.php
- tests/acceptance/tags/PageShortcodeCustomContentCest.php
Wait for an expected DOM element to be visible before asserting whether expected text is on the screen, immediately after loading a given URL.
Use `see()` in place of `seeInSource()` when asserting if text is displayed; `seeInSource()` is best for determining if raw HTML exists.
Prevents tests failing despite the output being valid:
Ensures tests run and pass first time:
https://github.com/ConvertKit/convertkit-wordpress/actions/runs/4982297086
> Improve reliability of tests that use `see()`

- includes/class-convertkit-output-restrict-content.php
- includes/class-wp-convertkit.php
- includes/integrations/contactform7/class-convertkit-contactform7-settings.php
- includes/integrations/wishlist/class-convertkit-wishlist-settings.php
- views/frontend/restrict-content/notices.php
Removes the few remaining PHPStan ignore directives in our code by making the applicable improvements to pass PHPStan static analysis.
> Remove all PHPStan ignores

- includes/class-wp-convertkit.php
- includes/integrations/elementor/class-convertkit-elementor-widget-formtrigger.php
- tests/acceptance/integrations/ElementorFormTriggerCest.php
Registers the [Form Trigger button](https://github.com/ConvertKit/convertkit-wordpress/pull/456) as an Elementor widget
- `ElementorFormTriggerCest`: Add tests to confirm the Form Trigger button registers as an Elementor widget and works when configured.
> Elementor: Form Trigger Button Widget

- .github/workflows/tests.yml
- tests/_support/Helper/Acceptance/WPCachePlugins.php
- tests/acceptance.suite.yml
- tests/acceptance/restrict-content/RestrictContentCacheCest.php
Adds tests for common WordPress Caching Plugins when using Member Content, to confirm that the correct content is displayed when a valid `ck_subscriber_id` cookie exists.
- `RestrictContentCacheCest`: Tests to confirm that Member Content functionality works when common WordPress Caching Plugins are correctly configured to exclude caching when the `ck_subscriber_id` cookie exists.
> Restrict Content: Tests for common Caching Plugins

- admin/section/class-convertkit-settings-general.php
- includes/blocks/class-convertkit-block-broadcasts.php
- includes/blocks/class-convertkit-block-form-trigger.php
- includes/class-convertkit-resource-products.php
- views/backend/post/no-api-key.php
- views/backend/setup-wizard/convertkit-setup/content-3.php
Uses `[esc_url()](https://developer.wordpress.org/reference/functions/esc_url/)` instead of `esc_attr()` for link `href` attributes, for best practices.
> Use `esc_url()` instead of `esc_attr()` for link href attributes

- includes/blocks/class-convertkit-block-form.php
- includes/functions.php
- resources/backend/js/gutenberg-block-form.js
- resources/backend/js/gutenberg.js
- tests/_support/Helper/Acceptance/Plugin.php
- tests/acceptance/forms/PageBlockFormCest.php
- tests/wpunit/ResourcePostsTest.php
When adding the ConvertKit Form Block, displays a notice if no API key is specified, or the ConvertKit account has no forms specified, including a link to the settings screen / ConvertKit to resolve.
- `PageBlockFormCest:testFormBlockWhenNoAPIKey`: Confirms that the expected message displays when no forms exist in ConvertKit
- `PageBlockFormCest:testFormBlockWhenNoForms`: Confirms that the expected message displays when no forms exist in ConvertKit
> Form Block: Display link to enter API Key or add Form in ConvertKit

- includes/blocks/class-convertkit-block-broadcasts.php
- includes/blocks/class-convertkit-block-content.php
- includes/blocks/class-convertkit-block-form-trigger.php
- includes/blocks/class-convertkit-block-form.php
- includes/blocks/class-convertkit-block-product.php
- resources/backend/css/tinymce.css
- resources/backend/js/quicktags.js
- resources/backend/js/tinymce.js
- resources/frontend/css/broadcasts.css
- resources/frontend/js/broadcasts.js
- tests/_support/Helper/Acceptance/Plugin.php
- tests/_support/Helper/Acceptance/WPGutenberg.php
- tests/acceptance/broadcasts/PageBlockBroadcastsCest.php
- tests/acceptance/broadcasts/PageShortcodeBroadcastsCest.php
- tests/acceptance/broadcasts/WidgetBroadcastsCest.php
Adds options to the ConvertKit Broadcasts block and shortcode to display output as a grid, and optionally display each broadcasts' image, description and read more link.
Demo:
https://www.loom.com/share/0fb937fabe364d928ad0497b593177af
Requires [this PR](https://github.com/ConvertKit/convertkit/pull/23938) to merge into the WordPress API. Tests mock this expected data structure to confirm working functionality.
Responsive CSS for list and grid views on smaller screens to follow in separate PR.
- `PageBlockBroadcastsCest`: Added tests for display as grid, images, descriptions, read more links and read more label.
- `PageShortcodeBroadcastsCest`: Added tests for display as grid, images, descriptions, read more links and read more label when using the [convertkit_broadcasts] shortcode.
> Broadcasts Block / Shortcode: Add grid, image, description and read more support

- includes/blocks/class-convertkit-block-form-trigger.php
- resources/backend/js/gutenberg-block-form-trigger.js
- tests/acceptance/forms/PageBlockFormTriggerCest.php
When adding the ConvertKit Form Trigger Block, displays a notice if no API key is specified, or the ConvertKit account has no forms specified, including a link to the settings screen / ConvertKit to resolve.
- `PageBlockFormTriggerCest:testFormTriggerBlockWhenNoAPIKey`: Confirms that the expected message displays when no forms exist in ConvertKit
- `PageBlockFormTriggerCest:testFormTriggerBlockWhenNoForms`: Confirms that the expected message displays when no forms exist in ConvertKit
> Form Trigger Block: Display link to enter API Key or add Form in ConvertKit

- includes/blocks/class-convertkit-block-form-trigger.php
- resources/backend/js/gutenberg-block-form-trigger.js
- tests/acceptance/forms/PageBlockFormTriggerCest.php
- tests/acceptance/forms/PageShortcodeFormTriggerCest.php
Similar to the [PR on Form and Product Shortcodes,](https://github.com/ConvertKit/convertkit-wordpress/pull/488) displays a message in the modal window when using the Form Trigger shortcode in the Classic Editor, and either no API Key is specified, or no Forms exist in ConvertKit.
- `PageShortcodeFormTriggerCest:testFormTriggerShortcodeWhenNoAPIKey`: Confirms that the expected message displays when no API key is specified in the Plugin's settings.
- `PageShortcodeFormTriggerCest:testFormTriggerShortcodeWhenNoForms`: Confirms that the expected message displays when no forms exist in ConvertKit
> Form Trigger Shortcode: Display notice when no API Key or Resources

- composer.json
- includes/block-formatters/class-convertkit-block-formatter-form-link.php
- includes/blocks/class-convertkit-block-form-trigger.php
- includes/class-convertkit-resource-forms.php
- tests/acceptance/forms/PageBlockFormTriggerCest.php
- tests/acceptance/forms/PageShortcodeFormTriggerCest.php
- tests/wpunit/ResourceFormsNoDataTest.php
- tests/wpunit/ResourceFormsTest.php
Adds a `non_inline_exist` method to the Form resource class, to determine if non-inline ConvertKit Forms exist.
Updates the message displayed on the Form Trigger block and shortcode when no non-inline ConvertKit Forms exist:
- `ResourceFormsTest:testNonInlineExist`: Test that using the `non_inline_exist` returns true when non inline forms exist.
- `ResourceFormsNoDataTest:testNonInlineExist`: Test that using the `non_inline_exist` returns false when no non inline forms exist.
> Add `non_inline_exist` method to Forms resource class

- ACTIONS-FILTERS.md
- composer.json
- includes/block-formatters/class-convertkit-block-formatter-form-link.php
- includes/blocks/class-convertkit-block-form-trigger.php
- includes/class-convertkit-resource-forms.php
- languages/convertkit.pot
- readme.txt
- tests/wpunit/ResourceFormsTest.php
- wp-convertkit.php
Adds a `get_non_inline` method to the Form resource class, to fetch ConvertKit Forms that are not inline.
This replaces two instances which would previously iterate through all Forms, to determine if each Form is inline or not.
- `ResourceFormsTest:testGetNonInline`: Test that using the `get_non_inline` method returns the expected non inline forms in the correct order.
- `ResourceFormsTest:testGetNonInlineWithValidOrderByAndOrder`: Test that using the `get_non_inline` method returns the expected non inline forms in the correct order, when `order_by` and `order are specified.
- `ResourceFormsTest:testGetNonInlineWithInvalidOrderBy`: Test that using the `get_non_inline` method returns the expected non inline forms in the correct order, when an invalid `order_by` parameter is specified.
> Forms: Add `get_non_inline` method

- admin/class-convertkit-admin-settings-restrict-content.php
- admin/class-convertkit-admin-settings.php
- admin/section/class-convertkit-settings-general.php
- resources/backend/js/settings-conditional-display.js
- tests/acceptance/general/PluginSettingsToolsCest.php
- tests/acceptance/restrict-content/RestrictContentSettingsCest.php
Conditionally displays settings on `Settings > ConvertKit > Member Content`, depending on whether the `Enable` checkbox is checked or not.
Loads specific JS and CSS depending on the settings screen that is requested, by using our `convertkit_admin_settings_enqueue_scripts` action.  Specifically:
- `General`: Load Select2 JS and CSS. We don't need this on the Tools or Member Content settings screens
- `Member Content`: Load `settings-conditional-display.js` to conditionally show/hide settings fields
- `RestrictContentSettingsCest:testEnableDisable`: Updated test to check that settings fields display / hide depending on whether the `Enable` checkbox is checked or not.
> Restrict Content: Conditionally display settings

- resources/backend/js/modal.js
- resources/backend/js/tinymce.js
- tests/acceptance/broadcasts/PageShortcodeBroadcastsCest.php
Fixes an issue where the TinyMCE modal for a shortcode would fail to load correctly (Insert / Cancel buttons would fail to work, and the tabbed interface wouldn't load), when switching from the Text Editor.
- `PageShortcodeBroadcastsCest:testBroadcastsShortcodeWhenSwitchingEditors`: Tests that the modal window works correctly when used in the text editor, switching to the visual editor and attempting to use it again for the broadcasts shortcode.
> Fix QuickTags to TinyMCE Switching

- .github/workflows/tests.yml
- includes/class-convertkit-resource-forms.php
- tests/acceptance/general/ActivateDeactivatePluginCest.php
Fixes the error reported [here](https://wordpress.org/support/topic/error-1795/) and [here](https://wordpress.org/support/topic/uncaught-error-call-to-undefined-method-convertkit_resource_formsget_by/), by checking that the ConvertKit WordPress Libraries loaded contain the necessary `get_by` function before using it.
This covers the scenario where:
- a WordPress site has the ConvertKit Plugin 2.2.3 or older and (in this case) the ConvertKit for WooCommerce 1.6.4 Plugin installed and active, and
- the main ConvertKit Plugin is updated to the latest version, 2.2.4, which includes a newer version of the ConvertKit WordPress Libraries (in this case, 1.3.6), and
- other ConvertKit Plugins are not (yet) updated - either because the user did not select them for updating, or the user did select …
> Fix undefined method `get_by`

- resources/backend/js/gutenberg-block-formatters.js
When applying or editing a block formatter (for adding/editing a form trigger or product trigger), implement the `useAnchor` hook instead of the deprecated `useAnchorRef`.
Before:
After:
> Implement `useAnchor` instead of deprecated `useAnchorRef`

- tests/_support/Helper/Acceptance/WPBulkEdit.php
- tests/acceptance/restrict-content/RestrictContentSetupCest.php
Fixes flaky tests when interacting with specific elements, ensuring they pass first time:
> Fix flaky tests

- includes/blocks/class-convertkit-block-broadcasts.php
- includes/class-convertkit-ajax.php
- includes/class-convertkit-gutenberg.php
- includes/functions.php
- resources/backend/css/gutenberg.css
- resources/backend/js/gutenberg-block-broadcasts.js
- resources/backend/js/gutenberg-block-form-trigger.js
- resources/backend/js/gutenberg-block-form.js
- resources/backend/js/gutenberg.js
- tests/acceptance/broadcasts/PageBlockBroadcastsCest.php
- tests/acceptance/forms/PageBlockFormCest.php
- tests/acceptance/forms/PageBlockFormTriggerCest.php
- tests/acceptance/products/PageBlockProductCest.php
Adds a refresh button to the Broadcast, Form, Form Trigger and Product blocks when either no API Keys are specified, or no resources (forms, broadcasts etc) exist.
Demo:
https://www.loom.com/share/9e751c61a6c44a4d84cf88b6c9231912?sid=600e5c5b-c186-4575-94c0-f7704f34c9cc
This is part of a larger goal to have new users discover the ConvertKit Plugin through the "available to install" blocks section by e.g. searching for a form block, adding it, authorizing / registering through oAuth and then selecting a form - all without needing to leave the editor screen to enter API keys etc.
- `testBroadcastsBlockRefreshButton`: Test that the refresh button works when adding a Broadcasts block with no API Keys or ConvertKit posts, adding said items and then clicking refresh
- …
> Add refresh button to blocks

- admin/class-convertkit-admin-setup-wizard.php
- admin/setup-wizard/class-convertkit-admin-setup-wizard-plugin.php
- resources/backend/css/gutenberg.css
- resources/backend/css/setup-wizard.css
- resources/backend/js/gutenberg.js
- tests/_support/Helper/Acceptance/Plugin.php
- tests/acceptance/broadcasts/PageBlockBroadcastsCest.php
- tests/acceptance/forms/PageBlockFormCest.php
- tests/acceptance/forms/PageBlockFormTriggerCest.php
- tests/acceptance/general/PluginSetupWizardCest.php
- tests/acceptance/products/PageBlockProductCest.php
- views/backend/setup-wizard/close-modal.php
- views/backend/setup-wizard/convertkit-setup/content-2.php
- views/backend/setup-wizard/footer.php
- views/backend/setup-wizard/header.php
Provides the option to serve a Setup Wizard in a modal or popup, by removing the header, progress bar and footer, used in [this PR](https://github.com/ConvertKit/convertkit-wordpress/pull/505).
Modal version:
Non-modal version:
This is used when first installing the Plugin, adding a block and clicking the link to enter API credentials, all from within the Gutenberg editor.  [See PR](https://github.com/ConvertKit/convertkit-wordpress/pull/505).
- `PluginSetupWizardCest:testSetupWizardModal`: Test that the modal version of the Plugin's Setup Wizard displays when the `convertkit-modal` parameter is included in the request.
> Setup Wizard: Modal View

- includes/class-convertkit-resource-creator-network-recommendations.php
- includes/functions.php
- includes/integrations/contactform7/class-convertkit-contactform7-admin-settings.php
- includes/integrations/contactform7/class-convertkit-contactform7-settings.php
- includes/integrations/contactform7/class-convertkit-contactform7.php
- tests/_support/Helper/Acceptance/Plugin.php
- tests/acceptance/integrations/ContactForm7FormCest.php
- wp-convertkit.php
Adds an option to enable the Creator Network Recommendations to a Contact Form 7 Form within the ConvertKit Plugin at `Settings > ConvertKit > Contact Form 7`:
When enabled, the modal is displayed when the form is submitted:
Demonstration:
https://www.loom.com/share/45db4e9f41e54deca1ae83a66fbb0090?sid=3b32c69a-8005-4c84-aac9-0d0f665c4323
Requirements must be met for this to work:
If the [API endpoint](https://github.com/ConvertKit/convertkit/pull/24419) `enabled` property returns `false`, the user is prompted to upgrade their ConvertKit Plan.
- `testSettingsContactForm7WhenNoAPIKeyAndSecret`: Confirm that no settings are displayed when no API Key and Secret are specified in the Plugin's settings (this isn't related to the Creator Network, but was a missing test that should have been …
> Contact Form 7: Add Creator Network Recommendations

- admin/section/class-convertkit-admin-settings-broadcasts.php
- tests/acceptance/broadcasts/BroadcastsSettingsCest.php
Shows or hides the Member Content setting at `Settings > ConvertKit > Broadcasts`, depending on whether Member Content functionality is enabled at `Settings > ConvertKit > Member Content`.
- `BroadcastsSettingsCest:testRestrictContentSettingHiddenWhenRestrictContentDisabled`: Test that the Member Content setting is not displayed when Member Content is disabled at `Settings > ConvertKit > Member Content`
- `BroadcastsSettingsCest:testRestrictContentSettingDisplayedWhenRestrictContentEnabled`: Test that the Member Content setting is displayed when Member Content is disabled at `Settings > ConvertKit > Member Content`
> Broadcasts to Posts: Settings UI: Member Content

- tests/_support/Helper/Acceptance/WPCachePlugins.php
Makes existing tests compatible with W3 Total Cache 2.4.0's UI changes for clicking buttons.
> Tests: Compatibility with W3 Total Cache 2.4.0

- resources/backend/js/gutenberg-block-formatters.js
Fixes [this reported issue](https://convertkit.atlassian.net/jira/software/c/projects/T3/boards/27?modal=detail&selectedIssue=T3-486), where `useAnchor` isn't available in WordPress versions below 6.1, resulting in an error.
Issue first introduced by [this PR](https://github.com/ConvertKit/convertkit-wordpress/pull/500), where `useAnchorRef` was replaced by `useAnchor`.
Existing tests pass. Also manually tested on WordPress 5.9.7 to confirm this will work on the specific site in question.
> Check if `useAnchor` is available

- .github/workflows/tests.yml
Fix a permissions error when running tests on GitHub Actions for WP-Optimize, since the release of WP-Optimize 3.2.17.
> Tests: Fix permissions for WP-Optimize

- admin/section/class-convertkit-admin-settings-broadcasts.php
- admin/section/class-convertkit-settings-base.php
- tests/acceptance/broadcasts/BroadcastsToPostsSettingsCest.php
Fixes a bug where the `Disable Styles` setting would remain displayed when the `Enable` setting was not checked.
- `BroadcastsToPostsSettingsCest:testEnableDisable`: Improved test by checking for named fields, rather than assuming an `enabled` class was added to every named field.
> Broadcasts to Posts: Conditionally display `Disable Styles` setting

- admin/section/class-convertkit-admin-settings-broadcasts.php
- tests/acceptance/broadcasts/BroadcastsToPostsSettingsCest.php
Displays the next import date and time when Broadcasts to Posts functionality is enabled
- `BroadcastsToPostsSettingsCest:testEnableDisable`: Confirm description below `Enabled` field shows the next import date and time, when enabled.
> Broadcasts to Posts: Display next import date and time

- .github/workflows/coding-standards.yml
Annotates code in a PR when coding standards errors are detected by the GitHub action:
[]
> Annotate PR with Coding Standard Errors

- composer.json
Remove duplicate `codeception/util-universalframework` entry in `composer.json`
> Remove duplicate `codeception/util-universalframework` entry

- tests/acceptance/broadcasts/import/BroadcastsToPostsCest.php
Adds a test to confirm Broadcasts are not imported as WordPress Posts when functionality disabled in settings
- `BroadcastsToPostsCest:testBroadcastsImportWhenDisabled`: Test that Broadcasts are not imported as WordPress Posts when functionality disabled in settings
> Broadcasts to Posts: Add test when disabled

- includes/integrations/forminator/class-convertkit-forminator-admin-settings.php
- includes/integrations/forminator/class-convertkit-forminator-settings.php
- includes/integrations/forminator/class-convertkit-forminator.php
- tests/acceptance/integrations/other/ForminatorCest.php
Adds an option to enable the Creator Network Recommendations to a Forminator Form within the ConvertKit Plugin at `Settings > ConvertKit > Forminator`:
When enabled, the modal is displayed when the form is submitted:
Requirements must be met for this to work:
If the [API endpoint](https://github.com/ConvertKit/convertkit/pull/24419) `enabled` property returns `false`, the user is prompted to upgrade their ConvertKit Plan.
The Forminator Form's method setting must be set to Ajax
- `testSettingsForminatorCreatorNetworkRecommendationsWhenDisabledOnConvertKitAccount`: Tests that the 'Enable Creator Network Recommendations' option on a Form's settings is not displayed when Creator Network Recommendations are not enabled on the ConvertKit account.
- …
> Forminator: Add Creator Network Recommendations

- includes/blocks/broadcasts/block.json
- includes/blocks/form/block.json
- includes/blocks/formtrigger/block.json
- includes/blocks/product/block.json
- includes/class-convertkit-gutenberg.php
The plugin is listed in the [block directory](https://en-gb.wordpress.org/plugins/browse/blocks/page/4/) - but to be eligible for inclusion in the `Available to install` section of the block editor (for sites where this Plugin is not installed), `block.json` definitions for each block (broadcasts, form, form trigger, products) need to be included:
https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#benefits-using-the-metadata-file
> Add block.json definitions

- .github/workflows/coding-standards.yml
- .github/workflows/tests.yml
- admin/section/class-convertkit-settings-base.php
- includes/integrations/forminator/class-convertkit-forminator-admin-settings.php
- includes/integrations/forminator/class-convertkit-forminator-settings.php
- includes/integrations/forminator/class-convertkit-forminator.php
- tests/acceptance/integrations/other/ForminatorCest.php
- wp-convertkit.php
Similar to the Contact Form 7 integration, adds options to subscribe entries to a specified ConvertKit Form when a Forminator Form is submitted.
- `ForminatorCest:testSettingsForminatorWhenNoAPIKeyAndSecret`: Test that no Forminator settings are displayed when no API Key and Secret are defined.
- `ForminatorCest:testSettingsForminatorWhenNoForms`: Test that no Forminator settings are displayed when an API Key and Secret are defined, but the ConvertKit account has no forms
- `ForminatorCest:testSettingsForminatorToConvertKitFormMapping`: Test that the email address and name are subscribed to the selected ConvertKit Form when a Forminator Form mapping is defined and the form submitted
> Forminator Integration

- includes/class-convertkit-resource-landing-pages.php
- tests/acceptance/forms/general/PageLandingPageCest.php
Extends #542, adding support for displaying WordPress' Site Icon for legacy landing pages, as legacy landing pages don't have a `link rel` specified by default.
`testLegacyLandingPageSiteIcon`: Tests that the WordPress Site Icon is output in the legacy landing page HTML
> Display WordPress Site Icon as favicon for Legacy Landing Pages

- includes/widgets/class-ck-widget-form.php
- views/backend/post/bulk-edit.php
- views/backend/post/meta-box.php
- views/backend/post/quick-edit.php
- views/backend/post/wp-list-table-filter.php
- views/backend/setup-wizard/convertkit-restrict-content-setup/content-2.php
- views/backend/setup-wizard/convertkit-setup/content-3.php
- views/backend/term/fields-add.php
- views/backend/term/fields-edit.php
Removes whitespace on `<option>` elements, ensuring that select2 title attributes render correctly when the cursor is hovered over a select2 field.
Before:
After:
> Remove whitespace on <option> elements

- admin/class-convertkit-admin-settings-restrict-content.php
- admin/section/class-convertkit-admin-settings-broadcasts.php
- tests/acceptance/broadcasts/import/BroadcastsToPostsSettingsCest.php
- tests/acceptance/forms/general/CategoryFormCest.php
- tests/acceptance/restrict-content/RestrictContentSettingsCest.php
- views/backend/term/fields-add.php
- views/backend/term/fields-edit.php
Adds missing `for` attributes on `label` elements in the Plugin's Member Content and Broadcasts settings screens.
Fixes an incorrect `for` attribute value when creating or editing a WordPress Category.
- `BroadcastsToPostsSettingsCest:testAccessibility`: Tests that the expected `for` attributes on `label` elements exist when viewing the Broadcasts settings screen.
- `RestrictContentSettingsCest:testAccessibility`: Tests that the expected `for` attributes on `label` elements exist when viewing the Member Content settings screen.
- `CategoryFormCest`: Updated tests to confirm the correct `for` attribute on the `label` element when creating or editing a WordPress Category.
> Add `for` attribute on `label` elements

- includes/blocks/broadcasts/block.json
- includes/blocks/form/block.json
- includes/blocks/formtrigger/block.json
- includes/blocks/product/block.json
- wp-convertkit.php
- Fixes the `block.json` definitions to meet WordPress' requirements for possible inclusion in the 'Available to install' section of the block editor.
- Adds more keywords for the Form block, to aid discovery
- Updates the description displayed in the 'Available to install' section, to better reflect what functionality ConvertKit provides.
Before:
After:
We're already listed in the [block directory](https://en-gb.wordpress.org/plugins/browse/blocks/page/4/) as WordPress approved our previous manual submission as a [plugin containing blocks](https://developer.wordpress.org/plugins/wordpress-org/add-your-plugin-to-the-block-directory/#plugins-containing-blocks).
Not sure how to perform testing, or perhaps didn't include a test in this PR? Walk through the following in order for a …
> Fix `block.json` for block discovery

- .github/workflows/tests.yml
- admin/class-convertkit-admin-restrict-content.php
- admin/class-convertkit-admin-setup-wizard.php
- admin/setup-wizard/class-convertkit-admin-setup-wizard-plugin.php
- admin/setup-wizard/class-convertkit-admin-setup-wizard-restrict-content.php
- includes/functions.php
- tests/acceptance/forms/shortcodes/PageShortcodeFormCest.php
- tests/acceptance/forms/shortcodes/PageShortcodeFormTriggerCest.php
- tests/acceptance/general/PluginSetupWizardCest.php
- tests/acceptance/products/PageShortcodeProductCest.php
- tests/acceptance/restrict-content/RestrictContentSetupCest.php
Fixes:
- Use `add_submenu_page` to register setup wizard routes against `options.php` instead of `index.php`, fixing an issue where blank submenu items would incorrectly display in the WordPress Administration interface when a third party administration menu management plugin (such as Admin Menu Editor) is activated.
- For the Add New Member Content wizard, change the `post_type` request URI parameter to `ck_post_type`, to avoid a WordPress permissions issue.
Before:
After:
- `PluginSetupWizardCest:testNoSetupWizardDashboardSubmenuItem`: Test that no dashboard submenu item is displayed for the Plugin's `Setup Wizard` when the Admin Menu Editor plugin is active and configured.
- `RestrictContentSetupCest:testNoMemberContentWizardDashboardSubmenuItem`: Test that no Member Content submenu …
> Wizards: Fix Blank Submenu Items and Access

- .github/workflows/tests.yml
- admin/class-convertkit-admin-restrict-content.php
- includes/class-convertkit-output-restrict-content.php
- tests/_support/Helper/Acceptance/Plugin.php
- tests/acceptance/restrict-content/RestrictContentSettingsCest.php
- tests/acceptance/restrict-content/RestrictContentSetupCest.php
- tests/acceptance/restrict-content/RestrictContentTagCest.php
- views/backend/post/bulk-edit.php
- views/backend/post/meta-box.php
- views/backend/post/quick-edit.php
- views/backend/post/wp-list-table-filter.php
- views/frontend/restrict-content/product.php
- views/frontend/restrict-content/tag.php
As requested [here](https://twitter.com/brendanaw/status/1704484890841137157), extends the existing Member Content functionality, adding an option to require that the subscriber be assigned to a specified Tag to view the member only content.
If the entered email address is not a subscriber, they will be subscribed and tagged, granting access to the member only content.
If the entered email address is subscribed, but not yet tagged to the specified tag, they will be tagged, again granting access to the member only content.
Demonstration video:
https://www.loom.com/share/1a0af441535d45c4be19501db7bfde46?sid=8ab56a77-f2e2-41de-8447-6dadaa858b86
- `RestrictContentTagCest`: Adds tests to confirm Restrict Content functionality works with tags
> Member Content: Restrict Content by Tag

- admin/class-convertkit-admin-restrict-content.php
- includes/functions.php
- tests/_support/Helper/Acceptance/Plugin.php
- tests/acceptance/restrict-content/RestrictContentCacheCest.php
- tests/acceptance/restrict-content/RestrictContentFilterPageCest.php
- tests/acceptance/restrict-content/RestrictContentFilterPostCest.php
- tests/acceptance/restrict-content/RestrictContentProductPageCest.php
- tests/acceptance/restrict-content/RestrictContentProductPostCest.php
- tests/acceptance/restrict-content/RestrictContentSettingsCest.php
- tests/acceptance/restrict-content/RestrictContentSetupCest.php
Adds options to:
- define the Member Content setting for WordPress Posts,
- filter WordPress Posts by a ConvertKit Product.
With the introduction of ConvertKit Broadcasts to WordPress Posts functionality, ConvertKit paid posts are correctly gated when viewed as WordPress Posts.  However, the admin UI to define/filter by ConvertKit Product on WordPress Posts was not displaying, as it was set to only display on WordPress Pages.
- `RestrictContentFilterPostCest`: Tests that the filter dropdown displays on the WordPress Posts screen, and filters Posts by ConvertKit Product
- `RestrictContentProductPostCest`: Tests that the Member Content functionality works when a ConvertKit Product is assigned as the Member Content option for a WordPress Post
- …
> Member Content: Display Filters and Settings on Posts

- includes/class-convertkit-output-restrict-content.php
- tests/acceptance/restrict-content/RestrictContentProductPageCest.php
- tests/acceptance/restrict-content/RestrictContentProductPostCest.php
- tests/acceptance/restrict-content/RestrictContentTagCest.php
Checks that a resource (Tag or Product) exists before restricting a Page or Post's content.
If the resource does not exist, all content is displayed on the Page / Post.
Fixes this issue where an uncaught WP_Error occurs when a Tag or Product no longer exists in ConvertKit (either deleted or the API Keys have been changed in the Plugin), and a WordPress Page or Post still has its Member Content setting set to the existing resource.
Before:
After:
- `testRestrictContentByInvalidProduct`: Tests that all Page / Post content is displayed when an invalid Product is specified as the Restrict Content setting on a Page / Post.
- `testRestrictContentByInvalidTag`: Tests that all Page / Post content is displayed when an invalid Tag is specified as the Restrict Content setting on a Page / Post.
> Restrict Content: Check Resource Exists

- admin/setup-wizard/class-convertkit-admin-setup-wizard-restrict-content.php
- tests/acceptance/restrict-content/RestrictContentSetupCest.php
- views/backend/setup-wizard/convertkit-restrict-content-setup/content-1.php
- views/backend/setup-wizard/convertkit-restrict-content-setup/content-2.php
Allows the user to restrict content by Tag in the Add New Member Content setup wizard.
- `testAddNewMemberContentDownloadsByTag`: Test that the Add New Member Content > Downloads generates the expected Page and restricts content by the selected Tag.
- `testAddNewMemberContentCourseByTag`: Test that the Add New Member Content > Course generates the expected Pages and restricts content by the selected Tag.
> Restrict Content Wizard: Add support for Tags

- admin/setup-wizard/class-convertkit-admin-setup-wizard-restrict-content.php
- includes/functions.php
- tests/acceptance/restrict-content/RestrictContentSetupCest.php
- views/backend/setup-wizard/convertkit-restrict-content-setup/content-1.php
Displays call to action buttons with links to ConvertKit to add a Product or Tag, when the ConvertKit account has neither specified.
Prevents users ending up on a screen where they can't proceed, because there are no Products or Tags to choose from.
Before:
After:
- `testAddNewMemberContentButtonNotDisplayedWhenNoResources`: Removed this test, as it failed to check that the `Add New Member Content` button was displayed when a ConvertKit account contains no Products or Tags, due to the incorrect `a.convertkit-action page-title-action` selector that would pass every time. No logic in the Plugin has ever existed to prevent this button from displaying under these conditions.
- `testAddNewMemberContentDisplaysCTAWhenNoResources`: Tests that the wizard screen displays links to creating a …
> Restrict Content: Wizard: Display options when no Products or Tags exist

- includes/blocks/class-convertkit-block-form.php
- resources/frontend/css/broadcasts.css
- resources/frontend/css/button.css
- resources/frontend/css/form.css
As [reported here](https://convertkit.atlassian.net/jira/software/c/projects/T3/boards/27?selectedIssue=T3-580), adds CSS margins to Form, Form Trigger and Product blocks when used on non-block WordPress Themes, as these non-block based Themes won't include or use WordPress' global `block spacing` property:
Before:
After:
> Replicate spacing on Blocks for non-block Themes

- includes/blocks/class-convertkit-block-form-trigger.php
- includes/blocks/class-convertkit-block-product.php
- resources/backend/js/gutenberg-block-broadcasts.js
- resources/backend/js/gutenberg-block-form-trigger.js
- resources/backend/js/gutenberg-block-form.js
- resources/backend/js/gutenberg-block-product.js
Fixes an issue where applying a background color to a Form Trigger or Product button block would result in different output between the editor and frontend, due to the color being applied to the editor `div` element, resulting in the border radius not showing.
Frontend output (before and after, always correct):
Before (editor):
After (editor):
> Match Button Blocks Output in Editor and Frontend

- tests/acceptance/broadcasts/blocks/PageBlockBroadcastsCest.php
- tests/acceptance/forms/blocks/PageBlockFormCest.php
- tests/acceptance/forms/blocks/PageBlockFormTriggerCest.php
- tests/acceptance/forms/shortcodes/PageShortcodeFormCest.php
- tests/acceptance/forms/shortcodes/PageShortcodeFormTriggerCest.php
- tests/acceptance/products/PageBlockProductCest.php
- tests/acceptance/products/PageShortcodeProductCest.php
Improves reliability of tests by waiting for the modal's contents to load, checking the expected element is visible, instead of immediately checking the DOM.
> Tests: Use `waitForElementVisible` when checking modal content

- admin/section/class-convertkit-admin-settings-broadcasts.php
- includes/class-convertkit-broadcasts-importer.php
- includes/class-convertkit-settings-broadcasts.php
- tests/_support/Helper/Acceptance/Plugin.php
- tests/acceptance/broadcasts/import/BroadcastsToPostsCest.php
- tests/acceptance/broadcasts/import/BroadcastsToPostsSettingsCest.php
As requested [here](https://twitter.com/RobbyMiles/status/1714688969445962225), adds an option to specify the WordPress Post status to assign imported ConvertKit Broadcasts to.
- `BroadcastsToPostsSettingsCest`: Updated tests to include the Post Status setting field.
- `testBroadcastsImportWithCategoryEnabled`: Test that the Post Status is set to published for each imported Broadcast
- `testBroadcastsImportWithPostStatusEnabled`: Test that the Post Status is set to private for each imported Broadcast
> Broadcasts to Posts: Add Post Status Setting

- admin/section/class-convertkit-admin-settings-broadcasts.php
- includes/class-convertkit-settings-broadcasts.php
Removes the `get_by_key` method for Broadcasts, as named methods are preferred in case array key names change in the future.
> Broadcasts to Posts: Remove `get_by_key` method

- .github/workflows/tests.yml
- admin/section/class-convertkit-settings-general.php
- includes/class-convertkit-output.php
- includes/class-convertkit-preview-output.php
- includes/class-convertkit-settings.php
- tests/acceptance/general/ActivateDeactivatePluginCest.php
- tests/acceptance/general/PluginSettingsGeneralCest.php
Based on [this ticket](https://wordpress.org/support/topic/sticky-bar-issues/) (where the customer was trying to manually add the embed script directly into their theme's code to display a sticky bar form site wide), adds a setting to optionally select a modal, slide in or sticky bar (i.e. non-inline) form to display site wide.
- `testDefaultNonInlineForm`: Tests that the non-inline form displays site wide when selected
- `testNoFormWhenNoDefaultNonInlineForm`: Tests that no non-inline form displays site wide when no option chosen
- `testChangeDefaultFormSettingAndPreviewFormLinks`: Tests that the preview functionality works for the new non-inline form setting
> Add Global Default Non-Inline Form Setting

- .github/workflows/tests.yml
- includes/class-convertkit-output.php
- tests/_support/Helper/Acceptance/CustomPostType.php
- tests/acceptance.suite.yml
- tests/acceptance/forms/general/CPTFormCest.php
Checks if the Post's type being viewed supports appending a ConvertKit Form to the content before running further logic.
Fixes [this issue](https://convertkit.atlassian.net/jira/software/c/projects/T3/boards/27?quickFilter=45&selectedIssue=T3-598), where Envira Gallery refuses to output a gallery if any output is detected (i.e. HTML comments when debugging in the ConvertKit Plugin is enabled).
- `CPTFormCest`: Checks that no options are displayed in the WordPress Administration UI on a custom Post Type, and checks that `append_form_to_content()` does not output on a custom Post Type when the `Debug` setting is enabled.
> Don't attempt to append Forms to unsupported Post Types

- resources/frontend/css/restrict-content.css
When selecting a style in a WordPress supplied block theme at `Apperance > Editor > Styles`, WordPress defines its own `!important` declarations on button padding, resulting in button layouts breaking in the Restrict Content functionality:
This doesn't happen if the default theme style is selected.
This PR resolves by doing the same - but if there's a better way to do this without using `!important`, I'm open to trying it.
> Restrict Content: Force `padding` property on buttons

- views/frontend/restrict-content/product-code.php
- views/frontend/restrict-content/product.php
- views/frontend/restrict-content/tag.php
Adds the `required` attribute to email and authorization code fields, to prevent users submitting blank data and making an unnecessary API request.
> Restrict Content: Add `required` attribute to email and code fields

- includes/class-convertkit-output-restrict-content.php
Check the nonce is valid when submitting the access code for Member Content functionality.
Remove output of error messages when the nonce is invalid, as the same `_wpnonce` field will contain a nonce for either running subscriber authentication or subscriber verification.
> Restrict Content: Verify nonce on code submission

- phpstan.neon.dist
Removes the `ignoreErrors` directive for PHPStan static analysis, introduced for WordPress 6.4, as these are resolved in 6.4.1.
> PHPStan: Remove `ignoreErrors`

- includes/blocks/class-convertkit-block.php
Replaces `FILTER_SANITIZE_STRING` (which is deprecated in PHP 8.1+) with `sanitize_text_field`, when checking if the request is from Gutenberg:
> Replace `FILTER_SANITIZE_STRING`

- admin/section/class-convertkit-admin-settings-broadcasts.php
- tests/acceptance/broadcasts/import/BroadcastsToPostsCest.php
When the scheduled event to import ConvertKit Broadcasts to WordPress Posts is running, the timestamp for the next scheduled event is `1`, resulting in incorrect output on the description:
This PR resolves by not outputting the next scheduled date/time when the event is running:
When the event is not running, the next scheduled date/time displays in the description.
- `BroadcastsToPostsCest:testBroadcastsManualImportWhenEnabled`: Test that the description does not display when using the manual import functionality.
> Broadcasts: Don't display next import date/time when event running

- admin/section/class-convertkit-admin-settings-broadcasts.php
- admin/section/class-convertkit-settings-base.php
- admin/section/class-convertkit-settings-general.php
- includes/class-convertkit-resource-forms.php
- includes/integrations/contactform7/class-convertkit-contactform7-admin-settings.php
- includes/integrations/forminator/class-convertkit-forminator-admin-settings.php
- includes/integrations/wishlist/class-convertkit-wishlist-admin-settings.php
- includes/widgets/class-ck-widget-form.php
- views/backend/post/bulk-edit.php
- views/backend/post/meta-box.php
- views/backend/post/quick-edit.php
- views/backend/setup-wizard/convertkit-setup/content-3.php
- views/backend/term/fields-add.php
- views/backend/term/fields-edit.php
Replaces multiple instances of `<select>` elements, used to select a ConvertKit Form, with two methods in the resource class:
- `get_select_field_all()`: Returns all Forms in a `<select>` dropdown
- `get_select_field_non_inline()`: Returns all non-inline Forms in a `<select>` dropdown
These will later be used (specifically `get_select_field_non_inline()`) to ensure that non-inline Forms in a `<select>` dropdown also display the inline form type (sticky bar, modal etc), where such a change can be made in one place and apply to all dropdowns.
> Resources: Forms: Add `select` dropdown methods

- .github/workflows/tests.yml
- tests/_support/Helper/Acceptance/WPBulkEdit.php
- tests/_support/Helper/Acceptance/WPClassicEditor.php
- tests/acceptance/integrations/woocommerce/WooCommerceProductFormCest.php
Improves the reliability of WooCommerce tests by:
- waiting for the WooCommerce Product publish button to be enabled before clicking it,
- scrolling the Bulk Edit view to ensure the Update button is visible and therefore can be clicked.
- removing unnecessary `wait` calls, as the above changes are a better way to check the UI before interacting with it
> Improve reliability of WooCommerce tests

- includes/class-convertkit-resource-forms.php
Resolves [this reported issue](https://convertkit.atlassian.net/jira/software/c/projects/T3/boards/27?search=wordpress&selectedIssue=T3-665), by checking if the request is for the WordPress Administration interface before deciding whether to remove the global non-inline form action, introduced in [this PR](https://github.com/ConvertKit/convertkit-wordpress/pull/591).
It's unclear why the creator can replicate this issue, given manual testing does not (see https://www.loom.com/share/e834f819d67f453a8ddc6a936b5d407e?sid=ca8029e4-6668-4669-a35c-f6cc118e032c) 
Currently no test, as no clear steps to accurately replicate.  Existing tests pass, to confirm this change does not break non-inline forms.
> Fix `output` Class Error

- includes/class-convertkit-output-restrict-content.php
Adds `convertkit_output_restrict_content_content_preview` and `convertkit_output_restrict_content_call_to_action` filter hooks, that might be useful for developers wishing the modify the preview content output and/or call to action displayed when using Member Content functionality (e.g. [this discussion](https://n7studios-workspace.slack.com/archives/C02KFR6N1GF/p1702572004086039?thread_ts=1702571153.834759&cid=C02KFR6N1GF)).
> Restrict Content: Add Filters

- tests/_support/Helper/Acceptance/ConvertKitBroadcasts.php
- tests/acceptance/broadcasts/blocks/PageBlockBroadcastsCest.php
- tests/acceptance/broadcasts/shortcodes/PageShortcodeBroadcastsCest.php
Refactors the `seeBroadcastsOutput` method by accepting an array of named key/value pairs.
> Tests: Refactor `seeBroadcastsOutput` method

- tests/_support/Helper/Acceptance/ConvertKitRestrictContent.php
- tests/acceptance/restrict-content/RestrictContentCacheCest.php
- tests/acceptance/restrict-content/RestrictContentFilterPageCest.php
- tests/acceptance/restrict-content/RestrictContentFilterPostCest.php
- tests/acceptance/restrict-content/RestrictContentProductPageCest.php
- tests/acceptance/restrict-content/RestrictContentProductPostCest.php
- tests/acceptance/restrict-content/RestrictContentSettingsCest.php
- tests/acceptance/restrict-content/RestrictContentSetupCest.php
- tests/acceptance/restrict-content/RestrictContentTagCest.php
Refactors Restrict Content helper methods by accepting an array of named key/value pairs for optional arguments.
> Tests: Refactor Restrict Content

- composer.json
- tests/acceptance.suite.yml
Updates `php-webdriver` to the latest version `1.15.1`, now that the `goog:chromeOptions` key is supported upstream (originally fixed `php-webdriver` to `1.14.x` in [this PR](https://github.com/ConvertKit/convertkit-wordpress/pull/533)).
> Tests: Update `php-webdriver`

- includes/class-convertkit-output-restrict-content.php
- resources/frontend/js/restrict-content.js
Replaces jQuery with vanilla JS for the frontend Member Content functionality.
Further PR's to follow for other frontend JS, with the goal to remove jQuery as a dependency. For sites that don't load jQuery via other Plugins / Theme, this will save loading ~ 100kb of dependencies.
> Restrict Content: Frontend: Remove jQuery

- includes/class-convertkit-output.php
- resources/frontend/js/convertkit.js
Replaces jQuery with vanilla JS for the remaining frontend functionality (tagging and storing valid subscriber ID as a cookie).
> Frontend: Remove jQuery

- includes/class-convertkit-gutenberg.php
Fixes a console warning when using the WordPress Site Editor
Follows guidance at https://developer.wordpress.org/block-editor/how-to-guides/enqueueing-assets-in-the-editor/#editor-content-scripts-and-styles which recommends to use the `enqueue_block_assets` hook with an admin check when load styles only for the editor.
We [already have an admin check](https://github.com/ConvertKit/convertkit-wordpress/blob/fix-site-editor-enqueue-console-warning/includes/class-convertkit-gutenberg.php#L188-L202) in the called `enqueue_styles` method, so this PR changes the hook from `enqueue_block_editor_assets` to `enqueue_block_assets`, as recommended in the docs above.
> Editor: Use `enqueue_block_assets` hook instead of `enqueue_block_editor_assets`

- composer.json
- includes/class-convertkit-resource-landing-pages.php
Use the latest ConvertKit WordPress Libraries, [1.4.1](https://github.com/ConvertKit/convertkit-wordpress-libraries/releases/tag/1.4.1).
Passes the debug parameter to `get_landing_page_html`, which is now supported.
> Use WordPress Libraries 1.4.1

- tests/_support/Helper/Acceptance/WPGutenberg.php
Waits for the field to be visible within the popover before interacting with it.
This prevents tests incorrectly failing due to Codeception trying to interact with the popover element before Gutenberg has positioned it:
> Tests: Fix Block Formatter Flaky Tests

- admin/section/class-convertkit-settings-base.php
- admin/section/class-convertkit-settings-general.php
- tests/acceptance/general/PluginSettingsGeneralCest.php
Remove whitespace, tabs and line ends from the API Key and Secret when entered and saved in the Plugin's settings, as reported [here](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263829243826?view=List).
Moves logic for the review request notification from the abstract `ConvertKit_Settings_Base` class to the specific `ConvertKit_Settings_General` class, which handles default forms.
- `PluginSettingsGeneralCest:testSaveValidAPICredentialsContainingSpaces`: Test that spaces contained in an API Key and Secret are removed prior to saving and testing credentials.
> Remove spaces from API Key and Secret

- admin/class-convertkit-admin-bulk-edit.php
- admin/class-convertkit-admin-quick-edit.php
- resources/backend/js/bulk-edit.js
- resources/backend/js/quick-edit.js
Replaces jQuery with vanilla JS for the backend Bulk and Quick Edit functionality.
Further PR's to follow for other backend JS, with the goal to not rely on jQuery as a dependency. jQuery is commonly used within the WordPress Administration interface, but as more screens move away from this, it's a good idea to not rely on needing jQuery.
> Bulk and Quick Edit: Backend: Remove jQuery

- admin/class-convertkit-admin-tinymce.php
- resources/backend/css/tinymce.css
- resources/backend/js/modal.js
- resources/backend/js/quicktags.js
- resources/backend/js/tinymce.js
- views/backend/tinymce/modal-field.php
Replaces jQuery with vanilla JS for the backend TinyMCE and QuickTags (Text Editor) functionality.
Replaces `wpColorPicker()` with browser native `input[type=color]` elements.
Further PR's to follow for other backend JS, with the goal to not rely on jQuery as a dependency. jQuery is commonly used within the WordPress Administration interface, but as more screens move away from this, it's a good idea to not rely on needing jQuery.
> TinyMCE and QuickTags: Backend: Remove jQuery

- admin/section/class-convertkit-admin-settings-broadcasts.php
Based on [this ticket](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263829341914?view=List), attempts to make it clear that Broadcasts must have `enabled on public feeds` enabled for them to be imported to WordPress.
> Broadcasts to Posts: Improve descriptions

- includes/integrations/forminator/class-convertkit-forminator-admin-settings.php
- includes/integrations/forminator/class-convertkit-forminator.php
- tests/acceptance/integrations/other/ForminatorCest.php
Adds options to subscribe entries to a specified ConvertKit Form when a Forminator Quiz form is submitted, as requested [here](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263829259133?view=List).
- `ForminatorCest:testSettingsForminatorQuizToConvertKitFormMapping`: Test that a Forminator Quiz is displayed in the Plugin's settings screen, and that subscribers are sent to ConvertKit when enabled.
> Forminator: Support Quizzes

- .github/workflows/tests.yml
- includes/class-convertkit-resource-forms.php
- tests/acceptance/forms/blocks/PageBlockFormCest.php
- tests/acceptance/forms/shortcodes/PageShortcodeFormCest.php
Fixes [this reported issue](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263829151905?view=List), where an inline Form's `script` embed is moved to the footer of the WordPress site when the Jetpack Boost Plugin is active and its "Defer Non-Essential JavaScript" setting is enabled, by adding a `data-jetpack-boost="ignore"` attribute to the script embed, as documented [here](https://jetpack.com/support/jetpack-boost/).
Before:
After:
- `PageBlockFormCest:testFormBlockWithJetpackBoostPlugin`: Tests that the ConvertKit Form Block is output in the correct section of the WordPress Page when the Jetpack Boost Plugin is activated and configured.
- `PageShortcodeFormCest:testFormShortcodeWithJetpackBoostPlugin`: Tests that the ConvertKit Form Shortcode is output in the …
> Jetpack Boost: Fix inline Forms output

- admin/class-convertkit-admin-tinymce.php
Removes the unused `wp-color-picker` script and style dependencies, as [this PR](https://github.com/ConvertKit/convertkit-wordpress/pull/613) uses the browser's native color picker.
> Remove unused `wp-color-picker` dependencies

- includes/class-convertkit-gutenberg.php
When using the Divi Builder, and switching from desktop to tablet or mobile views, the ability to vertically scroll disappears. Reported [here](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/conversation/12263829446216?view=List) and [here](https://drive.google.com/file/d/1fdNo5GkoxpaMrdFwHt_mRxAxm98lrkXm/view?usp=sharing).
Not loading our Plugin's `gutenberg.css` stylesheet resolves, by ensuring it only loads when in the WordPress Administration (previously, this would be loaded if in the WordPress Administration or using a third party Page Builder on the frontend site).
Given the stylesheet is only used when in the Gutenberg / block editor, it doesn't need to be loaded.
Before (no scrollbar on the right, no ability to scroll using scrollbar or mouse wheel):
After (scrollbar on the …
> Divi: Fix missing scrollbars

- admin/class-convertkit-admin-restrict-content.php
- admin/setup-wizard/class-convertkit-admin-setup-wizard-restrict-content.php
- includes/functions.php
- tests/acceptance/restrict-content/RestrictContentFilterCPTCest.php
- tests/acceptance/restrict-content/RestrictContentProductCPTCest.php
- tests/acceptance/restrict-content/RestrictContentProductPageCest.php
Adds support for Member Content functionality on public [Custom Post Types](https://developer.wordpress.org/plugins/post-types/registering-custom-post-types/), as requested [here](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263829418792?view=List) (in this example, the Recipe Custom Post Type registered through the Advanced Custom Fields Plugin has the option to restrict by Product or Tag).
Previously, the option to restrict content to a ConvertKit Tag or Product was only available on Pages and Posts
- `RestrictContentFilterCPTCest`: Test that filter options on a public Custom Post Type are displayed and work.
- `RestrictContentProductCPTCest`: Test that Restrict Content functionality works on a public Custom Post Type.
> Restrict Content: Support Public Custom Post Types

- admin/class-convertkit-admin-settings-restrict-content.php
- languages/convertkit.pot
- tests/_support/Helper/Acceptance/ConvertKitRestrictContent.php
- tests/acceptance/restrict-content/RestrictContentCacheCest.php
- tests/acceptance/restrict-content/RestrictContentProductCPTCest.php
- tests/acceptance/restrict-content/RestrictContentProductPageCest.php
- tests/acceptance/restrict-content/RestrictContentProductPostCest.php
- tests/acceptance/restrict-content/RestrictContentTagCest.php
Correct grammar for member-only content strings in field description and tests
> Fix 'Member Only' Grammar

- includes/class-convertkit-cache-minification-plugins.php
- includes/class-convertkit-output.php
- includes/class-convertkit-wp-rocket.php
- includes/class-wp-convertkit.php
- tests/acceptance/forms/general/PageLandingPageCest.php
- wp-convertkit.php
Prevents the WP-Rocket caching and minification Plugin from attempting to cache local and external CSS / JS, and attempting to lazy load images, when a Landing Page is selected for display on a WordPress Page, as reported [here](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263829294911?view=List).
It's possible to disable minification when editing an individual WordPress Page that uses a Landing Page, but these options are not always immediately visible or obvious.  This PR saves the user having to do this every time.
Before:
After:
- `PageLandingPageCest:testAddNewPageUsingDefinedLandingPageWithWPRocket`: Test that a landing page outputs as expected, with no minification or lazy loading performed by WP Rocket.
> Prevent WP Rocket caching/minifying Landing Pages

- includes/blocks/class-convertkit-block-broadcasts.php
- includes/blocks/class-convertkit-block-form-trigger.php
- includes/blocks/class-convertkit-block-form.php
- includes/blocks/class-convertkit-block-product.php
- resources/backend/css/quicktags.css
- resources/backend/css/tinymce.css
- resources/backend/js/quicktags.js
Removes an unnecessary scrollbar on Safari.
Improves calculation of QuickTags modal height by reading header and footer element heights.
Uses `white-space` instead of `text-wrap` for Safari compatibility.
Before:
After:
> TinyMCE / QuickTag Modals: Remove scrollbar on Safari

- admin/class-convertkit-admin-setup-wizard.php
- resources/backend/js/setup-wizard.js
Removes jQuery from Setup Wizard JS.
> Remove jQuery from Setup Wizard

- tests/acceptance/general/PluginSettingsGeneralCest.php
- tests/acceptance/general/PluginSetupWizardCest.php
- views/backend/setup-wizard/convertkit-setup/content-3.php
Fixes an issue where the preview form link for Pages would show the previewed form on a WordPress Post, not a Page.
- `PluginSettingsGeneralCest:testChangeDefaultFormSettingAndPreviewFormLinks`: Confirm that the Post Type being viewed for the form preview is correct.
- `PluginSetupWIzardCest: testSetupWizardFormConfigurationScreen `: Confirm that the Post Type being viewed for the form preview is correct.
> Setup Wizard: Fix `Preview Form` link for Pages

- admin/class-convertkit-admin-refresh-resources.php
- resources/backend/js/quick-edit.js
- resources/backend/js/refresh-resources.js
Removes jQuery from refresh resources JS.
> Remove jQuery from Refresh Resources

- includes/class-convertkit-post.php
Adds a `convertkit_post_settings` WordPress filter hook, to allow developers to programmatically define Post-level Plugin settings - for example, setting all Posts to a specific Member Content Tag or Product.
Adds the `post_id` value to the existing `convertkit_post_get_default_settings` WordPress filter hook.
> Add `convertkit_post_settings` hook

- admin/class-convertkit-admin-refresh-resources.php
- resources/backend/js/refresh-resources.js
- tests/acceptance/general/RefreshResourcesButtonCest.php
- views/backend/post/bulk-edit.php
- views/backend/post/meta-box.php
- views/backend/post/quick-edit.php
- views/backend/setup-wizard/convertkit-restrict-content-setup/content-2.php
Fixes issues where clicking the refresh button on the Member Content setting would result in:
- Tags and Products not being assigned to their applicable `optgroup` sections,
- `option` values not being prefixed with `tag_` or `product_`, resulting in an invalid value if the setting was changed and then saved.
- `RefreshResourcesButtonCest`: Confirm that Tags and Products are assigned to `optgroup` sections, and the value of a Tag and Product `option` is the correct format.
> Member Content: Fix Refresh Resources

- resources/frontend/css/form.css
Fixes [this issue](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263830003582?view=List) by adding `margin-left` and `margin-right` `auto` properties to inline forms, for WordPress Themes that don't automatically center inner forms / elements.
Before:
After:
Also removes the `margin-bottom` from non-inline forms, which would incorrectly shift e.g. a modal form slightly.  This property was added to ensure inline forms have similar spacing in both block and non-block themes ([original PR](https://github.com/ConvertKit/convertkit-wordpress/pull/565))
Before:
After:
> Center Inline Forms

- .github/workflows/tests.yml
- composer.json
[wp-browser 3.5](https://wpbrowser.wptestkit.dev/migration/#migrate-from-version-3-to-35) (released today) breaks tests in PHP 7.4, despite stating it's supported - specifically failing to load .env file values resulting in errors:
This PR follows docs to revert wp-browser to < `3.5`, to ensure tests pass in PHP 7.4.
Will need to review tests and a separate PR to add support for wp-browser 3.5.
> Fix Failing Tests on PHP 7.4

- includes/class-convertkit-output.php
- includes/class-convertkit-resource-forms.php
- tests/acceptance/forms/blocks/PageBlockFormCest.php
- tests/acceptance/forms/general/PageFormCest.php
- tests/acceptance/forms/shortcodes/PageShortcodeFormCest.php
Fixes [this reported issue](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263829995739?view=List), where a modal form is output twice, due to LiteSpeed Cache's `Load JS Deferred` setting duplicating the embed script.
Adding the `data-no-defer` attribute to ConvertKit Form `script` embeds resolves, similar to adding the `data-jetpack-boost` for [Jetpack Boost](https://github.com/ConvertKit/convertkit-wordpress/pull/621).
Tests in PHP 7.4 are failing due to wp-browser updating to 3.5 today, which is resolved in [this PR](https://github.com/ConvertKit/convertkit-wordpress/pull/635).
- `PageShortcodeFormCest:testFormShortcodeWithLiteSpeedCachePlugin`: Test that a single form is output when added via a shortcode with the LiteSpeed Cache Plugin enabled and its `Load …
> LiteSpeed Cache: Fix Duplicate Forms

- includes/blocks/class-convertkit-block-product.php
- includes/class-convertkit-resource-products.php
- tests/acceptance/products/PageBlockProductCest.php
- tests/acceptance/products/PageShortcodeProductCest.php
Adds an option to immediately load the checkout step in the ConvertKit Product Modal when the button is clicked.
Block:
Shortcode:
Result when button is clicked with checkout option enabled:
- `PageBlockProductCest:testProductBlockWithCheckoutParameterEnabled`: Test the Product block opens checkout step of the ConvertKit Product when the checkout option is enabled.
- `PageShortcodeProductCest:testProductShortcodeWithCheckoutParameterEnabled`: Test the Product shortcode opens checkout step of the ConvertKit Product when the checkout option is enabled.
> Products: Add checkout step option

- .distignore
- .github/workflows/tests.yml
- .gitignore
- composer.json
- tests/acceptance/general/SubscriberEmailToIDOnFormSubmitCest.php
Uses a more secure log file method, as added in our [WordPress Libraries](https://github.com/ConvertKit/convertkit-wordpress-libraries/pull/34).
> Use Secure Log in WordPress Libraries

- includes/class-convertkit-cache-plugins.php
- tests/acceptance/forms/blocks-shortcodes/PageBlockFormCest.php
- tests/acceptance/forms/blocks-shortcodes/PageShortcodeFormCest.php
- tests/acceptance/forms/post-types/PageFormCest.php
Fixes [this issue](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/conversation/12263830602836?view=List) by excluding ConvertKit Forms from Perfmatters' Plugin's `Delay JS` and `Defer JS` settings, ensuring forms and modals display.
- `PageBlockFormCest:testFormBlockWithPerfMattersPlugin`: Test that the Form <script> embed is output in the content when the Perfmatters Plugin is active and its "Delay JavaScript" setting is enabled.
- `PageShortcodeFormCest:testFormShortcodeWithPerfmattersPlugin`: Test that the Form <script> embed is output in the content when the Perfmatters Plugin is active and its "Delay JavaScript" setting is enabled.
- `PageFormCest:testAddNewPageUsingModalFormWithPerfmattersPlugin`: Test that the Modal Form is output once when the Perfmatters Plugin is active and its …
> Exclude Forms from Perfmatters `Delay JS`

- resources/frontend/css/form.css
Fixes [this issue](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263831100062?view=List), where a sticky bar form remains hidden on WordPress sites that use a high z-index property on a sticky / fixed header or menu.  This saves users having to add custom CSS to the form in ConvertKit.
Before:
After:
Existing tests passed. Visual tests performed to confirm CSS fixes.
> Set `z-index` CSS on Sticky Bar Forms

- .github/workflows/tests.yml
- includes/class-convertkit-output-restrict-content.php
- tests/acceptance/restrict-content/post-types/RestrictContentProductPageCest.php
Fixes [this issue](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263830936660?view=List), by ensuring that Member Content functionality does not run when:
- a WordPress Page has its Member Content setting defined, and
- a logged in WordPress User has the capability to edit a Page, and
- the WordPress User is editing the Page through a frontend page builder, such as Beaver Builder.
Before:
After:
`testRestrictContentWhenEditingWithFrontendPageBuilder`: Test that content is displayed when the Page is being edited in a frontend Page Builder / Editor by a logged in WordPress user who has the capability to edit the Page.
> Member Content: Display Content when using Frontend Page Builder

- admin/section/class-convertkit-settings-general.php
- tests/acceptance/general/PluginSettingsGeneralCest.php
Improves the disconnect logic when clicking `Disconnect` on the `Settings > ConvertKit` screen, by:
- requiring a nonce be specified for security,
- removing cached resources (forms, landing pages, tags, products etc) when disconnected.
- `testValidCredentials`: Test that clicking `Disconnect` removes the OAuth credentials from the Plugin settings, and that cached resources are deleted.
> v4 API: Improve Disconnect

- admin/class-convertkit-admin-category.php
- includes/class-convertkit-output.php
- includes/class-convertkit-setup.php
- includes/class-convertkit-term.php
- tests/acceptance/forms/general/CategoryFormCest.php
- tests/acceptance/forms/general/NonInlineFormCest.php
- views/backend/term/fields-add.php
- views/backend/term/fields-edit.php
- wp-convertkit.php
Presently, the Form setting at Category level is designed to output the Form on individual Posts that are assigned to a Category.
There have been a few requests for an option to also use this setting when viewing that Category's archive (a list of Posts assigned to that Category).
This PR adds an option to output the Form on the Category archives (`Display ConvertKit Form on Archive?`), with the option to choose to place the form above or below the list / grid of Posts for that Category:
- `testAddCategoryWithFormPositionBefore`: Test that a form is output before the Posts in the category archive when creating a new Category
- `testAddCategoryWithFormPositionAfter`: Test that a form is output after the Posts in the category archive when creating a new Category
- …
> Output Form on Category Archives

- .github/workflows/deploy.yml
- admin/class-convertkit-admin-notices.php
- admin/class-convertkit-admin-post.php
- admin/section/class-convertkit-settings-general.php
- admin/section/class-convertkit-settings-oauth.php
- admin/setup-wizard/class-convertkit-admin-setup-wizard-plugin.php
- composer.json
- includes/blocks/class-convertkit-block-content.php
- includes/blocks/class-convertkit-block-form.php
- includes/class-convertkit-ajax.php
- includes/class-convertkit-broadcasts-exporter.php
- includes/class-convertkit-broadcasts-importer.php
- includes/class-convertkit-output-restrict-content.php
- includes/class-convertkit-resource-creator-network-recommendations.php
- includes/class-convertkit-resource-forms.php
- includes/class-convertkit-resource-landing-pages.php
- includes/class-convertkit-resource-posts.php
- includes/class-convertkit-resource-products.php
- includes/class-convertkit-resource-tags.php
- includes/class-convertkit-setup.php
- includes/class-convertkit-subscriber.php
- includes/integrations/contactform7/class-convertkit-contactform7.php
- includes/integrations/forminator/class-convertkit-forminator.php
- includes/integrations/wishlist/class-convertkit-wishlist.php
- tests/acceptance/general/ActivateDeactivatePluginCest.php
- tests/wpunit/APITest.php
- wp-convertkit.php
We don't control the order in which our WordPress Plugins (this one, WooCommerce, Gravity Forms, WPForms etc) are updated, or which Plugins a user chooses to update.
As a result, there could be a condition where this Plugin uses the v4 API libraries, and another installed Plugin (such as WooCommerce) uses the v3 API libraries
This would result in fatal errors, as detected by [this test](tests/acceptance/general/ActivateDeactivatePluginCest.php), which was introduced to [catch these reported problems in the past](https://wordpress.org/support/topic/2-0-0-upgrade-breaking-websites/).
This PR resolves by using renamed API and Resource classes provided by [this PR](https://github.com/ConvertKit/convertkit-wordpress-libraries/pull/68) for the WordPress Libraries.
- …
> v4 API: Prevent conflicts with v3 API classes

- composer.json
- includes/class-convertkit-resource-forms.php
- includes/integrations/contactform7/class-convertkit-contactform7.php
- includes/integrations/forminator/class-convertkit-forminator.php
- includes/integrations/wishlist/class-convertkit-wishlist.php
- tests/acceptance/integrations/other/ContactForm7FormCest.php
- tests/acceptance/integrations/other/ForminatorCest.php
- tests/acceptance/integrations/wlm/WishListMemberCest.php
- tests/wpunit/ResourceFormsTest.php
Uses [this PR](https://github.com/ConvertKit/convertkit-wordpress-libraries/pull/69) and some logic to call the applicable v4 API method, depending on whether the Plugin needs to add the subscriber to a Form or Legacy Form.
- `testSettingsContactForm7ToConvertKitLegacyFormMapping`: Test that Contact Form 7 to Legacy Form subscribing/mapping works
- `testSettingsForminatorFormToConvertKitLegacyFormMapping`: Test that Forminator to Legacy Form subscribing/mapping works
- `testSettingsWishListMemberLevelToConvertKitLegacyFormMapping`: Test that WishList Member to Legacy Form subscribing/mapping works
> v4 API: Support Adding Subscribers to Legacy Forms

- includes/class-convertkit-ajax.php
- includes/class-convertkit-output.php
- resources/frontend/js/convertkit.js
- tests/_support/Helper/Acceptance/ConvertKitAPI.php
- tests/acceptance/tags/PageTagCest.php
Moves logic from the frontend (JS) to the backend (PHP) that would apply a tag to a subscriber when viewing a WordPress Page or Post with the `Add a Tag` option set.
We've had this functionality in the Plugin since 1.5.0, released 13th October 2017. However, [this reported security vulnerability](https://inky-knuckle-2c2.notion.site/ConvertKit-Plugin-is-Vulnerable-to-Missing-Authorization-1d6a790950bf4f78ae368294e6de9017?pvs=4) suggests the AJAX endpoint could be exploited to tag subscribers, if the Tag ID and Subscriber IDs are known.
Theoretically there is nothing to stop someone incrementing the `ck_subscriber_id` URL parameter to tag subscribers (e.g. https://example.com/a-page/?ck_subscriber_id). However, the attacker would need to know that a WordPress Page/Post is set to add a tag …
> Move tag subscriber logic to backend

- includes/class-convertkit-output.php
Use v4 API for the [tagging a subscriber code](https://github.com/ConvertKit/convertkit-wordpress/pull/675) introduced in 2.4.9.1
> v4 API: Tag Subscriber Logic

- admin/section/class-convertkit-settings-base.php
- admin/section/class-convertkit-settings-oauth.php
- tests/acceptance/general/PluginSettingsGeneralCest.php
Returns the `error_description` from OAuth, displaying it as an error notice on the settings screen when the user begins the OAuth flow and either:
- the user denies access to the application,
- exchanging the code for an access token fails.
- `testErrorNoticeDisplaysOnOAuthFailure`: Test that an error notice displays when the `error_description` is present in the URL, typically when the user denies access via OAuth or exchanging a code for an access token failed.
> v4 API: Show OAuth Errors

- admin/section/class-convertkit-settings-oauth.php
- composer.json
- tests/_support/Helper/Acceptance/ConvertKitAPI.php
- tests/acceptance/general/PageCest.php
- tests/acceptance/general/PluginSettingsGeneralCest.php
- tests/acceptance/general/PostCest.php
- wp-convertkit.php
Use the ConvertKit-hosted redirect URL with the `2.0` WordPress Libraries.
Updates tests that check the `state` parameter for beginning the OAuth process to its new encoded version.
> v4 API: Use ConvertKit-hosted redirect URI

- admin/section/class-convertkit-admin-settings-broadcasts.php
- admin/section/class-convertkit-settings-base.php
- admin/section/class-convertkit-settings-general.php
- admin/section/class-convertkit-settings-oauth.php
- admin/section/class-convertkit-settings-tools.php
The current notices system in the Plugin only supports predefined success / error messages, based on the `error` key.  This isn't helpful when a function (such as importing Broadcasts) returns a verbose `WP_Error`, and we want to display the precise error message instead of a generic e.g. `Broadcast import failed` (as is the case with [this ticket](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263833624191?view=List)).
This PR:
- refactors the notices system in the Plugin settings screen, to support both predefined and verbose error messages,
- moves registration of predefined success and error messages to each individual settings class,
- improves the `on_settings_screen` helper method, to better determine precisely which screen is requested (General, Tools, …
> Settings: Improve Notices and Screen Detection

- includes/class-convertkit-cache-plugins.php
- tests/acceptance/landing-pages/PageLandingPageCest.php
Resolves [this reported issue](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263833689206?view=List), where Perfmatters attempts to lazy load images and background images when a Landing Page is specified to be displayed on a WordPress Page.
Unchecking the `Lazy Loading` option on Perfmatter's settings on the WordPress Page resolves, however this PR will automatically always disable lazy loading when outputting a ConvertKit Landing Page.
Before:
After:
- `testAddNewPageUsingDefinedLandingPageWithPerfmattersPlugin`: Test that images and background image elements do not have the `perfmatters-lazy` CSS class applied to them when viewing a Landing Page.
> Perfmatters: Disable lazy loading assets on landing pages

- .github/workflows/tests.yml
- TESTING.md
- tests/_data/dump.sql
- tests/_support/Helper/Acceptance/WPGutenberg.php
- tests/_support/Helper/Acceptance/WPWidget.php
- tests/acceptance/broadcasts/import-export/BroadcastsToPostsCest.php
- tests/acceptance/forms/post-types/PageNoFormCest.php
- tests/acceptance/general/PageCest.php
- tests/acceptance/general/PostCest.php
- tests/acceptance/general/RefreshResourcesButtonCest.php
For tests, adds `wp_persisted_preferences` in the dump SQL file to disable welcome messages and tips, and removes the `disable-welcome-messages-and-tips` Plugin now that the settings are persisted directly to the database.
This replaces using the `maybeCloseGutenbergWelcomeModal`, which was proving unreliable in tests run on WordPress 6.6, resulting in the modal still displaying:
> Tests: Disable Welcome Message

- includes/functions.php
- includes/integrations/contactform7/class-convertkit-contactform7-admin-settings.php
- includes/integrations/contactform7/class-convertkit-contactform7-settings.php
- includes/integrations/contactform7/class-convertkit-contactform7.php
- tests/_support/Helper/Acceptance/ConvertKitAPI.php
- tests/acceptance/integrations/other/ContactForm7FormCest.php
- views/backend/subscription-dropdown-field.php
With the v4 API introducing the [create subscriber](https://developers.convertkit.com/v4.html#create-a-subscriber) method (without needing to subscribe to a Form), this PR:
- adds an option to create a subscriber
- renames the `None` option to `Do not subscribe`
- introduces the `convertkit_get_subscription_dropdown_field` helper method, which will be used in later PR's for other integrations, and introducing the option to subscribe to other resources, such as Tags or Sequences.
Before:
After:
- `testSettingsContactForm7WhenNoForms`: Removed this test, as Forms are no longer required to create a subscriber
- `testSettingsContactForm7DoNotSubscribeOption`: Test that no subscriber is created when the `Do not subscribe` option is selected and a Contact Form 7 Form is submitted
- …
> Contact Form 7: Add `Subscribe` option

- includes/class-convertkit-setup.php
- includes/integrations/forminator/class-convertkit-forminator-admin-settings.php
- includes/integrations/forminator/class-convertkit-forminator-settings.php
- includes/integrations/forminator/class-convertkit-forminator.php
- tests/acceptance/integrations/other/ForminatorCest.php
Matching the Contact Form 7 PR's, this PR:
- Adds a `Subscribe` option
- Renames `None` to `(Do not subscribe)`
- Adds options to add a Tag or Sequence to the subscriber
- Migrates settings data to use the `form:` prefix on Plugin upgrade
- `testSettingsForminatorFormToConvertKitTagMapping`: Test that saving a Forminator Form to ConvertKit Tag Mapping works.
- `testSettingsForminatorFormToConvertKitSequenceMapping`: Test that saving a Forminator Form to ConvertKit Sequence Mapping works.
- `testSettingsForminatorFormDoNotSubscribeOption`: Test that setting a Forminator Form to the '(Do not subscribe)' option works.
- `testSettingsForminatorFormSubscribeOption`: Test that setting a Forminator Form to the 'Subscribe' option works.
- `testSettingsForminatorQuizToConvertKitTagMapping`: Test …
> Forminator: Option to Subscribe; add Tag / Sequence to Subscriber

- tests/acceptance/integrations/other/ForminatorCest.php
Refactors Forminator Form Tests to remove repetitive code.
> Refactor Forminator Form Tests

- includes/integrations/contactform7/class-convertkit-contactform7-admin-settings.php
- includes/integrations/forminator/class-convertkit-forminator-admin-settings.php
- views/backend/setup-wizard/footer.php
Updates description text for Contact Form 7 and Forminator Form integration settings screens.
Removes errant `echo` statements, as `esc_html_e` will echo anyway.
> Update Form Integration Descriptions

- includes/class-convertkit-setup.php
- tests/acceptance/integrations/other/ContactForm7FormCest.php
- tests/acceptance/integrations/other/ForminatorCest.php
- tests/acceptance/integrations/wlm/WishListMemberCest.php
Contact Form 7, Forminator and WishList Member would have their `None` settings saved as `default`.
2.4.9 added a fix to the settings forms for the three integrations by changing the value of 'None' from `default` to a blank string:
https://github.com/ConvertKit/convertkit-wordpress/pull/655
However, no tests or automatic changes to existing saved settings were included, resulting in [this reported error](https://wordpress.org/support/topic/php-fatal-error-440/#post-17928655), where 'default' is still present in the settings:
```
[02-Aug-2024 05:23:16 UTC] PHP Fatal error: Uncaught TypeError: ConvertKit_API_V4::add_subscriber_to_form(): Argument #1 ($form_id) must be of type int, string given, called in /private/wp-content/plugins/convertkit/vendor/convertkit/convertkit-wordpress-libraries …
```
> Fix Third Party Form Integrations `default` value

- includes/class-convertkit-setup.php
- includes/functions.php
- includes/integrations/contactform7/class-convertkit-contactform7-admin-settings.php
- includes/integrations/forminator/class-convertkit-forminator-admin-settings.php
- includes/integrations/wishlist/class-convertkit-wishlist-admin-settings.php
- includes/integrations/wishlist/class-convertkit-wishlist-settings.php
- includes/integrations/wishlist/class-convertkit-wishlist.php
- tests/_support/Helper/Acceptance/ConvertKitAPI.php
- tests/acceptance/integrations/wlm/WishListMemberCest.php
- views/backend/subscription-dropdown-field.php
- wp-convertkit.php
Currently, the WLM integration provides the option to:
- Subscribe a user to a ConvertKit Form when added to a WLM Membership Level
- Tag a subscriber in ConvertKit when removed from a WLM Membership Level
These options seem inconsistent, so this PR resolves by:
- Adding options to only subscribe, or subscribe and add a Form, Tag or Sequence when added to a WLM Membership Level, bringing this in line with the Contact Form 7 + Forminator options
- Adding options to unsubscribe, or assign a Form, Tag or Sequence when removed from a WLM Membership Level, bringing this in line with the Contact Form 7 + Forminator options
- Renaming the `ConvertKit Form` table heading to `Assign to member`
- Renaming the `Unsubscribe Action` table heading to `Remove from member`
- Rename the settings key from …
> WishList Member: Update options

- admin/class-convertkit-admin-post.php
- admin/class-convertkit-admin-restrict-content.php
Adds a new `convertkit_admin_post_register_add_new_buttons` filter hook for the Plugin to register buttons (i.e. Add New Member Content, [Add New Landing Page](https://github.com/ConvertKit/convertkit-wordpress/pull/697)).
> Register Filter for `Add New` buttons

- includes/integrations/contactform7/class-convertkit-contactform7.php
- includes/integrations/forminator/class-convertkit-forminator.php
- includes/integrations/wishlist/class-convertkit-wishlist.php
- tests/_support/Helper/Acceptance/ConvertKitAPI.php
Fixes [this reported issue](https://linear.app/kit/issue/PLAT-2027/platform-v4-api-issue-post-to-create-a-subscriber-doesnt-appear-to), by calling `create_subscriber` with `state` = `inactive` when a Form is selected as the resource to assign to the subscriber in Contact Form 7, Forminator and WishList Member.
> Create subscriber with `inactive` state when a Form option is selected

- admin/class-convertkit-admin-landing-page.php
- admin/class-convertkit-admin-post.php
- admin/class-convertkit-admin-restrict-content.php
- resources/backend/css/wp-list-table-buttons.css
- resources/backend/js/wp-list-table-buttons.js
- tests/acceptance/landing-pages/PageLandingPageSetupWizardCest.php
- tests/acceptance/restrict-content/general/RestrictContentSetupCest.php
Introduces an `Add New` dropdown button for setup wizards registered in WordPress.  This allows easier addition of possible future setup / configuration wizards without cluttering the UI.
Before:
After:
Updated tests to interact with the new dropdown.
> Change `Add New` buttons to dropdown

- includes/integrations/divi/class-convertkit-divi-module.php
Displays the Form icon on the Divi module:
> Divi: Display Form Icon

- includes/blocks/class-convertkit-block-form.php
- includes/integrations/divi/class-convertkit-divi-module-form.php
- includes/integrations/divi/scripts/builder-bundle.min.js
- tests/acceptance/integrations/other/DiviFormCest.php
Displays a notice on the Divi Form Module, instructing the user what to do when either:
- the ConvertKit Plugin isn't connected via OAuth,
- no Forms exist in ConvertKit
- `testFormModuleInFrontendEditorWhenNoCredentials`: Test that the expected message displays in the module when the Plugin is not connected via OAuth
- `testFormModuleInFrontendEditorWhenNoForms`: Test that the expected message displays in the module when the ConvertKit account has no Forms.
> Divi: Display notice for no credentials / forms

- includes/blocks/class-convertkit-block-product.php
- includes/integrations/divi/class-convertkit-divi-module-product.php
- includes/integrations/divi/class-convertkit-divi-module.php
- includes/integrations/divi/loader.php
- includes/integrations/divi/scripts/builder-bundle.min.js
- tests/_support/Helper/Acceptance/ConvertKitPlugin.php
- tests/acceptance/integrations/other/DiviProductCest.php
Registers the ConvertKit Product block as a module in the Divi Builder, making it easier to add a ConvertKit Product button.
- `DiviProductCest`: Test that adding the ConvertKit Product module to Divi works.
> Divi: Add Product Module

- includes/blocks/class-convertkit-block-broadcasts.php
- includes/blocks/class-convertkit-block-form-trigger.php
- includes/integrations/divi/class-convertkit-divi-module-broadcasts.php
- includes/integrations/divi/class-convertkit-divi-module-form-trigger.php
- includes/integrations/divi/class-convertkit-divi-module.php
- includes/integrations/divi/loader.php
- includes/integrations/divi/scripts/builder-bundle.min.js
- tests/acceptance/integrations/other/DiviBroadcastsCest.php
- tests/acceptance/integrations/other/DiviFormCest.php
- tests/acceptance/integrations/other/DiviFormTriggerCest.php
- tests/acceptance/integrations/other/DiviProductCest.php
Registers the ConvertKit Form Trigger block as a module in the Divi Builder, making it easier to add ConvertKit Form Trigger buttons for modal, sticky bar and slide in forms.
- `DiviFormTriggerCest`: Test that adding the ConvertKit Form Trigger module to Divi works.
> Divi: Add Form Trigger Module

- composer.json
- tests/acceptance/landing-pages/PageLandingPageCest.php
Fixes [this reported issue](https://linear.app/kit/issue/BCDC-3182/bcdc-embedded-landing-pages-on-wordpress-do-not-redirect-when-someone), where a Landing Page setup to redirect, and embedded in WordPress, won't redirect to the thank you page URL.
Uses [this PR](https://github.com/ConvertKit/convertkit-wordpress-libraries/pull/77) to exclude rocket-loader.min.js, which was the cause of this.
- `testAddNewPageUsingDefinedLandingPage`: Updated test to complete subscription form, submit and observe that the redirect configured in ConvertKit is honored.
> Fix Landing Page Redirect

- resources/frontend/js/convertkit.js
- tests/acceptance/general/SubscriberIDURLCest.php
Fixes [this reported issue](https://n7studios-workspace.slack.com/archives/C02KFR6N1GF/p1725892885330669) where additional URL parameters (such as UTM params) would be incorrectly stripped from the URL by the Plugin's JS.
- `SubscriberIDURLCest`: Test that the `ck_subscriber_id` parameter and its value are correctly removed, retaining other parameters before and after it.
> Correctly remove `ck_subscriber_id` from URL

- includes/class-convertkit-subscriber.php
- tests/acceptance/general/SubscriberIDURLCest.php
Fixes [this reported issue](https://linear.app/kit/issue/BCDC-3228/bcdc-wordpress-php-error-when-ck-subscriber-id-is-missing), where a non-numeric or blank `ck_subscriber_id` query parameter results in an uncaught TypeError:
- `testSubscriberIDRemovedFromURL`: Added tests to confirm no errors on screen when a non-numeric or blank `ck_subscriber_id` is passed.
> Fix Fatal Error when `ck_subscriber_id` in query param is non-numeric

- admin/section/class-convertkit-settings-general.php
- includes/class-convertkit-output.php
- includes/class-convertkit-settings.php
- tests/_support/Helper/Acceptance/ConvertKitForms.php
- tests/acceptance/forms/blocks-shortcodes/PageBlockFormCest.php
- tests/acceptance/forms/blocks-shortcodes/PageShortcodeFormCest.php
- tests/acceptance/forms/general/CategoryFormCest.php
- tests/acceptance/forms/post-types/CPTFormCest.php
- tests/acceptance/forms/post-types/PageFormCest.php
- tests/acceptance/forms/post-types/PostFormCest.php
- tests/acceptance/general/PluginSettingsGeneralCest.php
- tests/acceptance/general/PluginSetupWizardCest.php
- tests/acceptance/general/PostCest.php
- tests/acceptance/integrations/other/DiviFormCest.php
- tests/acceptance/integrations/other/ElementorFormCest.php
- tests/acceptance/integrations/woocommerce/WooCommerceProductFormCest.php
Adds an option based on [these](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263831661911?view=List) [tickets](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263830004297?view=List) to specify whether the Default Form specified for a given Post Type should be added before or after the Page, Post or Custom Post Type's content:
Further PR's to follow to add additional position options (such as after a given number of paragraphs).
- `testAddNewPageUsingDefaultFormBeforeContent`: Test that adding a new WordPress Page using the default form set to display before the content works.
- `testAddNewPostUsingDefaultFormBeforeContent`: Test that adding a new WordPress Post using the default form set to display before the content works.
- …
> Settings: Define Default Form Position

- admin/class-convertkit-admin-bulk-edit.php
- admin/class-convertkit-admin-category.php
- admin/class-convertkit-admin-notices.php
- admin/class-convertkit-admin-post.php
- admin/class-convertkit-admin-quick-edit.php
- admin/class-convertkit-admin-restrict-content.php
- includes/functions.php
- resources/frontend/js/convertkit.js
Fixes [these reported](https://wordpress.org/support/topic/some-error-log-registratios/#post-18030337) JS and PHP warnings.
Wraps `get_current_screen` in a helper method to return `false` if the function is unavailable or returns null.  Returns the requested `WP_Screen` property.  This should catch other instances where warnings may occur that we haven't yet caught.
> Fix `get_current_screen` PHP Warnings

- admin/section/class-convertkit-settings-general.php
- includes/class-convertkit-output.php
- tests/_support/Helper/Acceptance/ConvertKitForms.php
- tests/acceptance/forms/post-types/CPTFormCest.php
- tests/acceptance/forms/post-types/PageFormCest.php
- tests/acceptance/forms/post-types/PostFormCest.php
- tests/acceptance/general/PluginSettingsGeneralCest.php
Adds a `Before and after content` option when defining default form positions in the Plugin's settings:
- `testAddNewCPTUsingDefaultFormBeforeAndAfterContent`: Test that the form displays before and after the content on a Custom Post Type
- `testAddNewPageUsingDefaultFormBeforeAndAfterContent`: Test that the form displays before and after the content on a Page
- `testAddNewPostUsingDefaultFormBeforeAndAfterContent`: Test that the form displays before and after the content on a Post
> Define Default Form Position: Add `Before and after content` option

- resources/frontend/js/convertkit.js
- tests/acceptance/general/SubscriberIDURLCest.php
Fixes [this reported issue](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263835123906?view=List), where the query separator would be appended to any URL when the `ck_subscriber_id` cookie is set, caused by using `charAt` in [this PR](https://github.com/ConvertKit/convertkit-wordpress/pull/709).
Updates variable names to make clearer what the JS function does.
- `testQuerySeparatorNotAppendedToURLWhenCookieExists`: Confirm no query separator is appended to a URL when a `ck_subscriber_id` cookie is set.
> Query separator incorrectly appended to URLs when `ck_subscriber_id` cookie set

- admin/section/class-convertkit-settings-general.php
Fixes [this reported issue](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/conversation/12263835120526?view=List), where the `ConvertKit_Resource_Forms` class is not initialized within the `non_inline_form_callback` method.
This class is initialized in the `default_form_callback` method, which is typically called earlier in the request when loading the settings UI.  However, if `convertkit_get_supported_post_types` are filtered to exclude all Post Types, then this initialization won't happen, resulting in the reported error.
> Initialize `ConvertKit_Resource_Forms` correctly in Settings UI

- composer.json
- tests/_support/Helper/Acceptance/ConvertKitForms.php
- tests/acceptance/landing-pages/PageLandingPageCest.php
- tests/acceptance/landing-pages/PageLandingPageSetupWizardCest.php
Uses 2.0.3 of the WordPress Libraries.
Updates landing page tests to confirm the correct `<html>` tag exists, now that landing pages are parsed correctly.
> Use WordPress Libraries 2.0.3

- admin/section/class-convertkit-settings-general.php
- views/backend/settings/tools.php
Changes button colors for `Disconnect` and `Clear log` to match Kit's secondary button styles.
Removes the `code` tag for the account name.
This matches the Kit for WooCommerce Plugin styling.
Before:
After:
> Update Secondary Button Colors

- admin/section/class-convertkit-admin-settings-broadcasts.php
- admin/section/class-convertkit-settings-base.php
- admin/section/class-convertkit-settings-general.php
- includes/class-convertkit-output.php
- includes/class-convertkit-settings.php
- resources/backend/js/settings-conditional-display.js
- tests/_support/Helper/Acceptance/ConvertKitForms.php
- tests/acceptance/forms/post-types/CPTFormCest.php
- tests/acceptance/forms/post-types/PageFormCest.php
- tests/acceptance/forms/post-types/PostFormCest.php
- tests/acceptance/general/PluginSettingsGeneralCest.php
Adds an `After element` option when defining default form positions in the Plugin's settings, with an option to choose the element and the number of elements after which to insert the form.
Support for elements other than paragraphs to follow in future PR's.
Settings screen:
If the setting is not `After element`, the conditional options will not be displayed:
Example output of the form after a paragraph:
- `testChangeDefaultFormPositionAfterElementSetting `: Test that no PHP errors or notices are displayed on the Plugin's Setting screen, when the Default Form Position setting for Pages and Posts are changed to `After element`
- `testAddNewCPTUsingDefaultFormAfterElement `: Test that the Default Form specified in the Plugin Settings works when creating and viewing a new WordPress CPT, and …
> Define Default Form Position: Add `After element` option

- admin/section/class-convertkit-settings-general.php
- tests/_support/Helper/Acceptance/ConvertKitForms.php
- tests/_support/Helper/Acceptance/WPGutenberg.php
- tests/acceptance/forms/post-types/CPTFormCest.php
- tests/acceptance/forms/post-types/PageFormCest.php
- tests/acceptance/forms/post-types/PostFormCest.php
Extends https://github.com/ConvertKit/convertkit-wordpress/pull/723 to add support for `h2` through `h6` elements to position the default form after:
The exclusion of `h1` is deliberate:
- For SEO, Pages should really only have a single `h1` element,
- Most Themes will output the Page / Post's title as a `h1` element. Including it as an option here may result in confusion as it will not be counted as the first element.
Existing tests are renamed to identify what they test (i.e. paragraphs).
Added the `addGutenbergPageToDatabase` test helper, to create a WordPress Page / Post / CPT with placeholder content comprising of a number of different elements for the tests to ensure the form is appended to the correct element.
- `testAddNewPageUsingDefaultFormAfterHeadingElement`: Test that the …
> Support for Headings in `After Element` Form Positioning

- admin/section/class-convertkit-admin-settings-broadcasts.php
Adds a notice in the Broadcasts settings of the Plugin if the `DISABLE_WP_CRON` constant is detected. This was the reason for [this issue](https://linear.app/kit/issue/BCDC-3262/bcdc-latest-2-broadcast-posts-not-appearing-on-creators-wordpress-page), where broadcasts were not importing for the creator.
The WordPress Cron system is essential for importing broadcasts. Normally, it's triggered by site activity, such as visitors or user logins. However, some web hosts disable this default behavior by specifying the `DISABLE_WP_CRON` constant, opting instead to trigger it via crontab or similar methods (see more: https://help.dreamhost.com/hc/en-us/articles/360048323291-Disabling-WP-CRON-to-Improve-Overall-Site-Performance).
The notice prompts creators to either ensure that their host is …
> Broadcasts: `DISABLE_WP_CRON` notice

- readme.txt
Updates the readme.txt tags to include `block`, which appears to be a requirement for the Plugin to be listed in the [block directory](https://wordpress.org/documentation/article/block-directory/):
There's a limit of 5 tags in the WordPress Plugin directory, so this PR removes `newsletter` and `subscribers` in favor of `block` and `form`, to see if this increases visibility in the block directory.  This can always be reverted at a later date, similar to our periodic optimizations to the readme file.
No changes to code, so no tests performed.
> Update tags to include Plugin in Block Directory

- includes/class-convertkit-broadcasts-importer.php
- tests/acceptance/broadcasts/import-export/BroadcastsToPostsCest.php
Attempting to vote on a poll that is included in a Broadcast imported to a WordPress Post results in an error:
This PR excludes polls from import.
- Updated tests to confirm the table with CSS class `ck-poll` isn't included in the created WordPress Post.
> Broadcasts: Import: Exclude polls

- admin/section/class-convertkit-settings-general.php
- tests/acceptance/general/PluginSettingsGeneralCest.php
Only displays the `Form Position` setting if Forms exist on the Kit account.
Before:
After:
- `testSettingsScreenWhenNoResources`: Test that Form setting options are not displayed when no Forms exist.
> Settings: Only display Form Settings if Forms exist

- includes/class-convertkit-output.php
- includes/class-convertkit-settings.php
- tests/_support/Helper/Acceptance/ConvertKitPlugin.php
- tests/acceptance/forms/blocks-shortcodes/PageBlockFormCest.php
- tests/acceptance/forms/blocks-shortcodes/PageShortcodeFormCest.php
- tests/acceptance/forms/general/EditFormLinkCest.php
- tests/acceptance/forms/general/WidgetFormCest.php
- tests/acceptance/forms/post-types/CPTFormCest.php
- tests/acceptance/forms/post-types/PageFormCest.php
- tests/acceptance/forms/post-types/PostFormCest.php
- tests/acceptance/integrations/other/DiviFormCest.php
- tests/acceptance/integrations/other/ElementorFormCest.php
Fixes [this reported issue](https://linear.app/kit/issue/BCDC-3064/tag-not-being-applies-when-subscribers-click-to-wp-site), due to the `maybe_tag_subscriber` method checking for an API Key and Secret, instead of an Access and Refresh Token.
There are no other calls to `has_api_key_and_secret`, and this PR sets the `has_api_key_and_secret` method to deprecated, with it calling `has_access_and_refresh_token` and logging/displaying (depending on WordPress configuration) a notice for developers who might still be relying on this method:
In the future, it's best to remove the `has_api_key_and_secret` method entirely, now it's no longer used. 
Tests failed to pick this up, as all tests would pre-populate the Plugin settings data in the database with an API Key and Secret, therefore ensuring …
> Fix `Add Tag` Functionality

- admin/class-convertkit-admin-settings.php
- admin/section/class-convertkit-admin-settings-broadcasts.php
- includes/class-convertkit-broadcasts-importer.php
- includes/class-convertkit-settings-broadcasts.php
- tests/_support/Helper/Acceptance/ConvertKitBroadcasts.php
- tests/acceptance/broadcasts/import-export/BroadcastsToPostsCest.php
- tests/acceptance/broadcasts/import-export/BroadcastsToPostsSettingsCest.php
Adds [this requested feature](https://linear.app/kit/issue/BCDC-3262/bcdc-latest-2-broadcast-posts-not-appearing-on-creators-wordpress-page#comment-35d197dc) by including an option to save a Broadcast's images to WordPress when importing the Broadcast to a WordPress Post.
This won't import non-creator uploaded images, such as icons for links and social links.
- `testBroadcastsImportWithImportImagesEnabled`: Tests that Broadcasts import with inline images copied to WordPress when the Import Images option is enabled.
> Broadcasts: Import Images

- includes/class-convertkit-broadcasts-importer.php
- tests/acceptance/broadcasts/import-export/BroadcastsToPostsCest.php
- tests/wpunit/BroadcastsImportTest.php
[As requested](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/conversation/12263835305931), if the Broadcast's title matches a H1 through H6 in the Broadcast's content, removes the heading in the content, because the Broadcast's title is always stored as the WordPress Post title, and a Post title is required.
Kit:
WordPress:
- `BroadcastsImportTest`: Updated assertion to confirm no H1 is included in the `HTML Template Test` broadcast, which contains the same title in both the Broadcast's title and H1.
> Broadcasts Importer: Remove Duplicate Title in Content

- includes/class-convertkit-broadcasts-importer.php
- tests/wpunit/BroadcastsImportTest.php
As requested here, don't strip the `figure` and `figcaption` elements when importing a Broadcast, to ensure the caption isn't detached from the image.
- `BroadcastsImportTest`: Assert that the `figure` and `figcaption` elements are retained on import.
> Broadcasts Importer: Retain `figure` and `figcaption`

- includes/class-convertkit-output.php
- includes/class-convertkit-term.php
- tests/acceptance/forms/general/CategoryFormCest.php
- tests/acceptance/general/RefreshResourcesButtonCest.php
- views/backend/term/fields-add.php
- views/backend/term/fields-edit.php
Adds a `None` option [as requested here](https://n7studios-workspace.slack.com/archives/C02KFR6N1GF/p1732020639109099), matching how Post and Plugin level settings operate, to not display a Form should a Post be assigned to the given Category.
- `testAddCategoryWithNoneFormSetting`: Test that adding a Category with the Form setting = `None` results in no Form being displayed when viewing a Post.
- `testEditCategoryWithNoneFormSetting`: Test that editing a Category with the Form setting = `None` results in no Form being displayed when viewing a Post.
> Categories: Forms: Add `None` Option

- includes/class-convertkit-output.php
- includes/class-convertkit-setup.php
- includes/class-convertkit-term.php
- tests/acceptance/forms/general/CategoryFormCest.php
- tests/acceptance/general/RefreshResourcesButtonCest.php
- views/backend/term/fields-add.php
- views/backend/term/fields-edit.php
- wp-convertkit.php
When defining the Form setting on Pages or Posts, key/value pairs have always been:
| Value  | Setting Label |
| ------------- | ------------- |
| -1  | Default (i.e. inherit from Plugin Settings)  |
| 0  | None (i.e. don't display a Form)  |
| Form ID (integer)  | Form Names (i.e. display the specified Form) |
When defining the Form setting on a Category, key/value pairs were:
| Value  | Setting Label |
| ------------- | ------------- |
| default  | None  |
| Form ID (integer)  | Form Names (i.e. display the specified Form) |
The 'None' label was misleading, because selecting this choice would display the Form specified at Post or Plugin level.  [This PR](https://github.com/ConvertKit/convertkit-wordpress/pull/295) changed the Form setting value and its label on a Category to better …
> Categories: Forms: Change 'Default' value from -1 to 0

- includes/class-convertkit-setup.php
- includes/class-wp-convertkit.php
- tests/_support/Helper/Acceptance/WPCron.php
- tests/acceptance/broadcasts/import-export/BroadcastsToPostsCest.php
- tests/wpunit/ResourcePostsTest.php
Fixes the below reported issues, by ensuring that the Broadcast to Posts WordPress Cron Event exists, should it be deleted by a third party Plugin.
https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263836210039?view=List
https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263835305931?view=List
https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263835371174?view=List
https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263835396821?view=List
In turn, the 'Import Now' button will be displayed, and Broadcasts will import to WordPress Posts )if the functionality is enabled in the Plugin's settings).
- `testBroadcastsCronEventRecreatedWhenDeleted`: Acceptance test to confirm the Cron event is recreated …
> Automatically Reschedule Cron Events

- .github/workflows/tests.yml
- includes/blocks/class-convertkit-block-form.php
- includes/blocks/class-convertkit-block.php
- includes/class-convertkit-output.php
- tests/_support/Helper/Acceptance/WPCron.php
- tests/_support/Helper/Acceptance/WPGutenberg.php
- tests/acceptance/forms/blocks-shortcodes/PageBlockFormCest.php
- tests/acceptance/forms/blocks-shortcodes/PageShortcodeFormCest.php
- tests/acceptance/forms/post-types/CPTFormCest.php
- tests/acceptance/forms/post-types/PageFormCest.php
- tests/acceptance/forms/post-types/PostFormCest.php
- tests/acceptance/integrations/other/DiviBroadcastsCest.php
- tests/acceptance/integrations/other/DiviFormCest.php
- tests/acceptance/integrations/other/DiviFormTriggerCest.php
- tests/acceptance/integrations/other/DiviProductCest.php
- tests/acceptance/landing-pages/PageLandingPageCest.php
WordPress 6.7 displays a PHP notice if a Theme or Plugin calls `load_plugin_textdomain` too early i.e. before the WordPress `init` hook and WP_DEBUG is enabled.
This Plugin's tests run with WP_DEBUG enabled, and due to activating third party Plugins to run specific tests against, we get errors:
This PR resolves by suppressing the `_load_textdomain_just_in_time` PHP notice in our automated testing via [use of a Plugin](https://gist.github.com/n7studios/cec76acd6652ab1cc74f8ca6b8cbba0f), whilst allowing other notices to still display and be detected.
Also fixes cron tests failing due to a change in the admin UI URL in [WP Crontrol 1.17.1](https://wordpress.org/plugins/wp-crontrol/), released November 23rd.
> Tests: Fix `_load_textdomain_just_in_time` PHP Notice

- includes/class-convertkit-output.php
- tests/acceptance/forms/post-types/CPTFormCest.php
- tests/acceptance/forms/post-types/PageFormCest.php
- tests/acceptance/forms/post-types/PostFormCest.php
This [previous PR](https://github.com/Kit/convertkit-wordpress/pull/745) resolved an issue with character encoding when injecting a Form after the nth element (heading, paragraph, image etc).
This resulted in an errant `meta` tag being left behind in the Post's content:
This PR resolves by removing the `meta` tag.
Updated tests to confirm meta tag removal when injecting a Form after an element.
> Character Encoding: Remove `meta` tag after injecting Form

- resources/frontend/js/convertkit.js
Prior to `1.9.6`, JS functionality existed to set a cookie if:
1. A `ck_subscriber_id` query parameter was included in the URL (i.e. a subscriber clicked a link in a Broadcast), and
2. The WordPress Page had the `Add a tag` setting configured to assign the subscriber to a tag.
Since then, several updates have moved this functionality to the server side:
- #371: Server side validation and storing of a subscriber ID as a cookie
- #408: Moves the logic above to an earlier point in the request cycle
- #675: Moves JS client side tagging logic to server side, resolving a reported security issue
As a result, the JS client-side function `convertStoreSubscriberIDInCookie` is still being called, triggering the `convertkit_store_subscriber_id_in_cookie` AJAX endpoint whenever a subscriber ID exists. …
> Remove JS `convertStoreSubscriberIDInCookie` function

- .github/workflows/coding-standards.yml
- admin/class-convertkit-admin-cache-plugins.php
- admin/class-convertkit-admin-tinymce.php
- admin/section/class-convertkit-admin-settings-broadcasts.php
- admin/section/class-convertkit-settings-general.php
- admin/section/class-convertkit-settings-tools.php
- composer.json
- includes/blocks/class-convertkit-block.php
- includes/class-convertkit-broadcasts-importer.php
- includes/class-convertkit-gutenberg.php
- includes/class-convertkit-resource-forms.php
- includes/class-convertkit-shortcodes.php
- includes/functions.php
- includes/integrations/contactform7/class-convertkit-contactform7-admin-settings.php
- includes/integrations/divi/class-convertkit-divi-module.php
- includes/integrations/elementor/class-convertkit-elementor-widget.php
- includes/integrations/elementor/class-convertkit-elementor.php
- phpstan.neon.dist
- phpstan.neon.example
Runs static analysis using the latest [2.0](https://github.com/phpstan/phpstan/blob/2.0.x/UPGRADING.md) version of PHPStan when tests are performed on PHP 7.4 and higher, which is the minimum supported version.
PHPStan 1.x will run on tests using PHP < 7.4.
> Tests: Use PHPStan 2.0

- includes/class-convertkit-output.php
- tests/acceptance/forms/post-types/CPTFormCest.php
- tests/acceptance/forms/post-types/PageFormCest.php
- tests/acceptance/forms/post-types/PostFormCest.php
Fixes [this reported issue](https://linear.app/kit/issue/WP-7/bcdc-wordpress-p3-critical-error-message-when-modal-form-set-on) when:
- a non-inline Form is specified at Plugin, Post or Category level, and
- the `Form Position` setting = `After element`
This was caused due to the `$form` variable being empty (due to the Plugin correctly deferring non-inline Forms to the footer of the site), and DOMDocument attempting to load a blank string as a result.
```
Warning: DOMDocument::loadHTML(): Empty string supplied as input in /home/thevanab/public_html/wp-content/plugins/convertkit/includes/class-convertkit-output.php on line 424
Fatal error: Uncaught TypeError: Argument 1 passed to DOMDocument::importNode() must be an instance of DOMNode, null given in …
```
> Fix `DOMDocument` Fatal Error when non-inline Form specified

- tests/acceptance/forms/blocks-shortcodes/PageShortcodeFormCest.php
Looks like legacy forms HTML now returns a form action of `api.kit.com`, instead of `api.convertkit.com`.
> Tests: Update Legacy Form action URL from `convertkit.com` to `kit.com`

- admin/class-convertkit-admin-cache-plugins.php
- admin/class-convertkit-admin-settings-restrict-content.php
- includes/class-convertkit-cache-plugins.php
- tests/acceptance/restrict-content/general/RestrictContentCacheCest.php
The notice added by [this PR](https://github.com/Kit/convertkit-wordpress/pull/465) is a bit confusing for some creators, who think they still need to configure something when looking at other issues, such as form display - even if their caching Plugin is configured.
We already have conditional notices displayed on steps to take should a creator use a caching Plugin that we cannot automatically configure ([this PR](https://github.com/Kit/convertkit-wordpress/pull/469)).
This PR also includes automatic configuration for WP Rocket.
`testRestrictContentWPRocketCache`: Test that Member Content is excluded from caching when WP Rocket is active and the subscriber logs in.
> Update `ck_subscriber_id` Notice

- resources/frontend/js/convertkit.js
- tests/acceptance/general/SubscriberIDURLCest.php
Fixes [this reported issue](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263837148171?view=List), where the `convertKitRemoveSubscriberIDFromURL` method would not include any hash included in the URL.
This bug was introduced in [this PR](https://github.com/Kit/convertkit-wordpress/pull/709/) (which introduced using `searchParams` to fetch URL query parameters, as a more reliable method to detect a `ck_subscriber_id` and other query parameters, but failed to fetch the URL hash), instead of the previous behaviour of grabbing the entire URL string.
- `SubscriberIDURLCest`: Added tests and checks to existing tests to confirm the hash is included when specified, and no hash is appended if not in the URL.
> Retain Hash when included in URL

- tests/acceptance/restrict-content/general/RestrictContentTagCest.php
This test fails as it's been run many times through GitHub actions, and Google rightly thinks the test email addresses are spammy.
Fixes the test by deliberately lowering the minimum score setting.
> Fix reCAPTCHA Test

- composer.json
- includes/integrations/contactform7/class-convertkit-contactform7.php
- includes/integrations/forminator/class-convertkit-forminator.php
- tests/_support/Helper/Acceptance/ConvertKitAPI.php
- tests/acceptance/integrations/other/ContactForm7FormCest.php
- tests/acceptance/integrations/other/ForminatorCest.php
Specifies the URL a Contact Form 7 or Forminator Form is embedded as the `referrer` parameter, when configured to subscribe the email address to a Kit Form.
- `testSettingsContactForm7ToConvertKitFormMapping`: Updated test to confirm the subscriber is subscribed to the Kit Form, and has the expected referrer URL.
- `testSettingsForminatorFormToConvertKitFormMapping`: Updated test to confirm the subscriber is subscribed to the Kit Form, and has the expected referrer URL.
> Form Subscribe: Add `referrer` support

- admin/class-convertkit-admin-settings-restrict-content.php
- admin/section/class-convertkit-admin-settings-broadcasts.php
- admin/section/class-convertkit-settings-base.php
- admin/section/class-convertkit-settings-general.php
- admin/section/class-convertkit-settings-oauth.php
- admin/section/class-convertkit-settings-tools.php
- includes/integrations/contactform7/class-convertkit-contactform7-admin-settings.php
- includes/integrations/forminator/class-convertkit-forminator-admin-settings.php
- includes/integrations/wishlist/class-convertkit-wishlist-admin-settings.php
- resources/backend/css/settings.css
Improves the UX of the settings screens by grouping relative settings together.
Before:
After:
> Group Settings in UI

- includes/blocks/class-convertkit-block-form-trigger.php
- includes/blocks/class-convertkit-block-form.php
- includes/blocks/class-convertkit-block-product.php
- includes/integrations/divi/class-convertkit-divi-module.php
- includes/integrations/elementor/class-convertkit-elementor-widget.php
- resources/backend/css/gutenberg.css
- resources/backend/js/gutenberg.js
- resources/backend/js/modal.js
- resources/backend/js/quicktags.js
- resources/backend/js/tinymce.js
- tests/_support/Helper/Acceptance/ConvertKitPlugin.php
- tests/acceptance/broadcasts/blocks-shortcodes/PageBlockBroadcastsCest.php
- tests/acceptance/forms/blocks-shortcodes/PageBlockFormCest.php
- tests/acceptance/forms/blocks-shortcodes/PageBlockFormTriggerCest.php
- tests/acceptance/general/RefreshResourcesButtonCest.php
- tests/acceptance/products/PageBlockProductCest.php
- views/backend/tinymce/modal-field.php
Adds refresh buttons to the Form, Form Trigger and Product blocks and shortcodes, allowing creators to refresh the list of cached resources (forms, products) after adding them to Kit, without having to navigate to Settings > Kit ([example ticket](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263837351253?view=List)).
- `testRefreshResourcesOnFormBlock`: Test that refreshing resources works on the Form block
- `testRefreshResourcesOnFormShortcodeUsingTinyMCE`: Test that refreshing resources works on the Form shortcode in the TinyMCE editor
- `testRefreshResourcesOnFormShortcodeUsingTextEditor`: Test that refreshing resources works on the Form shortcode in the text editor
- `testRefreshResourcesOnFormTriggerBlock`: Test that refreshing resources works on the Form …
> Add Refresh Resource Button to Blocks and Shortcode UI

- admin/section/class-convertkit-settings-general.php
- tests/acceptance/general/PluginSettingsGeneralCest.php
Fixes [this reported issue](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263837429149?view=List) where clicking Save Changes on the settings screen results in an uncaughty TypeError when a Kit account has no resources, and no checkboxes are checked.
- `testSettingsScreenWhenNoResources`: Updated test to save all settings when the Kit account has no resources and no checkboxes are checked on the settings screen.
> Settings: Fix Uncaught TypeError

- admin/class-convertkit-admin-settings-restrict-content.php
- admin/section/class-convertkit-admin-settings-broadcasts.php
- admin/section/class-convertkit-settings-base.php
- admin/section/class-convertkit-settings-general.php
- admin/section/class-convertkit-settings-oauth.php
- admin/section/class-convertkit-settings-tools.php
- includes/functions.php
- tests/acceptance.suite.yml
- tests/acceptance/general/PluginIntercomCest.php
- views/backend/setup-wizard/footer.php
Adds the Intercom help messenger to the Plugin's settings and setup wizard screens, to encourage users to seek support direct from Kit, instead of [leaving a review](https://wordpress.org/support/topic/removing-kit-help/).
The `user_id` isn't populated, as Identity Verification is enabled, requiring a `user_hash`.
- `PluginIntercomCest`: Test that the Intercom messenger displays on the Plugin and Wizard screens.
> Add Intercom to Settings and Setup Wizard Screens

- includes/class-convertkit-broadcasts-exporter.php
- tests/acceptance/broadcasts/import-export/BroadcastsExportCPTRowActionCest.php
This update extends the `Create Broadcast in Kit` option to be available when viewing a list of Pages and Custom Post Types, not just Posts.
Initially, this feature was designed to support only WordPress Posts, as blog posts are the most common content type used for Kit Broadcasts. However, based on [user feedback](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263837780674?view=List), this PR adds support for additional Post Types to improve flexibility.
- `BroadcastsExportCPTRowActionCest`: Added tests to confirm the export action displays / does not display on a Custom Post Type, depending on whether the functionality is enabled in the Plugin's settings.
> Add `Create Broadcast in Kit` to all Post Types

- resources/frontend/js/convertkit.js
Fixes [this reported issue](https://linear.app/kit/issue/WP-22/kit-for-wordpress-267-and-higher-results-in-needing-to-press-back), where the browser’s history would store the current URL twice due to JavaScript always calling `window.history.pushState` instead of `window.history.replaceState`
Whilst the browser’s back button correctly skips over the duplicate entry, taking the user back to the previous page, using the mouse back button requires two clicks to navigate back, as it does not automatically detect and skip duplicate entries.
This PR resolves by:
- only modifying the history state if a ck_subscriber_id query parameter is present, and
- uses `replaceState` to replace the current history entry, preventing duplicate entries.
There doesn't seem to be a Codeception method for …
> Remove `ck_subscriber_id`: Use `replaceState` instead of `pushState`

- admin/class-convertkit-admin-settings.php
- admin/section/class-convertkit-admin-section-base.php
- admin/section/class-convertkit-admin-section-broadcasts.php
- admin/section/class-convertkit-admin-section-general.php
- admin/section/class-convertkit-admin-section-oauth.php
- admin/section/class-convertkit-admin-section-restrict-content.php
- admin/section/class-convertkit-admin-section-tools.php
- includes/integrations/contactform7/class-convertkit-contactform7-admin-section.php
- includes/integrations/forminator/class-convertkit-forminator-admin-section.php
- includes/integrations/wishlist/class-convertkit-wishlist-admin-section.php
- wp-convertkit.php
Renames several PHP admin classes from `Admin_Settings` to `Admin_Section`, renames the files and moves the `ConvertKit_Admin_Settings_Restrict_Content` in to the `admin/section` folder to match the structure of the other settings sections.
> Rename Settings Classes to Sections

- tests/acceptance/restrict-content/general/RestrictContentFilterCPTCest.php
- tests/acceptance/restrict-content/general/RestrictContentFilterPageCest.php
- tests/acceptance/restrict-content/general/RestrictContentFilterPostCest.php
Adds missing tests for filter by Tag functionality in the WordPress Admin UI.
> Restrict Content: Tags: Add Filter Tests

- admin/section/class-convertkit-admin-section-restrict-content.php
- includes/class-convertkit-output-restrict-content.php
- includes/class-convertkit-settings-restrict-content.php
- resources/frontend/css/restrict-content.css
- resources/frontend/js/restrict-content.js
- tests/_support/Helper/Acceptance/ConvertKitRestrictContent.php
- tests/acceptance/restrict-content/general/RestrictContentCacheCest.php
- tests/acceptance/restrict-content/general/RestrictContentFilterCPTCest.php
- tests/acceptance/restrict-content/general/RestrictContentFilterPageCest.php
- tests/acceptance/restrict-content/general/RestrictContentFilterPostCest.php
- tests/acceptance/restrict-content/general/RestrictContentSettingsCest.php
- tests/acceptance/restrict-content/general/RestrictContentTagCest.php
- tests/acceptance/restrict-content/post-types/RestrictContentProductCPTCest.php
- tests/acceptance/restrict-content/post-types/RestrictContentProductPageCest.php
- tests/acceptance/restrict-content/post-types/RestrictContentProductPostCest.php
- views/frontend/restrict-content/code.php
- views/frontend/restrict-content/login-email.php
- views/frontend/restrict-content/login-modal-content-code.php
- views/frontend/restrict-content/login.php
- views/frontend/restrict-content/product.php
- views/frontend/restrict-content/tag.php
Refactors restrict content tests, adding a number of helper methods for repetitive test assertions.
> Restrict Content: Refactor Tests

- admin/class-convertkit-admin-post.php
- admin/class-convertkit-admin-restrict-content.php
- admin/section/class-convertkit-admin-section-restrict-content.php
- includes/class-convertkit-output-restrict-content.php
- includes/class-convertkit-resource-forms.php
- includes/class-convertkit-settings-restrict-content.php
- resources/frontend/css/restrict-content.css
- tests/_support/Helper/Acceptance/ConvertKitRestrictContent.php
- tests/acceptance/restrict-content/general/RestrictContentFilterCPTCest.php
- tests/acceptance/restrict-content/general/RestrictContentFilterPageCest.php
- tests/acceptance/restrict-content/general/RestrictContentFilterPostCest.php
- tests/acceptance/restrict-content/general/RestrictContentFormCest.php
- tests/acceptance/restrict-content/general/RestrictContentSettingsCest.php
- views/backend/post/bulk-edit.php
- views/backend/post/meta-box.php
- views/backend/post/quick-edit.php
- views/backend/post/wp-list-table-filter.php
- views/frontend/restrict-content/form.php
Adds functionality to gate content by Kit form, as requested in some tickets, with the option to login for existing subscribers, who receive a magic link / code by email, in the same way gating content by Tag and Product functions.
- `RestrictContentFormCest`: Test that gating content by form works
- `testFilterByForm`: Test that filtering Pages, Posts and Custom Post Types by form works
> Restrict Content by Form

- admin/section/class-convertkit-admin-section-general.php
- includes/class-convertkit-output.php
- includes/class-convertkit-settings.php
- tests/_support/Helper/Acceptance/ConvertKitPlugin.php
- tests/acceptance/forms/general/NonInlineFormCest.php
Adds an option to honor the 'None' setting at Page / Post level when form(s) are defined in the Plugin's `Default Forms (Site Wide)` setting. Requested in these tickets:
https://linear.app/kit/issue/WP-25/wordpress-p3-default-forms-site-wide-setting-seems-to-be-not-getting
https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263837959598?view=List
https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263837929550?view=List
https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263837935866?view=List
- `testPageLevelNoneSettingIgnored`: Test that the Page's 'None' setting is ignored when the Plugin's "do not display" setting is not checked.
- `testPageLevelNoneSettingHonored`: Test that the Page's 'None' setting is honored when …
> Default Forms (Site Wide): Honor `None` setting specified at Page / Post level

- composer.json
Use the latest WordPress Libraries, 2.0.6, instead of the `dev-add-form-referrer-support` branch.
Both are the same, but better to use the published version.
> Use WordPress Libraries 2.0.6

- includes/class-convertkit-output-broadcasts.php
- includes/class-wp-convertkit.php
- resources/frontend/css/broadcasts.css
- tests/acceptance/broadcasts/import-export/BroadcastsToPostsCest.php
- wp-convertkit.php
Adds a CSS class to the `<body>` tag of WordPress Posts, Pages and Custom Posts that were created/imported using the Kit Plugin's Broadcasts to Posts functionality.
This allows us and creators to provide CSS to override styling from some common themes that interferes with broadcast content, such as Elementor ([reported here](https://linear.app/kit/issue/WP-29/wp-medium-styling-issues-with-imported-broadcasts)).
Original Broadcast:
Before:
After:
- Updated existing tests to confirm CSS class is added to the body tag.
> Broadcasts to Posts: Add CSS class to 'body' tag

- admin/section/class-convertkit-admin-section-tools.php
- tests/_support/Helper/Acceptance/KitRestrictContent.php
- tests/acceptance/general/PluginSettingsToolsCest.php
Includes broadcast settings in the export JSON file generated at `Settings > Kit > Tools`, and imports those settings when a JSON export file is used.
- `testExportAndImportValidConfiguration`: Updated to include testing broadcast settings are exported and imported, and directly checks the database table on import for quicker test time.
> Tools: Import / Export: Include Broadcasts Settings

- admin/class-convertkit-admin-bulk-edit.php
- admin/class-convertkit-admin-category.php
- admin/class-convertkit-admin-post.php
- admin/class-convertkit-admin-refresh-resources.php
- admin/class-convertkit-admin-restrict-content.php
- admin/class-convertkit-admin-setup-wizard.php
- admin/class-convertkit-admin-tinymce.php
- admin/section/class-convertkit-admin-section-base.php
- admin/section/class-convertkit-admin-section-oauth.php
- admin/section/class-convertkit-admin-section-tools.php
- admin/setup-wizard/class-convertkit-admin-setup-wizard-landing-page.php
- admin/setup-wizard/class-convertkit-admin-setup-wizard-plugin.php
- admin/setup-wizard/class-convertkit-admin-setup-wizard-restrict-content.php
- includes/blocks/class-convertkit-block-broadcasts.php
- includes/blocks/class-convertkit-block.php
- includes/class-convertkit-ajax.php
- includes/class-convertkit-broadcasts-exporter.php
- includes/class-convertkit-output-restrict-content.php
- includes/class-convertkit-preview-output.php
- includes/class-convertkit-subscriber.php
- includes/class-wp-convertkit.php
- includes/integrations/forminator/class-convertkit-forminator.php
- phpcs.xml
- readme.txt
- wp-convertkit.php
Currently, we implement `WordPress-Docs` and `WordPress-Extra` (which, in turn implements `WordPress-Core`) coding standards.
However, switching this to the complete [`WordPress` ruleset](https://github.com/WordPress/WordPress-Coding-Standards?tab=readme-ov-file#standards-subsets) (which lists itself as comprising of `WordPress-Core`, `WordPress-Docs` and `WordPress-Extra`) introduces some additional rulesets.
This PR updates code to meet these coding standards, primarily covering checking and unslashing superglobals in PHP.
> Use `WordPress` Coding Standards ruleset

- includes/class-convertkit-subscriber.php
- tests/_support/Helper/Acceptance/KitRestrictContent.php
- tests/acceptance/broadcasts/import-export/BroadcastsToPostsCest.php
- tests/acceptance/general/SubscriberIDURLCest.php
- tests/acceptance/restrict-content/general/RestrictContentCacheCest.php
- tests/acceptance/restrict-content/general/RestrictContentFormCest.php
- tests/acceptance/restrict-content/general/RestrictContentSetupCest.php
- tests/acceptance/restrict-content/general/RestrictContentTagCest.php
- tests/acceptance/restrict-content/post-types/RestrictContentProductCPTCest.php
- tests/acceptance/restrict-content/post-types/RestrictContentProductPageCest.php
- tests/acceptance/restrict-content/post-types/RestrictContentProductPostCest.php
Creators using this plugin on WP Engine have reported that content remains cached when using the Member Content functionality, even after logging in as a Kit subscriber:
- [Issue WP-28: Member Content Access Issues on WP via Kit Plugin](https://linear.app/kit/issue/WP-28/wp-p3-member-content-access-issues-on-wp-via-kit-plugin)
- [Issue WP-21: Medium Member Content Not Unlocking for Subscribers](https://linear.app/kit/issue/WP-21/wp-medium-member-content-not-unlocking-when-a-subscriber-enters-their)
To address this, we’ve advised creators to exclude the `ck_subscriber_id cookie` from caching in WP Engine:
[WP Engine Custom Cache Exclusions](https://wpengine.com/support/cache/#Custom_Cache_Exclusions)
By default, however, WP Engine does not cache pages when a cookie starting with …
> Member Content: Add `wordpress_ck_subscriber_id` cookie

- includes/class-convertkit-output.php
This PR resolves [WP-31](https://linear.app/kit/issue/WP-31/wordpress-conflict-with-feast-plugin-possible-to-resolve-on-our-end), where third-party plugins using custom post types and the `the_content` filter inadvertently trigger the `append_form_to_content` method.
Previously, the existing `is_singular` check did not account for the actual post ID within the current filter context, causing the main post/page settings to be ignored.
This update ensures that the correct post ID is used, preserving expected behavior even when custom post types are involved.
> Append Form to Content: Check Post Type of main Post

- includes/class-wp-convertkit.php
Removes the call to `load_plugin_textdomain`, as [it's not needed since WordPress 4.6](https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/#Enhanced-support-for-only-using-PHP-translation-files):
> Reminder: if your plugin or theme is hosted on WordPress.org and is still using load_*_textdomain(), you can remove this call. Since WordPress 4.6, plugins and themes no longer need load_plugin_textdomain() or load_theme_textdomain(). WordPress automatically loads the translations for you when needed. If you still support older WordPress versions or do not host your plugin/theme on WordPress.org, move the function call to a later hook such as init.
> Remove `load_plugin_textdomain`

- includes/class-convertkit-output-restrict-content.php
[PHPStan 2.1.10](https://github.com/phpstan/phpstan/releases/tag/2.1.10), released Sunday 23rd March, now correctly detects a duplicate `array_key_exists` check that isn't necessary, which is removed in this PR.
> Remove duplicate `array_key_exists` check for `convertkit_post_id`

- includes/class-convertkit-output.php
- tests/EndToEnd/forms/general/NonInlineFormCest.php
Excludes non-inline forms defined in the Plugin's  `Default Forms (Site Wide)` setting from displaying on Search and 404, as this [wasn't intended to happen](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263838646672?view=List).
- Updated `NonInlineFormCest` to confirm non-inline site wide forms are not displayed on search and 404 screens.
> Exclude Default Forms (Site Wide) on Search and 404

- resources/backend/js/gutenberg-block-formatters.js
- resources/backend/js/gutenberg.js
- resources/backend/js/refresh-resources.js
Improves Gutenberg / block editor detection by checking if `wp.blockEditor` is undefined, instead of `wp.blocks`.
Page builders that don't use Gutenberg will typically result in `wp.blockEditor` being undefined, resulting in JS errors at present:
> Improve Gutenberg / Block Editor Detection

- tests/EndToEnd/forms/blocks-shortcodes/PageBlockFormCest.php
- tests/EndToEnd/forms/blocks-shortcodes/PageShortcodeFormCest.php
- tests/EndToEnd/forms/post-types/PageFormCest.php
The Jetpack Boost Plugin's latest update loads translations incorrectly, resulting in a PHP warning, which causes tests to fail due to checks the tests perform:
This PR resolves by suppressing the specific PHP notice, using the same method in #747
> Tests: Fix Jetpack Boost test failures

- .github/workflows/tests.yml
- includes/class-convertkit-output-restrict-content.php
- includes/integrations/class-convertkit-uncode.php
- tests/EndToEnd/restrict-content/post-types/RestrictContentProductActionHookCest.php
- tests/EndToEnd/restrict-content/post-types/RestrictContentProductPageCest.php
- tests/EndToEnd/restrict-content/post-types/RestrictContentProductThirdPartyThemeOrPageBuilderCest.php
- tests/Support/Helper/KitRestrictContent.php
- tests/Support/Helper/ThirdPartyPlugin.php
- wp-convertkit.php
Most Themes will run a Page / Post's content through WordPress' `the_content` filter, which the Kit Member Content functionality also uses to determine whether to display the gated login or not.
[Some Themes (such as Uncode) don't use this filter.](https://linear.app/kit/issue/WP-33/wp-p4-member-content-feature-not-working-with-uncode-theme) As a result, gated Page / Post content is incorrectly displayed.
This PR resolves by:
- adding the `convertkit_restrict_content_register_content_filter` action, allowing us to register Theme-specific logic for Member Content functionality,
- uses this new action when the Uncode theme is active
- `RestrictContentProductThirdPartyThemeOrPageBuilderCest`:  Tests Restrict Content by Product functionality on WordPress Pages when using a third party Theme …
> Restrict Content: Allow Themes to register own content filter

- includes/class-convertkit-output.php
- tests/EndToEnd/restrict-content/post-types/RestrictContentProductCPTCest.php
- tests/EndToEnd/restrict-content/post-types/RestrictContentProductPageCest.php
- tests/EndToEnd/restrict-content/post-types/RestrictContentProductPostCest.php
Fixes [this reported issue](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/mentions/conversation/12263838349736?view=List), where defining the `Add a Tag` setting on a Page that is also enabled for Member Content would result in a fatal error, due to the call to `tag_subscriber()` passing a signed subscriber ID, instead of the subscriber ID integer:
```
[25-Mar-2025 17:12:06 UTC] PHP Fatal error:  Uncaught TypeError: ConvertKit_API_V4::tag_subscriber(): Argument #2 ($subscriber_id) must be of type int, string given, called in /var/www/wp-content/plugins/convertkit/includes/class-convertkit-output.php on line 141 and defined in /var/www/wp-content/plugins/convertkit-for-woocommerce/vendor/convertkit/convertkit-wordpress-libraries/src/class-convertkit-api-traits.php:622
Stack trace: …
```
> Member Content: Use subscriber ID for tagging

- includes/integrations/class-convertkit-uncode.php
Following #804, the creator experienced duplicate Member Content gating on their Posts.
Switching to using the `uncode_single_content_final_output` provides better results:
> Restrict Content: Uncode Theme: Use `uncode_single_content_final_output` filter

- tests/EndToEnd/integrations/woocommerce/WooCommerceProductFormCest.php
WooCommerce 9.8.0 introduces a PHP deprecated notice due to their own Plugin using a method they've deprecated"
This PR resolves, ensuring tests pass, by setting the WooCommerce store in live mode, therefore bypassing the `is_store_page` check.
> Tests: Set WooCommerce Store in Live Mode

- admin/section/class-convertkit-admin-section-broadcasts.php
- admin/section/class-convertkit-admin-section-restrict-content.php
`add_action` shouldn't be used when hooking on a filter that returns data (in this case, `convertkit_admin_settings_register_sections`).
There [isn't a coding standard sniff](https://github.com/WordPress/WordPress-Coding-Standards/issues/713) to detect correct usage, and functionality has worked because `add_action` passes the request to `add_filter` anyway.
> Use `add_filter` for `convertkit_admin_settings_register_sections`

- wp-convertkit.php
Fixes these reported errors ([here](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/mentions/conversation/12263839025810?view=List) and [here](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263839057483?view=List)) in 2.7.8, where a fatal error occurs:
`An error of type E_ERROR was caused in line 79 of the file /home/customer/www/laurasteward.com/public_html/wp-content/plugins/convertkit/includes/class-wp-convertkit.php. Error message: Uncaught Error: Class "ConvertKit_Admin_Bulk_Edit" not found`
This is due to:
- both sites using SolidWP (previously iThemes Sync).  We had the same issue in Kit for WooCommerce in December 2022, which was fixed in [this PR](https://github.com/Kit/convertkit-woocommerce/pull/129),
- moving class initialization to WordPress' …
> Require all Plugin Files

- .github/workflows/tests.yml
- includes/class-wp-convertkit.php
- includes/integrations/divi/class-convertkit-divi-extension.php
- tests/EndToEnd/integrations/divi-builder/DiviPluginBroadcastsCest.php
- tests/EndToEnd/integrations/divi-builder/DiviPluginFormCest.php
- tests/EndToEnd/integrations/divi-builder/DiviPluginFormTriggerCest.php
- tests/EndToEnd/integrations/divi-builder/DiviPluginProductCest.php
- tests/EndToEnd/integrations/divi-theme/DiviThemeBroadcastsCest.php
- tests/EndToEnd/integrations/divi-theme/DiviThemeFormCest.php
- tests/EndToEnd/integrations/divi-theme/DiviThemeFormTriggerCest.php
- tests/EndToEnd/integrations/divi-theme/DiviThemeProductCest.php
- tests/Support/Helper/DiviBuilder.php
- tests/Support/Helper/WPCron.php
[WP Control 1.19.0](https://wordpress.org/plugins/wp-crontrol/) adds a confirmation popup when deleting a WordPress cron event, which caused the `testBroadcastsCronEventRecreatedWhenDeleted` test to fail.
> Tests: Fix Delete Cron Test

- .github/workflows/coding-standards.yml
- .github/workflows/tests.yml
- tests/EndToEnd/integrations/wlm/WishListMemberCest.php
Runs tests and coding standards against the latest PHP version, 8.4.
Enabled `WP_DEBUG` on all tests, excluding Elementor in PHP 8.4 due to Elementor returning a deprecated notice regarding Implicitly nullable parameter declarations:
https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated
> Run Tests and Coding Standards against PHP 8.4

- resources/backend/css/tinymce.css
Fixes the refresh button icon not displaying, and improves the button positioning when using the Text editor.
Before:
TinyMCE:
Text editor:
After:
TinyMCE:
Text editor:
> TinyMCE: Fix Refresh Button

- tests/EndToEnd/integrations/other/ForminatorCest.php
Forminator 1.43.0 changes the button label for quiz forms. This PR resolves by using a CSS selector to target the button, which should be more consistent.
> Tests: Fix Forminator Quiz Tests

- includes/class-convertkit-broadcasts-importer.php
- tests/Integration/BroadcastsImportTest.php
Removes emojis from the WordPress Post's Permalink when importing Broadcasts that contain emojis in the title.
Whilst emojis are supported in Permalinks, it's better to exclude them for readability, link sharing and SEO.
WordPress' `sanitize_title` will remove non-alphanumeric characters, and replace spaces with hyphens - however won't cover removal of emojis.
- `testGeneratePermalinkFunction`: Tests that emojis are removed from the given Broadcast title when parsed through the `generate_permalink` function.
> Broadcasts: Import: Remove emojis from Permalinks

- .github/workflows/tests.yml
Exchanges a v3 API Key and Secret for OAuth tokens, as currently OAuth tokens have to be manually generated and updated in Settings > Secret and Variables > Actions every ~ 2 days, due to their expiry. 
> Tests: Exchange API Key and Secret for OAuth Tokens

- DEPLOYMENT.md
`main` branch protection is now enabled, therefore bumping the Plugin version number and updating `readme.txt` must be submitted as a PR, rather than directly to the `main` branch.
This PR updates instructions to reflect the above when creating a new release. 
> Update Deployment Guide

- admin/class-convertkit-admin-restrict-content.php
- tests/EndToEnd/restrict-content/general/RestrictContentFilterCPTCest.php
- tests/EndToEnd/restrict-content/general/RestrictContentFilterPageCest.php
- tests/EndToEnd/restrict-content/general/RestrictContentFilterPostCest.php
- views/backend/post/wp-list-table-filter.php
When working on [this issue](https://linear.app/kit/issue/WP-46/wordpress-med-subscribers-being-added-to-kit-via-wp-plugin) to find any content that has Member Content functionality enabled, it was difficult using the current filter on the WP_List_Table, as current filters only permit filtering by a specific Form, Tag or Product:
This PR resolves by adding an `All member-only content` option to the filter dropdown.
- `RestrictContentFilterCPTCest:testFilterByAllMemberOnlyContent`: Test that filtering by 'All member-only content' works on the CPT screen.
- `RestrictContentFilterPageCest:testFilterByAllMemberOnlyContent`: Test that filtering by 'All member-only content' works on the Pages screen.
- `RestrictContentFiltePostCest:testFilterByAllMemberOnlyContent`: Test that filtering by 'All …
> Restrict Content: Filters: Add `All member-only content` option

- tests/Support/Helper/KitRestrictContent.php
- views/backend/post/bulk-edit.php
- views/backend/post/meta-box.php
- views/backend/post/quick-edit.php
- views/backend/setup-wizard/convertkit-restrict-content-setup/content-2.php
Replaces some errant `members only` strings with the correct `member-only` text, as raised [here](https://github.com/Kit/convertkit-wordpress/pull/833#discussion_r2162390559).
> Member Content: Replace “Members only” with “member-only”

- includes/blocks/broadcasts/block.json
- includes/blocks/class-convertkit-block-broadcasts.php
- includes/blocks/class-convertkit-block-form-trigger.php
- includes/blocks/class-convertkit-block-product.php
- includes/blocks/formtrigger/block.json
- includes/blocks/product/block.json
- tests/EndToEnd/broadcasts/blocks-shortcodes/PageBlockBroadcastsCest.php
- tests/EndToEnd/forms/blocks-shortcodes/PageBlockFormTriggerCest.php
- tests/EndToEnd/products/PageBlockProductCest.php
- tests/Support/Helper/KitForms.php
- tests/Support/Helper/KitProducts.php
Building on #844, adds the block editor's native typography controls to the Broadcasts, Form Trigger and Product blocks.
Also cleans up supports() and attributes() to be standardised, removing some now deprecated properties.
Before (e.g. Broadcasts block with no font size or line height options):
After (e.g. Broadcasts block with an XL font size and line height specified):
- `testBroadcastsBlockWithTypographyParameters`: Test the Broadcasts block's typography parameters work.
- `testFormTriggerBlockWithTypographyParameters`: Test the Form Trigger block's typography parameters work.
- `testProductBlockWithTypographyParameters`: Test the Product block's typography parameters work.
> Blocks: Add Typography Support

- .github/workflows/tests.yml
Fixes the WordPress Playground instances used when previewing a PR by setting the OAuth tokens before activating the Plugin.
Previously, Playground WASM would throw errors, resulting in Playground not displaying:
> WordPress Playground: Set Tokens before Plugin Activation

- .github/workflows/tests.yml
Adds a condition to only run the WordPress Playground step for PRs, not when merging to the `main` branch.
> WordPress Playground: Only run on PRs

- .distignore
Exclude `.devcontainer` and `phpstan-dev.neon` when the GitHub action publishes a new Plugin version / release to wordpress.org
> Exclude `.devcontainer` and `phpstan-dev.neon` from releases

- admin/class-convertkit-admin-restrict-content.php
- admin/class-multi-value-field-table.php
- tests/EndToEnd/restrict-content/general/RestrictContentFilterCPTCest.php
- tests/EndToEnd/restrict-content/general/RestrictContentFilterPageCest.php
- tests/EndToEnd/restrict-content/general/RestrictContentFilterPostCest.php
Fixes [this reported issue](https://linear.app/kit/issue/WP-52/wp-p3-posts-not-displaying-when-using-kit-plugin-v285) introduced in [this PR change](https://github.com/Kit/convertkit-wordpress/pull/851/files#diff-d6630bc83a6df4608fc924b4e626f22a5b6c4cf954c7d8d4828cab2b44dd5165L96-L102), that removed the check for whether the `convertkit_restrict_content` query parameter had a non-empty value.
This regression wasn’t caught earlier because there were no existing tests covering the behaviour of the WP_List_Table when the Filter button is clicked with the Member Content dropdown set to All content.
- `RestrictContentFilterPostCest:testNoFilteringWhenAllContentSelected`: Test that no filtering takes place when the filter is set to All Content on the Posts screen.
- …
> Member Content: Don’t filter WP_List_Table when no Member Content Filter selected

- includes/blocks/class-convertkit-block-form.php
- includes/class-convertkit-output-restrict-content.php
- includes/class-convertkit-output.php
- includes/class-convertkit-resource-forms.php
Adds a `data-kit-source-post-id` attribute to Form `<script>` tags when the Plugin's Debug setting is enabled, to help identify which Page or Post ID was used to embed a Form.
This was useful when [debugging this issue](https://linear.app/kit/issue/WP-54/wordpress-med-plugin-embedding-modal-forms-to-homepage-when-setting-is), where a home page had two modal form scripts outputting, and it wasn't clear which Posts were responsible for this, given the home page in question output some 30+ different Posts. 
> Forms: Debugging: Add `data-kit-source-post-id` Attribute

- resources/frontend/js/convertkit.js
The Plugin has always removed the `ck_subscriber_id` query param from the URL, storing it in the `ck_subscriber_id` cookie. This approach prevents users from unintentionally sharing URLs containing their `ck_subscriber_id`, for example on social media, where that ID could potentially grant access to gated content on a WordPress site: https://github.com/Kit/convertkit-wordpress/pull/169
Some developers need to access this in JS.  Currently, they may:
- inspect the `ck_subscriber_id` cookie for a value,
- inspect the JS `convertkit` object, which will include a subscriber_id when a valid `ck_subscriber_id` was included in the URL,
- in PHP, leverage the `get_subscriber_id()` method of the `ConvertKit_Subscriber` class
This PR adds a `convertkit_subscriber_id_removed_from_url` event to the …
> JS: Emit `convertkit_subscriber_id_removed_from_url` event

- includes/blocks/class-convertkit-block-form.php
- includes/blocks/form/block.json
- resources/backend/js/gutenberg-block-form.js
- tests/EndToEnd/forms/blocks-shortcodes/PageBlockFormCest.php
Adds the block editor's [native alignment option](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#align) to Forms:
- `testFormBlockWithAlignmentParameter`: Test that the alignment class is included in the block's output when an alignment option is chosen
> Forms: Add Align Block Option

- includes/blocks/class-convertkit-block-form-builder.php
- tests/EndToEnd/forms/blocks-shortcodes/PageBlockFormBuilderCest.php
Adds an optional setting to assign subscribers to a tag when they subscribe using the Form Builder's subscription form:
- `testFormBuilderBlockWithTaggingEnabled`: Test that the subscriber is tagged with the selected tag when configured on the Form Builder
> Block Editor: Form Builder: Tag Option

- includes/blocks/class-convertkit-block-form-builder-field-custom.php
- includes/blocks/class-convertkit-block-form-builder-field-email.php
- includes/blocks/class-convertkit-block-form-builder-field-name.php
- includes/blocks/class-convertkit-block-form-builder-field.php
- includes/blocks/class-convertkit-block-form-builder.php
- includes/blocks/form-builder-field-custom/block.json
- includes/class-convertkit-resource-custom-fields.php
- includes/class-wp-convertkit.php
- tests/EndToEnd/forms/blocks-shortcodes/PageBlockFormBuilderCest.php
- tests/EndToEnd/integrations/other/ContactForm7FormCest.php
- tests/EndToEnd/integrations/other/ForminatorCest.php
- tests/EndToEnd/integrations/wlm/WishListMemberCest.php
- tests/Support/Helper/KitAPI.php
- wp-convertkit.php
Returns the subscriber when using `apiCheckSubscriberExists()`, following how this is done for the other Plugins test libraries, such as WooCommerce.
This is used in #871 to test that a subscriber's first name custom field values were correctly set.
> Tests: Return Subscriber in `apiCheckSubscriberExists` helper

- includes/blocks/class-convertkit-block-form-builder.php
- tests/EndToEnd/forms/blocks-shortcodes/PageBlockFormBuilderCest.php
Enables Google's reCAPTCHA on the Form Builder, if the site and secret key is defined at `Kit > Settings > reCAPTCHA`
`testFormBuilderWithRecaptchaEnabled`: Test the Form Builder block works when reCAPTCHA is enabled.
`testFormBuilderWithRecaptchaEnabledAndHighMinimumScore`: Test the Form Builder block works when reCAPTCHA is enabled, and the minimum score is set to 0.99.
> Block Editor: Form Builder: Add reCAPTCHA support

- includes/blocks/class-convertkit-block-form-builder-field-custom.php
- includes/blocks/class-convertkit-block-form-builder-field.php
- resources/frontend/css/form-builder.css
- tests/EndToEnd/forms/blocks-shortcodes/PageBlockFormBuilderCest.php
Adds support for defining the input type on a Form Builder's Custom Field block
Future PR's could extend this to select dropdowns, checkboxes and radio buttons.
Updated exists tests to check each input type works correctly on the backend and frontend form.
> Form Builder: Custom Field: Add support for field type

- admin/section/class-convertkit-admin-section-general.php
- includes/class-convertkit-output.php
- includes/class-convertkit-resource-forms.php
- includes/class-convertkit-settings.php
- resources/frontend/js/convertkit.js
- tests/EndToEnd/forms/general/NonInlineFormCest.php
- tests/EndToEnd/general/plugin-screens/PluginSettingsGeneralCest.php
Loads the main `convertkit.js` script on all frontend requests, not just Posts/Pages.
This is required for #885, to set a cookie if a non-inline modal is loaded on the home page via the Site Wide setting.
> JS: Load on all pages

- admin/class-convertkit-wp-list-table.php
- admin/section/class-convertkit-admin-section-form-entries.php
- includes/class-convertkit-form-entries.php
- includes/integrations/contactform7/class-convertkit-contactform7-admin-section.php
- includes/integrations/forminator/class-convertkit-forminator-admin-section.php
- includes/integrations/wishlist/class-convertkit-wishlist-admin-section.php
- tests/EndToEnd/forms/blocks-shortcodes/PageBlockFormBuilderCest.php
- tests/Integration/FormEntriesTest.php
- tests/Support/Helper/KitPlugin.php
- wp-convertkit.php
Adds a section to the Kit Plugin's settings where form submissions made using Form Builder blocks with "Store form submissions" can be viewed.
Future PR's to follow to enable sorting, search, pagination and re-sending subscribers to the API. 
Tests in this PR.
> Form Builder: View Entries

- admin/class-convertkit-wp-list-table.php
- admin/section/class-convertkit-admin-section-form-entries.php
- includes/blocks/class-convertkit-block-form-builder.php
- includes/class-convertkit-form-entries.php
- includes/class-convertkit-setup.php
- includes/integrations/contactform7/class-convertkit-contactform7-admin-section.php
- includes/integrations/forminator/class-convertkit-forminator-admin-section.php
- includes/integrations/wishlist/class-convertkit-wishlist-admin-section.php
- phpcs.xml
- tests/EndToEnd/forms/blocks-shortcodes/PageBlockFormBuilderCest.php
- tests/EndToEnd/general/other/UpgradePathsCest.php
- tests/Integration/FormEntriesTest.php
- tests/Support/Helper/KitPlugin.php
- wp-convertkit.php
Renames the `Multi_Value_Table` class to `ConvertKit_WP_List_Table`, and removes some unused methods.
This class has been named this way since the Plugin's creation, and doesn't follow the naming convention of the Plugin's other classes starting with `ConvertKit_*`.
Further work on this class will follow when using it to display form submissions via the [Form Entries block](https://github.com/Kit/convertkit-wordpress/pull/886).
> Rename `Multi_Value_Table` class to `ConvertKit_WP_List_Table`

- includes/class-convertkit-form-entries.php
- tests/Integration/FormEntriesTest.php
Require a `post_id` be included when storing an entry from the Form Builder block.
- `testAddEntryWithNoPostID`: Test that a `WP_Error` is returned when no Post ID is included.
- `testUpsertEntryWithNoPostID`: Test that a `WP_Error` is returned when no Post ID is included.
> Form Builder: Store Entries: Require Post ID

- SETUP.md
- admin/section/class-convertkit-admin-section-broadcasts.php
- admin/section/class-convertkit-admin-section-form-entries.php
- admin/section/class-convertkit-admin-section-general.php
- admin/section/class-convertkit-admin-section-oauth.php
- admin/section/class-convertkit-admin-section-restrict-content.php
- admin/section/class-convertkit-admin-section-tools.php
- includes/integrations/contactform7/class-convertkit-contactform7-admin-section.php
- includes/integrations/forminator/class-convertkit-forminator-admin-section.php
- includes/integrations/wishlist/class-convertkit-wishlist-admin-section.php
- readme.txt
- tests/EndToEnd/general/plugin-screens/PluginSettingsGeneralCest.php
Updates documentation links in the Plugin to reflect changes:
- https://help.kit.com/en/articles/2502591-getting-started-the-wordpress-plugin redirects to https://help.kit.com/en/articles/2502591-how-to-set-up-the-kit-plugin-on-your-wordpress-website, so replaced these links with the new one (https://help.kit.com/en/articles/2502591-how-to-set-up-the-kit-plugin-on-your-wordpress-website)
- Broadcasts has its own documentation: https://help.kit.com/en/articles/9669096-publish-broadcasts-as-wordpress-posts-and-vice-versa
- Member Content has its own documentation: https://help.kit.com/en/articles/7896769-how-to-customize-your-kit-subscribers-experience-on-your-wordpress-website
> Update Documentation Links

- admin/section/class-convertkit-admin-section-base.php
- admin/section/class-convertkit-admin-section-broadcasts.php
- admin/section/class-convertkit-admin-section-general.php
- admin/section/class-convertkit-admin-section-oauth.php
- admin/section/class-convertkit-admin-section-restrict-content.php
- admin/section/class-convertkit-admin-section-tools.php
- tests/EndToEnd/general/plugin-screens/PluginIntercomCest.php
Load Intercom's script in the `ConvertKit_Admin_Section_Base` class, as all settings classes use this. There's no need to repeat this filter hook call all settings screens.
Updated tests to include Form Entries settings screen, and confirm Intercom does not load on a non-Plugin screen.
> Improve Intercom Integration

- includes/blocks/class-convertkit-block-form-builder.php
- resources/frontend/css/form-builder.css
- tests/EndToEnd/forms/blocks-shortcodes/PageBlockFormBuilderCest.php
Previously, when the `Display form` option was disabled, no message would show after submitting the form to tell the subscriber that they did successfully subscribe.
This PR resolves by always showing the subscribed message, regardless of whether the form continues to display or not.
Updated tests to check that the subscribed message displays.
> Form Builder: Always display subscribed message

- tests/Support/Helper/ThirdPartyPlugin.php
In [wp-browser 4.5.6](https://github.com/lucatume/wp-browser/releases/tag/4.5.6), the selector used to activate or deactivate a plugin was updated - moving from the  bulk action checkboxes on the Plugins screen to the individual Activate/Deactivate links.
As a result, this plugin’s tests fail because they attempt to deactivate plugins without first checking if they are active. When a plugin is inactive, the Deactivate link is not available, which leads to test failures.
This PR resolves by using the bulk actions to activate/deactivate Plugins, as wp-browser did in < 4.5.6. Using the deactivation link isn't guaranteed to work, because many Plugins hijack this with their own UI to survey the user on why they're deactivating a Plugin vs. just honoring the request.
> Tests: Fix Plugin Deactivation in wp-browser 4.5.6+

- TESTING.md
Adds a table of composer commands that can be used for testing, coding standards and static analysis:
https://github.com/Kit/convertkit-wordpress/blob/update-developer-docs/TESTING.md#prerequisites
> Update Testing Docs

- includes/blocks/class-convertkit-block-form-builder.php
- languages/convertkit.pot
Fix a typo in the Form Builder's description:
> Form Builder: Fix Typo

- .eslintrc.js
- resources/backend/js/bulk-edit.js
- resources/backend/js/editor.js
- resources/backend/js/gutenberg-block-form.js
- resources/backend/js/gutenberg-block-formatters.js
- resources/backend/js/gutenberg.js
- resources/backend/js/modal.js
- resources/backend/js/preview-output.js
- resources/backend/js/quick-edit.js
- resources/backend/js/quicktags.js
- resources/backend/js/refresh-resources.js
- resources/backend/js/select2.js
- resources/backend/js/settings-conditional-display.js
- resources/backend/js/setup-wizard.js
- resources/backend/js/tabs.js
- resources/backend/js/tinymce-broadcasts.js
- resources/backend/js/tinymce-content.js
- resources/backend/js/tinymce-form.js
- resources/backend/js/tinymce-formtrigger.js
- resources/backend/js/tinymce-product.js
- resources/backend/js/wp-list-table-buttons.js
Implement WordPress' recommended configuration for JS coding standards / linting on backend JS code:
https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#installation
https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#lint-js
Separate PRs to follow for Gutenberg backend JS coding standards, for ease of review.
The GitHub action's coding-standards includes a new step to check JS coding standards.
> Add JS Coding Standards: Backend

- .eslintrc.js
- .github/workflows/coding-standards.yml
Explains why some JS standards are disabled, and updates the GitHub action to just call `npm install`, as `package.json` defines what will be installed.
> Improve JS Rules and Workflow
